(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/code.mli *)
(* [oxcaml] = true *)

open! Stdlib

module Addr : sig
  type t = int

  val to_string : t -> string

  val zero : t

  val succ : t -> t

  val pred : t -> t

  module Set = Int_set
  module Map = Int_trie

  module Hashtbl : Hashtbl.S with type key = t
end

module Var : sig
  type t [@@ocaml.immediate]

  val print : Format.formatter -> t -> unit

  val equal : t -> t -> bool

  val idx : t -> int

  val of_idx : int -> t

  val fresh : unit -> t

  val fresh_n : string -> t

  val fork : t -> t

  val count : unit -> int

  val compare : t -> t -> int

  val get_name : t -> string option

  val set_name : t -> ?generated:bool -> string -> unit

  val generated_name : t -> bool

  val propagate_name : t -> t -> unit

  val forget_generated_name : t -> unit

  val reset : unit -> unit

  val set_last : int -> unit
  [@@ocaml.doc
    " Set the index of the last allocated variable; subsequent calls to\n\
    \      [fresh] return higher indices. "]

  val last : unit -> t [@@ocaml.doc " The last allocated variable. "]

  module Set : Int_set.S with type elt = t

  module Map : Map.S with type key = t

  module Hashtbl : Hashtbl.S with type key = t

  module Tbl : sig
    type key = t

    type 'a t

    type size = unit

    val get : 'a t -> key -> 'a

    val set : 'a t -> key -> 'a -> unit

    val length : 'a t -> int

    val make : size -> 'a -> 'a t

    val iter : (key -> 'a -> unit) -> 'a t -> unit
  end

  module ISet : sig
    type elt = t

    type t

    val empty : unit -> t

    val iter : (elt -> unit) -> t -> unit

    val mem : t -> elt -> bool

    val add : t -> elt -> unit

    val remove : t -> elt -> unit

    val copy : t -> t
  end
end

type cont = Addr.t * Var.t list

type prim =
  | Vectlength of Optimization_hint.array_kind
  | Array_get
  | Extern of string * Optimization_hint.ccall option
  | Not
  | IsInt
  | Eq
  | Neq
  | Lt
  | Le
  | Ult

type array_or_not =
  | Array
  | NotArray
  | Unknown

module Native_string : sig
  type t = private
    | Byte of string
    | Utf of Utf8_string.t

  val of_string : string -> t

  val of_bytestring : string -> t

  val equal : t -> t -> bool
end

type constant =
  | String of string
  | NativeString of Native_string.t
  | Float of Int64.t
  | Float32 of Int64.t
  | Float_array of Int64.t array
  | Int of Targetint.t
  | Int32 of Int32.t
      [@ocaml.doc " Only produced when compiling to WebAssembly. "]
  | Int64 of Int64.t
  | NativeInt of Targetnativeint.t
  | Tuple of int * constant array * array_or_not
  | Null_

module Constant : sig
  type t = constant

  val ocaml_equal : t -> t -> bool option
  [@@ocaml.doc
    " Guaranteed equality in terms of OCaml [(=)]: if [constant_equal a b =\n\
    \    Some v], then [Poly.equal a b = v]. This is used for optimization \
     purposes. "]
end

type loc =
  | No
  | Before of Addr.t
  | After of Addr.t

val noloc : loc

val location_of_pc : int -> loc

type prim_arg =
  | Pv of Var.t
  | Pc of constant

type special = Alias_prim of string

type mutability =
  | Immutable
  | Maybe_mutable

type field_type =
  | Non_float
  | Float

type yielding_kind =
  | Unyielding
  | May_yield
  | Unknown

type expr =
  | Apply of
      { f : Var.t;
        args : Var.t list;
        exact : bool;
        yielding : yielding_kind
      }
  | Block of int * Var.t array * array_or_not * mutability
  | Field of Var.t * int * field_type
  | Closure of
      Var.t list
      * cont
      * (Optimization_hint.closure_hint option * Parse_info.t option)
  | Constant of constant
  | Prim of prim * prim_arg list
  | Special of special

type instr =
  | Let of Var.t * expr
  | Assign of Var.t * Var.t
  | Set_field of Var.t * int * field_type * Var.t
  | Offset_ref of Var.t * int
  | Array_set of Var.t * Var.t * Var.t
  | Event of Parse_info.t

type last =
  | Return of Var.t
  | Raise of Var.t * [`Normal | `Notrace | `Reraise]
  | Stop
  | Branch of cont
  | Cond of Var.t * cont * cont
  | Switch of Var.t * cont array
  | Pushtrap of cont * Var.t * cont
  | Poptrap of cont

type block =
  { params : Var.t list;
    body : instr list;
    branch : last
  }

type program =
  { start : Addr.t;
    blocks : block Addr.Map.t;
    free_pc : Addr.t
  }

module Marshalable_program : sig
  type t

  val of_program : program -> t

  val to_program : t -> program
end
[@@ocaml.doc " A [program] in a form that can be marshaled. "]

type cmj_body =
  { program : Marshalable_program.t;
    last_var : int;
        [@ocaml.doc
          " Highest variable index used in [program]. [Var] keeps this in \
           mutable\n\
          \            state, so [ocamlj] must communicate it to [js_of_ocaml] \
           to keep the\n\
          \            two in sync. "]
    imported_compilation_units : string list;
        [@ocaml.doc
          " Full paths of the compilation units whose symbols [program] fetches\n\
          \            from the global symbol table. Needed to fill in \
           [Unit_info.t]. "]
    exported_compilation_unit : string
        [@ocaml.doc
          " Full path of the compilation unit [program] defines. Needed to fill\n\
          \            in [Unit_info.t]. "]
  }
[@@ocaml.doc
  " Contents of a [.cmj] file produced by OxCaml's [ocamlj] (after the magic\n\
  \    number), marshaled. "]

module Print : sig
  type xinstr =
    | Instr of instr
    | Last of last

  val expr : Format.formatter -> expr -> unit

  val constant : Format.formatter -> constant -> unit

  val var_list : Format.formatter -> Var.t list -> unit

  val instr : Format.formatter -> instr -> unit

  val block :
    Format.formatter -> (Addr.t -> xinstr -> string) -> int -> block -> unit

  val program :
    Format.formatter -> (Addr.t -> xinstr -> string) -> program -> unit

  val last : Format.formatter -> last -> unit

  val cont : Format.formatter -> cont -> unit
end

type 'c fold_blocs =
  block Addr.Map.t -> Addr.t -> (Addr.t -> 'c -> 'c) -> 'c -> 'c

type fold_blocs_poly = { fold : 'a. 'a fold_blocs } [@@unboxed]

val fold_closures :
  program ->
  (Var.t option -> Var.t list -> cont -> Parse_info.t option -> 'd -> 'd) ->
  'd ->
  'd
[@@ocaml.doc
  " [fold_closures p f init] folds [f] over all closures in the program [p],\n\
  \    starting from the initial value [init]. For each closure, [f] is called\n\
  \    with the following arguments: the closure name (enclosed in\n\
  \    {!Stdlib.Some}), its parameter list, the address and parameter \
   instantiation\n\
  \    of its first block, the optional closure location and the current \
   accumulator.\n\
  \    In addition, [f] is called on the initial block [p.start], with\n\
  \    [None] as the closure name.  All closures in all blocks of [p] are\n\
  \    included in the fold, not only the ones reachable from\n\
  \    [p.start]. "]

val fold_closures_innermost_first :
  program ->
  (Var.t option -> Var.t list -> cont -> Parse_info.t option -> 'd -> 'd) ->
  'd ->
  'd
[@@ocaml.doc
  " Similar to {!fold_closures}, but applies the fold function to the\n\
  \    innermost closures first. Unlike with {!fold_closures}, only the closures\n\
  \    reachable from [p.start] are considered. "]

val fold_closures_outermost_first :
  program ->
  (Var.t option -> Var.t list -> cont -> Parse_info.t option -> 'd -> 'd) ->
  'd ->
  'd
[@@ocaml.doc
  " Similar to {!fold_closures}, but applies the fold function to the\n\
  \    outermost closures first. Unlike with {!fold_closures}, only the closures\n\
  \    reachable from [p.start] are considered. "]

val fold_children : 'c fold_blocs

val fold_children_skip_try_body : 'c fold_blocs

val poptraps : block Addr.Map.t -> Addr.t -> Addr.Set.t

val return_values : program -> Var.Set.t Var.Map.t

val traverse :
  fold_blocs_poly ->
  (Addr.t -> 'c -> 'c) ->
  Addr.t ->
  block Addr.Map.t ->
  'c ->
  'c

val preorder_traverse :
  fold_blocs_poly ->
  (Addr.t -> 'c -> 'c) ->
  Addr.t ->
  block Addr.Map.t ->
  'c ->
  'c

val last_instr : instr list -> instr option
[@@ocaml.doc " Last instruction of a block body, ignoring events "]

val used_blocks : program -> BitSet.t

val prepend : program -> instr list -> program

val empty : program

val compact : program -> program

val is_empty : program -> bool

val equal : program -> program -> bool

val print_diff : program -> program -> unit

val check_updates : name:string -> program -> program -> updates:int -> unit

val invariant : program -> unit

val cont_equal : cont -> cont -> bool

val cont_compare : cont -> cont -> int
