(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/parse_info.mli *)
(* [oxcaml] = true *)

type t =
  { src : string option;
    name : string option;
    col : int;
    line : int;
    idx : int
  }

val zero : t

val equal : t -> t -> bool

val t_of_lexbuf : Lexing.lexbuf -> t

val t_of_pos : Lexing.position -> t

val start_position : t -> Lexing.position

val t_of_position : src:string option -> Lexing.position -> t

val to_string : t -> string
