(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/parse_info.ml *)
(* [oxcaml] = true *)

open! Stdlib

type t =
  { src : string option;
    name : string option;
    col : int;
    line : int;
    idx : int
  }

let zero = { src = None; name = None; col = 0; line = 0; idx = 0 }

let equal a b =
  a.line = b.line && a.col = b.col && a.idx = b.idx
  && Option.equal String.equal a.src b.src
  && Option.equal String.equal a.name b.name

let t_of_pos start_p =
  let idx = start_p.Lexing.pos_cnum in
  let line, col = start_p.pos_lnum, start_p.pos_cnum - start_p.pos_bol in
  let name = Some start_p.pos_fname in
  let src = Some start_p.pos_fname in
  { idx; line; col; name; src }

let t_of_lexbuf lexbuf : t = t_of_pos lexbuf.Lexing.lex_start_p

let start_position (t : t) =
  { Lexing.pos_fname = Option.value ~default:"" t.name;
    pos_lnum = t.line;
    pos_bol = t.idx - t.col;
    pos_cnum = t.idx
  }

let t_of_position ~src pos =
  { name = Some pos.Lexing.pos_fname;
    src;
    line = pos.Lexing.pos_lnum;
    col = pos.Lexing.pos_cnum - pos.Lexing.pos_bol;
    idx = 0
  }

let to_string { name; src; line; col; _ } =
  match name, src with
  | (None | Some ""), (None | Some "") -> "?"
  | _ ->
    let file =
      match name, src with
      | (None | Some ""), Some file -> file
      | Some file, (None | Some "") -> file
      | Some file, Some _file -> file
      | None, None -> assert false
    in
    Format.sprintf "%s:%d:%d" file line col
