(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/reserved.ml *)
(* [oxcaml] = true *)

open! Stdlib

let keyword =
  List.fold_left
    ~f:(fun acc x -> StringSet.add x acc)
    ~init:StringSet.empty
    [ "break";
      "case";
      "catch";
      "continue";
      "debugger";
      "default";
      "delete";
      "do";
      "else";
      "finally";
      "for";
      "function";
      "if";
      "in";
      "instanceof";
      "new";
      "return";
      "switch";
      "this";
      "throw";
      "try";
      "typeof";
      "var";
      "void";
      "while";
      "with";
      "class";
      "const";
      "enum";
      "export";
      "extends";
      "import";
      "super";
      "implements";
      "interface";
      "let";
      "package";
      "private";
      "protected";
      "public";
      "static";
      "yield";
      "null";
      "true";
      "false";
      "NaN";
      "undefined";
      "eval";
      "arguments";
      "await" ]

let provided =
  List.fold_left
    ~f:(fun acc x -> StringSet.add x acc)
    ~init:StringSet.empty
    [ "event";
      "location";
      "window";
      "document";
      "eval";
      "navigator";
      "self";
      "Array";
      "Function";
      "Date";
      "Math";
      "JSON";
      "Object";
      "globalThis";
      "RegExp";
      "String";
      "Boolean";
      "Number";
      "BigInt";
      "Infinity";
      "isFinite";
      "ActiveXObject";
      "XMLHttpRequest";
      "XDomainRequest";
      "DOMException";
      "Error";
      "SyntaxError";
      "TypeError";
      "arguments";
      "decodeURI";
      "decodeURIComponent";
      "encodeURI";
      "encodeURIComponent";
      "escape";
      "unescape";
      "isNaN";
      "parseFloat";
      "parseInt";
      "module";
      "require";
      "Symbol";
      "ArrayBuffer";
      "DataView";
      "Float32Array";
      "Float64Array";
      "Int16Array";
      "Int32Array";
      "Int8Array";
      "TextDecoder";
      "TextEncoder";
      "Uint16Array";
      "Uint32Array";
      "Uint8Array";
      "Uint8ClampedArray";
      "URL";
      "atob";
      "btoa";
      "clearInterval";
      "console";
      "global";
      "importScripts";
      "performance";
      "setTimeout";
      "Map";
      "Set";
      "WeakRef";
      "WeakMap";
      "FinalizationRegistry";
      "WebAssembly";
      "Promise";
      "fetch";
      "crypto" ]
