(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/targetnativeint.ml *)
(* [oxcaml] = true *)

include Sizable_int.Make (struct
  let name = "Targetnativeint"

  let allowed_sizes = [| 64; 32 |]
end)
