(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/timer.ml *)
(* [oxcaml] = true *)

open! Stdlib

type t =
  { get_time : unit -> float;
    start : float
  }

let make ?(get_time = Sys.time) () = { get_time; start = get_time () }

let get t = t.get_time () -. t.start

let print f t = Format.fprintf f "%.2f" (get t)
