(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/timer.mli *)
(* [oxcaml] = true *)

type t

val make : ?get_time:(unit -> float) -> unit -> t

val get : t -> float

val print : Format.formatter -> t -> unit
