#
# Build rules common to ocaml-ox and oxcaml
#

ws_boot   = --root=. --workspace=duneconf/boot.ws
ws_runstd = --root=. --workspace=duneconf/runtime_stdlib.ws
ws_main   = --root=. --workspace=duneconf/main.ws

ifeq ($(coverage),yes)
  coverage_dune_flags=--instrument-with bisect_ppx
  ocaml_subdirs_to_ignore=otherlibs
else
  coverage_dune_flags=
  ocaml_subdirs_to_ignore=
endif

define dune_boot_context
(lang dune 2.8)
; We need to call the boot context "default" so that dune selects it for merlin
(context (default
  (name default)
  (profile dev)
  (env (_
    (flags (:standard -warn-error +A -alert -unsafe_multidomain -alert -unsafe_effects))
    (env-vars
      ("OCAMLPARAM" "")

      ; Avoid using the full OC_CFLAGS for C code compiled during the boot
      ; In particular, we should avoid using ASan here even if it is otherwise
      ; enabled, since (a) it is of little benefit, because it has no effect
      ; on the final compiler, and (b) it breaks, because linking is missing
      ; the matching -fsanitize=address flag
      ("OC_CFLAGS_SEXP" "boot_oc_cflags.sexp"))))))
endef

ifneq ($(origin BUILD_OCAMLPARAM), undefined)
ENV_VARS := (env-vars ("OCAMLPARAM" "$(BUILD_OCAMLPARAM)"))
else
ENV_VARS :=
endif

ifeq ($(main_build_profile),dev)
main_ocamlopt_optimization_flags :=
else
main_ocamlopt_optimization_flags := -O3
endif

define dune_runtime_stdlib_context
(lang dune 3.23)
(using oxcaml 0.1)
(context (default
  (name runtime_stdlib)
  (profile main)
  (cms_cmt_dependency cms)
  (paths
    (PATH ("$(CURDIR)/_build/_bootinstall/bin" :standard))
    (OCAMLLIB ("$(CURDIR)/_build/_bootinstall/lib/ocaml")))
  (env (_
    (bin_annot_cms true)
    (flags (:standard -directory stdlib -warn-error +A -alert -unsafe_multidomain -alert -unsafe_effects))
    $(ENV_VARS)))))
endef

define dune_main_context
(lang dune 3.23)
(using oxcaml 0.1)
(context (default
  (name main)
  (profile $(main_build_profile))
  (cms_cmt_dependency cms)
  (paths
    (PATH ("$(CURDIR)/_build/_bootinstall/bin" :standard))
    (OCAMLLIB ("$(CURDIR)/_build/runtime_stdlib_install/lib/ocaml_runtime_stdlib")))
  (env (_
    (bin_annot_cms true)
    (flags (:standard -directory compiler-distro -warn-error +A -alert -unsafe_multidomain -alert -unsafe_effects))
    ; We never want to build the compiler itself with AddressSanitizer enabled.
    (ocamlopt_flags (:standard $(main_ocamlopt_optimization_flags) -fno-asan))
    $(ENV_VARS)))))
endef


.DEFAULT_GOAL := compiler
.PHONY: boot-compiler boot-runtest runtime-stdlib compiler runtest runtest-llvmize runtest-dwarf

boot_targets = \
  $(boot_ocamlc) \
  $(boot_ocamlopt) \
  $(boot_ocamlj) \
  $(boot_ocamlmklib) \
  $(boot_ocamldep) \
  $(boot_ocamlobjinfo) \
  ocamltest/ocamltest.native

boot-compiler: _build/_bootinstall
	$(dune) build $(ws_boot) $(coverage_dune_flags) @merlin-support $(boot_targets)

boot-runtest: boot-compiler
	$(dune) build $(ws_boot) $(coverage_dune_flags) --force $(runtest_targets)

runtime-stdlib: boot-compiler
	$(dune) build $(ws_runstd) --only-package=ocaml_runtime_stdlib @install
	rm -rf _build/runtime_stdlib_install
# Dune 3.11+ clears `_build/install` before building, move the runtime stdlib
# to a separate directory.
	$(cpl) -R _build/install/runtime_stdlib _build/runtime_stdlib_install
# Dune does not believe the compiler can make .cmxs unless the following file exists.
	@touch _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/dynlink.cmxa
# Dune will look here if the system compiler is OCaml 5 instead.
	@mkdir -p _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/dynlink/
	@touch _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/dynlink/dynlink.cmxa

# This target is a polling version of "make runtime-stdlib"
.PHONY: runtime-stdlib-hacking
runtime-stdlib-hacking: boot-compiler
	$(dune) build -w $(ws_runstd) --only-package=ocaml_runtime_stdlib @install

compiler: runtime-stdlib
	SYSTEM=$(SYSTEM) MODEL=$(MODEL) \
          ASPP="$(ASPP)" ASPPFLAGS="$(ASPPFLAGS)" \
          $(dune) build $(ws_main) \
          --only-package=ocaml @install \
          tools/regalloc/regalloc.exe \
          oxcaml/testsuite/tools/expect.exe \
          oxcaml/testsuite/tools/expectnat.exe \
          oxcaml/testsuite/tools/codegen_main.exe \
          oxcaml/testsuite/tools/asmgen_$(ARCH).o \
          testsuite/lib/lib.cm{,x}a \
          testsuite/lib/testing.cm{,x}a \
          @middle_end/flambda2/tests/tools/all \
          $(ocamldir)/tools/dumpobj.bc

.PHONY: minimize-failure
minimize-failure: boot-minimizer boot-compiler runtime-stdlib
	SYSTEM=$(SYSTEM) MODEL=$(MODEL) \
          ASPP="$(ASPP)" ASPPFLAGS="$(ASPPFLAGS)" \
          ./_build/default/chamelon/chamelon.exe dune build \
          $(ws_main) \
          --only-packages=ocaml @install \
          tools/regalloc/regalloc.exe \
          oxcaml/testsuite/tools/expect.exe \
          oxcaml/testsuite/tools/expectnat.exe \
          oxcaml/testsuite/tools/codegen_main.exe \
          oxcaml/testsuite/tools/asmgen_$(ARCH).o \
          testsuite/lib/lib.cm{,x}a \
          testsuite/lib/testing.cm{,x}a \
          $(ocamldir)/tools/dumpobj.bc

.PHONY: minimize-stdlib
minimize-stdlib: boot-minimizer boot-compiler
	./_build/default/chamelon/chamelon.exe dune build \
          $(ws_runstd) \
          --only-packages=ocaml_runtime_stdlib @install

# We want to be able to build the @runtest dune alias, but exclude
# external/merlin from that (since Merlin only builds in the boot workspace).
# Dune doesn't offer a native way to do this, so instead we list all directories
# and build @runtest in each directory, excluding external/merlin and any
# directories not in the dune workspace. (We can exclude external/ as a whole
# since all the non-merlin directories in that folder are vendored anyways.)
runtest_targets := $(sort $(addprefix @, $(addsuffix runtest, $(filter-out autom4te.cache/ build-aux/ external/ _%, $(dir $(wildcard */.))))))

# CR dkalinichenko: [runtest] is built using the main profile,
# which uses the boot compiler. Use the final compiler for [runtest],
# and implement [runtest-upstream-boot] for testing when the final compiler
# itself is miscompiled.
runtest: compiler
	OXCAML_NAME_MANGLING=$(NAME_MANGLING_SCHEME) OXCAML_POLL_INSERTION=$(POLL_INSERTION) $(dune) build $(ws_main) $(runtest_targets)

runtest-llvmize: compiler
	OXCAML_NAME_MANGLING=$(NAME_MANGLING_SCHEME) $(dune) build @runtest-llvmize $(ws_main)

runtest-dwarf: compiler
	OXCAML_NAME_MANGLING=$(NAME_MANGLING_SCHEME) $(dune) build @runtest-dwarf $(ws_main)

# This Makefile supports old versions that don't have $(file), so we're using
# environment var trickery to get a multiline string into a file
duneconf/boot.ws: export contents = $(dune_boot_context)
duneconf/runtime_stdlib.ws: export contents = $(dune_runtime_stdlib_context)
duneconf/main.ws: export contents = $(dune_main_context)
duneconf/%.ws:
	echo "$$contents" > $@

# We need to disable ocaml/otherlibs when compiling with coverage, because we
# need to compile against the user's opam instead. Unfortunately, Dune gives us
# no nicer way of declaring data_only_dirs differently in different workspaces,
# so we have to output a file to be included in ocaml/dune.
#
# Also, Dune only allows one (data_only_dirs) declaration per file, so here we
# have to account for the declaration that would already have been in
# ocaml/dune.
$(ocamldir)/duneconf/dirs-to-ignore.inc:
	echo "(data_only_dirs yacc $(ocaml_subdirs_to_ignore))" > $@

# Targets that should be prerequisites to any target that runs Dune
dune_config_targets = \
  duneconf/boot.ws \
  duneconf/runtime_stdlib.ws \
  duneconf/main.ws \
  $(ocamldir)/duneconf/dirs-to-ignore.inc \
  $(ocamldir)/duneconf/ox-extra.inc \
  dune-project

_build/_bootinstall: Makefile.config $(dune_config_targets)
	echo -n '$(NATDYNLINKOPTS)' > $(ocamldir)/natdynlinkops

# flags.sexp
# Do not include :standard as it is ignored
# See: https://github.com/ocaml/dune/issues/13225
	echo '($(if $(filter true,$(FUNCTION_SECTIONS)),-function-sections,))' > ocamlopt_upstream_flags.sexp
	echo '($(OXCAML_DWARF_FLAGS_FOR_COMPILER) $(ASSEMBLY_FLAG_FOR_COMPILER) $(if $(filter true,$(FUNCTION_SECTIONS)),-function-sections,))' > ocamlopt_oxcaml_flags.sexp
	echo '( )' > boot_oc_cflags.sexp
	echo '( $(OC_CFLAGS) )' > oc_cflags.sexp
	echo '( $(subst -I $(ROOTDIR)/,-I $(CURDIR)/,$(OC_CPPFLAGS)) )' > oc_cppflags.sexp
	echo '( $(SHAREDLIB_CFLAGS) )' > sharedlib_cflags.sexp

# _build/_bootinstall: a minimal install directory for the boot compiler,
# which is placed on PATH for subsequent builds
	rm -rf _build/_bootinstall
	mkdir -p _build/_bootinstall/{bin,lib/ocaml}
	cp $^ _build/_bootinstall/lib/ocaml
	ln -sf ../../default/$(boot_ocamlopt) _build/_bootinstall/bin/ocamlopt.opt
	ln -sf ../../default/$(boot_ocamlc) _build/_bootinstall/bin/ocamlc.opt
	ln -sf ../../default/$(boot_ocamlj) _build/_bootinstall/bin/ocamlj.opt
	ln -sf ../../default/$(boot_ocamlmklib) _build/_bootinstall/bin/ocamlmklib.opt
	ln -sf ../../default/$(boot_ocamldep) _build/_bootinstall/bin/ocamldep.opt
	ln -sf ../../default/$(boot_ocamlobjinfo) _build/_bootinstall/bin/ocamlobjinfo.opt
	ln -sf "`$(opam_exec) which ocamllex`" _build/_bootinstall/bin/ocamllex.opt
	for prog in ocamlopt ocamlj ocamlc ocamllex ocamldep ocamlmklib; do \
	  ln -sf "$$prog.opt" "_build/_bootinstall/bin/$$prog"; \
	done

# save a bit of disk space in build trees by using cp -l on Linux
# (not available on e.g. OS X)
cpl=$(if $(filter linux,$(SYSTEM)),cp -l,cp -L)

# Assemble the contents of the install directory in _install
# This is needed to run the upstream testsuite (see runtest-upstream below)
# We use a local directory rather than the final install path, since
# the final install path may be on a different filesystem (and hence be
# slow and/or unable to make hardlinks)
.PHONY: _install install install_for_opam
_install: compiler
	rm -rf _install
	mkdir -p _install/{bin,lib/ocaml}
	$(cpl) _build/runtime_stdlib_install/bin/* _install/bin/
	$(cpl) _build/install/main/bin/* _install/bin/
	( cd _install/bin; for i in *.opt; do ln -s $$i $${i%.opt}; done )
	$(cpl) -R _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/* _install/lib/ocaml/
	rm -f _install/lib/ocaml/{META,dune-package,Makefile.config,dynlink.cmxa,dynlink/dynlink.cmxa}
	$(cpl) -R _build/install/main/lib/ocaml/* _install/lib/ocaml/
	if [ "x$(legacy_layout)" == "xyes" ] ; \
	then \
          for libdir in unix str dynlink bigarray ; do \
	    mv _install/lib/ocaml/$${libdir}/* _install/lib/ocaml/ ; \
            rmdir _install/lib/ocaml/$${libdir} ; \
          done \
	fi
	rm -f _install/lib/ocaml/{META,dune-package}
	rm -f _install/lib/ocaml/compiler-libs/*.cmo
	$(cpl) {_build/install/main,_install}/lib/ocaml/compiler-libs/topstart.cmo
	for file in $(toplevels_installed); do \
	  cp -f _install/lib/ocaml/compiler-libs/$${file}dirs.{cmi,mli,cmt,cmti} _install/lib/ocaml; \
	done
	mkdir _install/lib/stublibs
	cp _build/main/parser.cmly _install/lib/ocaml/compiler-libs/
	find _build/main/ \( -name "flambda2*.cmi" \
          -or -name "flambda2*.cmsi" -or -name "flambda2*.cms" \
          -or -name "flambda2*.cmti" -or -name "flambda2*.cmt" \) \
          -exec cp -f {} _install/lib/ocaml/compiler-libs \;


# Copy _install to the final install directory (no-op if they are the same)
install: _install
	mkdir -p '$(prefix)'
	rsync --chmod=u+rw,go+r -rl _install/ '$(prefix)'

# Same as above, but relies on a successfull earlier _install
install_for_opam:
	mkdir -p '$(prefix)'
	rsync --chmod=u+rw,go+r -rl _install/ '$(prefix)'

main_prefix = _build/install/main
main_build = _build/main
boot_build = _build/default

# The following horror will be removed when work to allow the testsuite to
# run on an installed tree (led by David Allsopp) is completed.
.PHONY: runtest-upstream test install_for_test
install_for_test: install
	rm -rf _runtest
	mkdir _runtest
	ln -s ../_install _runtest/_install
	# Use rsync to ensure hardlinks are created on both Linux and macOS
	rsync --link-dest=../../$(ocamldir)/testsuite/ -a $(ocamldir)/testsuite/ _runtest/testsuite/
	 # replace backend-specific testsuite/tools with their new versions
	rm -f _runtest/testsuite/tools/*
	cp -a oxcaml/testsuite/tools/* _runtest/testsuite/tools/
	cp $(main_build)/oxcaml/testsuite/tools/expect.exe _runtest/testsuite/tools/expect
	chmod 755 _runtest/testsuite/tools/expect
	cp $(main_build)/middle_end/flambda2/tests/tools/fexprc.exe _runtest/testsuite/tools/fexprc
	chmod 755 _runtest/testsuite/tools/fexprc
	cp $(main_build)/oxcaml/testsuite/tools/expectnat.exe _runtest/testsuite/tools/expectnat
	chmod 755 _runtest/testsuite/tools/expectnat
	cp $(main_build)/oxcaml/testsuite/tools/codegen_main.exe \
          _runtest/testsuite/tools/codegen
	chmod 755 _runtest/testsuite/tools/codegen
	cp $(main_build)/oxcaml/testsuite/tools/asmgen_*.o \
          _runtest/testsuite/tools/
	cp $(main_build)/testsuite/lib/lib.{a,cmxa,cma} \
          _runtest/testsuite/lib/
	cp $(main_build)/testsuite/lib/.lib.objs/byte/lib.cm* \
          _runtest/testsuite/lib/
	cp $(main_build)/testsuite/lib/.lib.objs/native/lib.cm* \
          _runtest/testsuite/lib/
	cp $(main_build)/testsuite/lib/testing.{a,cmxa,cma} \
          _runtest/testsuite/lib/
	cp $(main_build)/testsuite/lib/.testing.objs/byte/testing.cm* \
          _runtest/testsuite/lib/
	cp $(main_build)/testsuite/lib/.testing.objs/native/testing.cm* \
          _runtest/testsuite/lib/
	 # replace backend-specific testsuite/tests/asmcomp with their new versions
	rm _runtest/testsuite/tests/asmcomp/*
	cp -a oxcaml/testsuite/tests/asmcomp/* _runtest/testsuite/tests/asmcomp/
	 # replace backend-specific testsuite/tests/asmgen with their new versions
	rm _runtest/testsuite/tests/asmgen/*
	cp -a oxcaml/testsuite/tests/asmgen/* _runtest/testsuite/tests/asmgen/
	 # add extension library tests that are not supported by the upstream compiler
	rm _runtest/testsuite/tests/lib-extensions/*
	cp -a oxcaml/testsuite/tests/lib-extensions/* _runtest/testsuite/tests/lib-extensions

	cp $(ocamldir)/Makefile.* _runtest/

#	Create an OCaml directory laid out like the testsuite expects,
#	by copying and symlinking in bits from the install/build directory
	(cd _runtest; \
	 for exe in _install/bin/*; do ln -s $$exe; done; \
         ln -s . boot; \
	 for exe in ocamlc ocamlopt ocamllex; do \
	   rm -f $$exe; ln -s $$exe.byte $$exe; \
         touch ocamlc.opt ocamlopt.opt; \
	 done; \
	 ln -s _install/lib/ocaml stdlib; \
	 mkdir runtime; \
	 for f in ocamlrun* stdlib/caml stdlib/stublibs/* runtime/caml/threads.h; do \
	   ln -s ../$$f runtime/`basename $$f`; \
	 done; \
	 ln -s . lex; ln -s . yacc; \
	 ln -s _install/lib/ocaml/compiler-libs compilerlibs; \
	 mkdir -p otherlibs/{unix,dynlink/native,str,bigarray,runtime_events,eval}; \
	 ln -s ../stdlib/threads otherlibs/systhreads; \
         $(cpl) stdlib/unix/{lib,}unix* otherlibs/unix; \
         $(cpl) stdlib/dynlink/dynlink* otherlibs/dynlink; \
         $(cpl) stdlib/str/{lib,}str* otherlibs/str; \
         $(cpl) stdlib/{lib,}eval* otherlibs/eval; \
	 for universe in upstream_compatible stable beta alpha ; do \
		mkdir -p otherlibs/{stdlib_,}$${universe}; \
		$(cpl) stdlib/stdlib_$${universe}/* otherlibs/stdlib_$${universe}; \
	 done; \
	 $(cpl) stdlib/runtime_events/{lib,}runtime_events* otherlibs/runtime_events; \
	 ln -s ../_build/main/$(ocamldir)/toplevel/byte/.ocamltoplevel.objs/byte toplevel; \
	)

	# Various directories are put on the -I paths by tools/Makefile;
	# utils/ is one such, so we just dump the .cm* files in there for
	# various things.
	mkdir _runtest/utils
	cp _install/lib/ocaml/compiler-libs/*.{cmi,cmx} _runtest/utils
	cp $(main_build)/$(ocamldir)/.ocamlfrontend.objs/byte/*.cmo _runtest/utils
	cp $(main_build)/$(ocamldir)/.ocamlcommon.objs/byte/*.cmo _runtest/utils
	rm -f _runtest/utils/{topdirs,opttopdirs}.cmi
	cp _install/lib/ocaml/*.{cmi,cma,a,cmxa} _runtest/utils
	cp _install/lib/ocaml/{unix,str,dynlink}/*.{cmi,cma,a,cmxa} _runtest/utils
	cp $(main_build)/$(ocamldir)/.ocamlcommon.objs/native/config.o _runtest/utils
	# Needed for tests/warnings
	cp $(ocamldir)/utils/warnings.ml _runtest/utils
	# Suppress linker errors about -I directories not existing.
	for dir in asmcomp bytecomp driver file_formats lambda middle_end \
	  parsing typing; do ln -s utils _runtest/$$dir; done
	# stublibs
	mkdir -p _runtest/lib/ocaml/stublibs/
	cp $(main_prefix)/lib/ocaml/stublibs/*.so _runtest/lib/ocaml/stublibs
	# ocamldebug
	mkdir _runtest/debugger
	ln -s ../ocamldebug _runtest/debugger
	cp $(main_build)/$(ocamldir)/debugger/.ocamldebug.objs/byte/*.cm* \
	  _runtest/debugger
	# The ast_invariants test needs VERSION to be present.  In fact ideally
	# we should have all the source files in _runtest too for this test,
	# but for the moment we accept it being a weaker check.  We're not
	# working on parts of the compiler that deal with the AST anyway in
	# this repo.
	touch _runtest/VERSION
	# tools
	mkdir _runtest/tools
	ln -s ../_install/bin/ocamlmklib.byte _runtest/tools/ocamlmklib
	ln -s ../_install/bin/ocamlobjinfo.byte _runtest/tools/ocamlobjinfo
	ln -s ../_install/bin/dumpobj.byte _runtest/tools/dumpobj
	ln -s ../_install/bin/ocamlfilt _runtest/tools/ocamlfilt
        # ocamldoc
	# rm _runtest/ocamldoc
	# mkdir _runtest/ocamldoc
	# ln -s ../../_install/bin/ocamldoc.byte _runtest/ocamldoc/ocamldoc
	# cp $(main_build)/$(ocamldir)/ocamldoc/.odoc_lib.objs/byte/*.cm* _runtest/ocamldoc
	# ocamltest itself
	mkdir _runtest/ocamltest
	cp $(boot_build)/ocamltest/ocamltest.native _runtest/ocamltest/ocamltest
test: install_for_test
	$(MAKE) test-no-rebuild

.PHONY: test-no-rebuild
test-no-rebuild:
	if [ "$(middle_end)" = "flambda2" ]; then \
	  for path in `cd testsuite; ls -1 -d tests/*`; do \
	    if [[ -d "testsuite/$$path" ]] && ! grep -q "^  $$path " oxcaml/testsuite/flambda2-test-list; then \
	      echo "  $$path"; \
	    fi; \
	  done > _runtest/flambda2-test-list; \
	fi
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite \
	  && if $$(which parallel > /dev/null 2>&1); \
             then \
	       echo "Running testsuite in parallel (nproc=$$(nproc))"; \
               if [ "$(middle_end)" = "flambda2" ]; then \
                 make --no-print-directory list-parallel FILE=$$(pwd)/../flambda2-test-list; \
	       else \
                 make --no-print-directory parallel; \
               fi \
             else \
	       echo "Running testsuite sequentially"; \
               if [ "$(middle_end)" = "flambda2" ]; then \
                 make --no-print-directory list FILE=$$(pwd)/../flambda2-test-list; \
	       else \
                 make --no-print-directory all; \
               fi \
             fi)

.PHONY: test-files-parallel
test-files-parallel:
	if [ "$(middle_end)" = "flambda2" ]; then \
	  for path in `cd testsuite; ls -1 -d tests/*`; do \
	    if [[ -d "testsuite/$$path" ]] && ! grep -q "^  $$path " oxcaml/testsuite/flambda2-test-list; then \
	      echo "  $$path"; \
	    fi; \
	  done > _runtest/flambda2-test-list; \
	fi
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite; \
	 if [ "$(middle_end)" = "flambda2" ]; then \
	   $(MAKE) --no-print-directory files-parallel \
	     FILE=$$(pwd)/../flambda2-test-list; \
	 else \
	   $(MAKE) --no-print-directory files-parallel DIR=tests; \
	 fi)

promote-failed:
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite && make promote-failed)

runtest-upstream: test

test-one: install_for_test
	$(MAKE) test-one-no-rebuild

# If the TEST argument is passed as `testsuite/tests/foo` (as is invited by
# tab completion) then look for it in `tests/foo`. Otherwise, if it's passed as
# just `foo`, then look for it in `tests/foo` for backward compatibility.
locate_test = \
  $(shell \
    test=$(shell echo "$1" | sed 's|^testsuite/tests/||g'); \
    echo "tests/$${test}"; \
  )

test-one-no-rebuild:
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite && make one $(if $(TEST),TEST=$(call locate_test,$(TEST))) $(if $(DIR),DIR=$(call locate_test,$(DIR))))

promote-one: install_for_test
	$(MAKE) promote-one-no-rebuild

promote-one-no-rebuild:
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite && make promote $(if $(TEST),TEST=$(call locate_test,$(TEST))) $(if $(DIR),DIR=$(call locate_test,$(DIR))))

# This target is like a polling version of upstream "make ocamlopt"
.PHONY: hacking
hacking: _build/_bootinstall
	$(dune) build $(ws_boot) -w @merlin-support $(boot_targets)

# The development watcher starts eagerly, but is managed as a worktree-local
# background process. All public dev commands renew its idle lease and wait
# for the latest compiler build before using its outputs.
DEV_IDLE_TIMEOUT ?= 1800
# How long to wait for a single watcher build before deciding it is wedged.
# Generous: a cold world-rebuild of the compiler is legitimately many minutes.
DEV_RPC_TIMEOUT ?= 1800
# How often to report that a build is still running.
DEV_HEARTBEAT ?= 30
# Set NOWATCH=1 to bypass the watcher entirely. Slower, but works where dune's
# RPC socket cannot be created at all, such as a restricted sandbox.
NOWATCH ?=
ARGS ?=
dev_watcher = python3 tools/dev-watcher.py
dev_build = _build/dev-dune
dev_build_flag = --build-dir=$(CURDIR)/$(dev_build)
dev_boot_targets = $(boot_targets) main.bc
dev_stdlib = _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib
dev_compiler = $(dev_build)/default/main_native.exe
dev_watch_command = $(dune) build $(ws_boot) $(dev_build_flag) -w \
  --display=short @merlin-support $(dev_boot_targets)
# The same build, without the watcher: the NOWATCH path and the recovery path
# taken when the watcher cannot be used.
dev_direct_command = $(dune) build $(ws_boot) $(dev_build_flag) \
  --display=short @merlin-support $(dev_boot_targets)

.PHONY: dev dev-start dev-setup dev-runtime dev-check
.PHONY: dev-test dev-test-all dev-promote
.PHONY: dev-ocamlc dev-ocamlopt
.PHONY: dev-expect-runners
.PHONY: dev-status dev-log dev-stop dev-errors dev-diff
.PHONY: dev-stdlib-check dev-refresh-stdlib dev-configure

dev-start: _build/_bootinstall
	@if [ -n "$(NOWATCH)" ]; then exit 0; fi; \
	 $(dev_watcher) start --idle-timeout $(DEV_IDLE_TIMEOUT) -- \
	   $(dev_watch_command)

# configure is not tracked in git and configure.ac needs autoconf >= 2.71, which
# is newer than the autoconf on many systems, so a fresh worktree reliably fails
# here. Without this check the failure surfaces from the Makefile.config
# prerequisite of _build/_bootinstall, which says nothing about autoconf.
dev-configure:
	@set -eu; \
	  for candidate in autoconf27 autoconf-2.71 autoconf2.71 autoconf; do \
	    if command -v $$candidate >/dev/null 2>&1 && \
	       $$candidate --version 2>/dev/null | head -n 1 | \
	         awk '{ split($$NF, v, "."); \
	                exit !(v[1] > 2 || (v[1] == 2 && v[2] >= 71)) }'; then \
	      found=$$candidate; \
	      break; \
	    fi; \
	  done; \
	  if [ -z "$${found:-}" ]; then \
	    echo "dev: no autoconf >= 2.71 on PATH, which configure.ac requires." >&2; \
	    echo "dev: on these boxes the one to use is usually autoconf27." >&2; \
	    exit 2; \
	  fi; \
	  echo "dev: generating configure with $$found"; \
	  $$found; \
	  ./configure --prefix="$$(pwd)/_install"

dev-setup:
	+@set -eu; \
	  if [ ! -f Makefile.config ]; then \
	    echo "dev: Makefile.config is missing, so this worktree is not" >&2; \
	    echo "dev: configured. Run \`make dev-configure\` (which finds a" >&2; \
	    echo "dev: suitable autoconf and configures with --prefix=_install)." >&2; \
	    exit 2; \
	  fi; \
	  if [ ! -x _install/bin/ocamlopt.opt ] || \
	     [ ! -f _runtest/testsuite/Makefile ]; then \
	    echo "dev: preparing the initial compiler and test installation"; \
	    $(dev_watcher) stop; \
	    $(MAKE) --no-print-directory install_for_test; \
	  fi

dev-runtime:
	+@set -eu; \
	  artifact=_build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/stdlib.cma; \
	  if [ ! -f $$artifact ] || \
	     [ Makefile.config -nt $$artifact ] || \
	     [ duneconf/runtime_stdlib.ws -nt $$artifact ] || \
	     find runtime stdlib otherlibs \
	       \( -type d \( -name test -o -name tests \) -prune \) -o \
	       \( -type f -newer $$artifact -print -quit \) | grep -q .; then \
	    echo "dev: refreshing the runtime and standard library"; \
	    $(dev_watcher) stop; \
	    $(MAKE) runtime-stdlib; \
	  fi

dev-check: dev-setup dev-runtime dev-start
	@set -eu; \
	  if [ -n "$(NOWATCH)" ]; then \
	    echo "dev: building directly (NOWATCH is set; no watcher, no rpc)"; \
	    $(dev_direct_command); \
	  else \
	    $(dev_watcher) build \
	      --timeout $(DEV_RPC_TIMEOUT) \
	      --heartbeat $(DEV_HEARTBEAT) \
	      --ping "$(dune) rpc ping --root=. $(dev_build_flag)" \
	      --fallback "$(dev_direct_command)" \
	      --diagnostics "$(dune) diagnostics --root=. $(dev_build_flag)" \
	      -- $(dune) rpc build $(ws_boot) $(dev_build_flag) \
	           $(dev_boot_targets); \
	  fi
	@$(MAKE) --no-print-directory dev-stdlib-check

# A compiler change can alter the shape of marshaled .cmi files without a magic
# number bump, which leaves the previously built stdlib unreadable by the
# compiler that must read it. Nothing in the loop notices, because no stdlib
# *source* changed: the reader changed. The observed failure is a SIGSEGV in the
# built compiler, which points nowhere. Predicting this from compiler-source
# mtimes would rebuild the stdlib on nearly every edit, so detect it instead --
# compiling one line against the installed stdlib is enough to provoke it.
dev-stdlib-check:
	@set -eu; \
	  if [ ! -x $(dev_compiler) ] || \
	     [ ! -f $(dev_stdlib)/stdlib.cmi ]; then exit 0; fi; \
	  scratch=_build/dev/stdlib-check; \
	  rm -rf $$scratch; mkdir -p $$scratch; \
	  echo 'let () = Printf.printf "%d" (List.length [Sys.opaque_identity 0])' \
	    > $$scratch/probe.ml; \
	  status=0; \
	  ( ulimit -c 0; \
	    OCAMLLIB="$$(pwd)/$(dev_stdlib)" TMPDIR="$$(pwd)/$$scratch" \
	      $(dev_compiler) -c -o $$scratch/probe.cmo $$scratch/probe.ml \
	      >$$scratch/probe.log 2>&1 \
	  ) 2>/dev/null || status=$$?; \
	  if [ $$status = 0 ]; then rm -rf $$scratch; exit 0; fi; \
	  echo "dev: the compiler cannot read the installed standard library," >&2; \
	  echo "dev: so a compiler change may have altered .cmi shapes." >&2; \
	  if [ $$status -gt 128 ]; then \
	    echo "dev: (it died on signal $$(($$status - 128)), which is what a" >&2; \
	    echo "dev: stale marshaled .cmi looks like)" >&2; \
	  fi; \
	  echo "dev: run \`make dev-refresh-stdlib\` to rebuild it." >&2; \
	  sed 's/^/dev: /' $$scratch/probe.log >&2; \
	  exit 1

dev-refresh-stdlib:
	+@$(dev_watcher) stop; \
	  $(MAKE) --no-print-directory runtime-stdlib

# Check the watcher's own recovery logic against a stub dune. Needs no compiler,
# so it runs in seconds and does not touch this worktree's watcher.
dev-selftest:
	@sh tools/dev-watcher-test.sh

# Fresh diagnostics straight from the running watcher, without a build round
# trip. This is the tightest error loop the watcher supports.
dev-errors:
	@$(dune) diagnostics --root=. $(dev_build_flag) 2>&1 \
	  | $(dev_watcher) filter-notices

dev: dev-check

DEV_RUNNERS ?=
dev-expect-runners:
	@test -n "$(DEV_RUNNERS)" || \
	  { echo "dev: no expect-test runner selected" >&2; exit 2; }
	@$(dev_watcher) stop
	$(dune) build $(ws_main) \
	  $(addprefix oxcaml/testsuite/tools/,$(addsuffix .exe,$(DEV_RUNNERS)))
	@$(MAKE) --no-print-directory dev-start \
	  DEV_IDLE_TIMEOUT=$(DEV_IDLE_TIMEOUT)

dev-test: dev-check
	+@set -eu; \
	  if [ -z "$(TEST)$(DIR)" ]; then \
	    echo "Usage: make dev-test TEST=path/to/test.ml" >&2; \
	    echo "   or: make dev-test DIR=path/to/test-directory" >&2; \
	    exit 2; \
	  fi; \
	  selection="$(if $(TEST),$(call locate_test,$(TEST)),$(call locate_test,$(DIR)))"; \
	  selection="testsuite/$$selection"; \
	  stale_runners=""; \
	  for runner in expect expectnat; do \
	    case $$runner in \
	      expect) pattern='(^|[;[:space:]])expect([;[:space:]]|$$)' ;; \
	      expectnat) pattern='(^|[;[:space:]])expectnat([;[:space:]]|$$)' ;; \
	    esac; \
	    artifact=_build/main/oxcaml/testsuite/tools/$$runner.exe; \
	    if grep -ERq --include='*.ml' "$$pattern" "$$selection" && \
	       { [ ! -x $$artifact ] || \
	         [ $(dev_build)/default/main_native.exe -nt $$artifact ] || \
	         find oxcaml/testsuite/tools -type f -newer $$artifact \
	           -print -quit | grep -q .; }; then \
	      stale_runners="$$stale_runners $$runner"; \
	    fi; \
	  done; \
	  if [ -n "$$stale_runners" ]; then \
	    echo "dev: refreshing expect-test runner(s):$$stale_runners"; \
	    $(MAKE) --no-print-directory dev-expect-runners \
	      DEV_IDLE_TIMEOUT=$(DEV_IDLE_TIMEOUT) \
	      DEV_RUNNERS="$$stale_runners"; \
	  fi; \
	  $(dev_watcher) prepare-test-root; \
	  echo "dev: compiler = $(dev_build)/default/main_native.exe"; \
	  echo "dev: stdlib   = _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib"; \
	  export OCAMLSRCDIR=$$(pwd)/_build/dev/runtest; \
	  export CAML_LD_LIBRARY_PATH=$$(pwd)/_build/dev/runtest/stdlib/stublibs; \
	  export TMPDIR="$${TMPDIR:-$$(pwd)/_build/dev/tmp}"; \
	  mkdir -p "$$TMPDIR"; \
	  if $$(which gfortran > /dev/null 2>&1); then \
	    export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	  fi; \
	  cd _build/dev/runtest/testsuite; \
	  $(MAKE) $(if $(PROMOTE),promote,$(if $(DIR),files-parallel,one)) \
	    $(if $(TEST),TEST=$(call locate_test,$(TEST))) \
	    $(if $(DIR),DIR=$(call locate_test,$(DIR)))

dev-test-all: dev-check
	+@set -eu; \
	  if ! parallel --version 2>/dev/null | grep -q 'GNU parallel'; then \
	    echo "dev: GNU Parallel is required for dev-test-all" >&2; \
	    exit 2; \
	  fi; \
	  $(dev_watcher) stop; \
	  restart_watcher() { \
	    $(MAKE) --no-print-directory dev-start \
	      DEV_IDLE_TIMEOUT=$(DEV_IDLE_TIMEOUT) >/dev/null || true; \
	  }; \
	  trap restart_watcher EXIT; \
	  echo "dev: building the final compiler for the full test suite"; \
	  $(MAKE) --no-print-directory \
	    -o boot-compiler -o runtime-stdlib install_for_test; \
	  status=0; \
	  $(MAKE) --no-print-directory test-files-parallel || status=$$?; \
	  echo "dev: corrected outputs are under _runtest/testsuite/_ocamltest/,"; \
	  echo "dev: not the _build/dev root the rest of the loop uses."; \
	  echo "dev: \`make dev-diff TEST=...\` searches both."; \
	  exit $$status

# A promoting run fails the action it promoted, which aborts the test, so a test
# with several reference files converges only after several passes. Bounded,
# because output that is genuinely unstable between the plain and -principal runs
# never converges and should be reported rather than looped on.
DEV_PROMOTE_PASSES ?= 3

dev-promote:
	+@set -eu; \
	  scratch=_build/dev/promote; \
	  mkdir -p $$scratch; \
	  promote_log=$$scratch/promote.log; \
	  pass=1; \
	  while [ $$pass -le $(DEV_PROMOTE_PASSES) ]; do \
	    if $(MAKE) --no-print-directory dev-test PROMOTE=1 \
	        DEV_IDLE_TIMEOUT=$(DEV_IDLE_TIMEOUT) \
	        $(if $(TEST),TEST=$(TEST)) $(if $(DIR),DIR=$(DIR)) \
	        >"$$promote_log" 2>&1; then \
	      cat "$$promote_log"; \
	      exit 0; \
	    fi; \
	    cat "$$promote_log"; \
	    if $(MAKE) --no-print-directory dev-test \
	        DEV_IDLE_TIMEOUT=$(DEV_IDLE_TIMEOUT) \
	        $(if $(TEST),TEST=$(TEST)) $(if $(DIR),DIR=$(DIR)); then \
	      echo "dev: promoted test output (converged after $$pass pass(es))"; \
	      exit 0; \
	    fi; \
	    pass=$$((pass + 1)); \
	  done; \
	  echo "dev: promotion did not converge in $(DEV_PROMOTE_PASSES) passes." >&2; \
	  echo "dev: the usual cause is output that differs between the plain and" >&2; \
	  echo "dev: -principal runs, which promotion cannot settle: the test needs a" >&2; \
	  echo "dev: Principal{| ... |} block written by hand." >&2; \
	  echo "dev: run \`make dev-diff TEST=...\` to see the difference." >&2; \
	  exit 1

# Show the newest corrected output for a test against its source. Corrected
# artifacts land in three different places depending on how the test was run, and
# the -principal pass writes .corrected.corrected, which supersedes .corrected --
# promoting the latter by hand silently drops the principal updates.
dev-diff:
	@set -eu; \
	  if [ -z "$(TEST)" ]; then \
	    echo "Usage: make dev-diff TEST=path/to/test.ml" >&2; \
	    exit 2; \
	  fi; \
	  source="testsuite/$(call locate_test,$(TEST))"; \
	  name=$$(basename "$$source"); \
	  roots=""; \
	  for root in _build/dev/runtest/testsuite _runtest/testsuite testsuite; do \
	    if [ -d $$root ]; then roots="$$roots $$root"; fi; \
	  done; \
	  candidates=$$(find $$roots -name "$$name.corrected.corrected" 2>/dev/null); \
	  if [ -z "$$candidates" ]; then \
	    candidates=$$(find $$roots -name "$$name.corrected" 2>/dev/null); \
	  fi; \
	  if [ -z "$$candidates" ]; then \
	    echo "dev: no corrected output for $$source." >&2; \
	    echo "dev: run \`make dev-test TEST=$(TEST)\` first; note that" >&2; \
	    echo "dev: prepare-test-root discards the previous run's artifacts." >&2; \
	    exit 1; \
	  fi; \
	  newest=$$(ls -t $$candidates | head -1); \
	  echo "dev: corrected output $$newest"; \
	  echo "dev: promote it with \`make dev-promote TEST=$(TEST)\`, not by copying."; \
	  diff -u "$$source" "$$newest" || true

dev-ocamlc: dev-check
	@echo "dev: compiler = $(dev_build)/default/main_native.exe"
	@echo "dev: stdlib   = _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib"
	@OCAMLLIB="$$(pwd)/_build/runtime_stdlib_install/lib/ocaml_runtime_stdlib" \
	  $(dev_build)/default/main_native.exe $(ARGS)

dev-ocamlopt: dev-check
	@echo "dev: compiler = $(dev_build)/default/boot_ocamlopt.exe"
	@echo "dev: stdlib   = _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib"
	@OCAMLLIB="$$(pwd)/_build/runtime_stdlib_install/lib/ocaml_runtime_stdlib" \
	  $(dev_build)/default/boot_ocamlopt.exe $(ARGS)

dev-status:
	@$(dev_watcher) status

dev-log:
	@if [ -f _build/dev/watcher.log ]; then \
	  tail -n 100 _build/dev/watcher.log; \
	else \
	  echo "dev: no watcher log"; \
	fi

dev-stop:
	@$(dev_watcher) stop

# The `hacking-emacs-poller` and `hacking-emacs-builder` targets make it
# possible to run the polling build with Emacs's `M-x compile`.  You should run
# `make hacking-emacs-poller` in your terminal from the root directory of the
# repo, and set Emacs's `compile-command` to `make hacking-emacs-builder` (from
# the appropriate directory).

.PHONY: hacking-emacs-poller
hacking-emacs-poller: _build/_bootinstall
	$(dune) build $(ws_boot) --passive-watch-mode

.PHONY: hacking-emacs-builder
hacking-emacs-builder: _build/_bootinstall
	$(dune) rpc build $(ws_boot) -w @merlin-support $(boot_targets)
	$(dune) diagnostics

.PHONY: debug-printers
debug-printers: runtime-stdlib # required for $(ws_main) to work
	 $(dune) build $(ws_main) $(ocamldir)/tools/debug_printers
	@echo
	@echo To load into ocamldebug, use:
	@echo source \"$$(realpath _build/main/$(ocamldir)/tools/debug_printers)\"

# boot-_install installs the bootstrapped compiler into _install. It is mostly
# just copied from the install phrase.
# This allows tools/compare.sh to function as expected, which is useful because
# it allows us to easily run the bootstrapped compiler, especially with
# tools/compare.sh
.PHONY: boot-_install
boot-_install: runtime-stdlib
	rm -rf _install
	mkdir -p _install/{bin,lib/ocaml}
	$(cpl) _build/runtime_stdlib_install/bin/* _install/bin/
	# can't use a hard link here because ocamllex comes from the system and
	# is possibly on a different device
	ln -sf $(realpath _build/_bootinstall/bin/ocamllex.opt) _install/bin/ocamllex.opt
	$(cpl) _build/_bootinstall/bin/ocaml{c,opt,mklib,dep,objinfo}.opt _install/bin/
	( cd _install/bin; for i in *.opt; do ln -s $$i $${i%.opt}; done )
	$(cpl) -R _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/* \
    _install/lib/ocaml/
	rm -f _install/lib/ocaml/{META,dune-package,Makefile.config,dynlink.cmxa,dynlink/dynlink.cmxa}
	$(cpl) -R _build/_bootinstall/lib/ocaml/* _install/lib/ocaml/
	rm -f _install/lib/ocaml/{META,dune-package}
	rm -f _install/lib/ocaml/compiler-libs/*.cmo
	mkdir _install/lib/stublibs
	find _build/default -name "dll*.so" \
       -print0 | xargs -0 -I '{}' cp -f '{}' _install/lib/stublibs
	mkdir -p _install/lib/ocaml/compiler-libs
	cp _build/default/parser.cmly _install/lib/ocaml/compiler-libs/
	find _build/default/ \( -name "flambda2*.cmi" \
          -or -name "flambda2*.cmti" -or -name "flambda2*.cmt" \) \
          -print0 | xargs -0 -I '{}' cp -f '{}' _install/lib/ocaml/compiler-libs
