#
# Build rules common to ocaml-ox and oxcaml
#

ws_boot   = --root=. --workspace=duneconf/boot.ws
ws_runstd = --root=. --workspace=duneconf/runtime_stdlib.ws
ws_main   = --root=. --workspace=duneconf/main.ws

ifeq ($(coverage),yes)
  coverage_dune_flags=--instrument-with bisect_ppx
  ocaml_subdirs_to_ignore=otherlibs
else
  coverage_dune_flags=
  ocaml_subdirs_to_ignore=
endif

define dune_boot_context
(lang dune 2.8)
; We need to call the boot context "default" so that dune selects it for merlin
(context (default
  (name default)
  (profile dev)
  (env (_
    (flags (:standard -warn-error +A -alert -unsafe_multidomain -alert -unsafe_effects))
    (env-vars
      ("OCAMLPARAM" "")

      ; Avoid using the full OC_CFLAGS for C code compiled during the boot
      ; In particular, we should avoid using ASan here even if it is otherwise
      ; enabled, since (a) it is of little benefit, because it has no effect
      ; on the final compiler, and (b) it breaks, because linking is missing
      ; the matching -fsanitize=address flag
      ("OC_CFLAGS_SEXP" "boot_oc_cflags.sexp"))))))
endef

ifneq ($(origin BUILD_OCAMLPARAM), undefined)
ENV_VARS := (env-vars ("OCAMLPARAM" "$(BUILD_OCAMLPARAM)"))
else
ENV_VARS :=
endif

ifeq ($(main_build_profile),dev)
main_ocamlopt_optimization_flags :=
else
main_ocamlopt_optimization_flags := -O3
endif

define dune_runtime_stdlib_context
(lang dune 3.23)
(using oxcaml 0.1)
(context (default
  (name runtime_stdlib)
  (profile main)
  (cms_cmt_dependency cms)
  (paths
    (PATH ("$(CURDIR)/_build/_bootinstall/bin" :standard))
    (OCAMLLIB ("$(CURDIR)/_build/_bootinstall/lib/ocaml")))
  (env (_
    (bin_annot_cms true)
    (flags (:standard -directory stdlib -warn-error +A -alert -unsafe_multidomain -alert -unsafe_effects))
    $(ENV_VARS)))))
endef

define dune_main_context
(lang dune 3.23)
(using oxcaml 0.1)
(context (default
  (name main)
  (profile $(main_build_profile))
  (cms_cmt_dependency cms)
  (paths
    (PATH ("$(CURDIR)/_build/_bootinstall/bin" :standard))
    (OCAMLLIB ("$(CURDIR)/_build/runtime_stdlib_install/lib/ocaml_runtime_stdlib")))
  (env (_
    (bin_annot_cms true)
    (flags (:standard -directory compiler-distro -warn-error +A -alert -unsafe_multidomain -alert -unsafe_effects))
    ; We never want to build the compiler itself with AddressSanitizer enabled.
    (ocamlopt_flags (:standard $(main_ocamlopt_optimization_flags) -fno-asan))
    $(ENV_VARS)))))
endef


.DEFAULT_GOAL := compiler
.PHONY: boot-compiler boot-runtest runtime-stdlib compiler runtest runtest-llvmize runtest-dwarf

boot_targets = \
  $(boot_ocamlc) \
  $(boot_ocamlopt) \
  $(boot_ocamlj) \
  $(boot_ocamlmklib) \
  $(boot_ocamldep) \
  $(boot_ocamlobjinfo) \
  ocamltest/ocamltest.native

boot-compiler: _build/_bootinstall
	$(dune) build $(ws_boot) $(coverage_dune_flags) @merlin-support $(boot_targets)

boot-runtest: boot-compiler
	$(dune) build $(ws_boot) $(coverage_dune_flags) --force $(runtest_targets)

runtime-stdlib: boot-compiler
	$(dune) build $(ws_runstd) --only-package=ocaml_runtime_stdlib @install
	rm -rf _build/runtime_stdlib_install
# Dune 3.11+ clears `_build/install` before building, move the runtime stdlib
# to a separate directory.
	$(cpl) -R _build/install/runtime_stdlib _build/runtime_stdlib_install
# Dune does not believe the compiler can make .cmxs unless the following file exists.
	@touch _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/dynlink.cmxa
# Dune will look here if the system compiler is OCaml 5 instead.
	@mkdir -p _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/dynlink/
	@touch _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/dynlink/dynlink.cmxa

# This target is a polling version of "make runtime-stdlib"
.PHONY: runtime-stdlib-hacking
runtime-stdlib-hacking: boot-compiler
	$(dune) build -w $(ws_runstd) --only-package=ocaml_runtime_stdlib @install

compiler: runtime-stdlib
	SYSTEM=$(SYSTEM) MODEL=$(MODEL) \
          ASPP="$(ASPP)" ASPPFLAGS="$(ASPPFLAGS)" \
          $(dune) build $(ws_main) \
          --only-package=ocaml @install \
          tools/regalloc/regalloc.exe \
          oxcaml/testsuite/tools/expect.exe \
          oxcaml/testsuite/tools/expectnat.exe \
          oxcaml/testsuite/tools/codegen_main.exe \
          oxcaml/testsuite/tools/asmgen_$(ARCH).o \
          testsuite/lib/lib.cm{,x}a \
          testsuite/lib/testing.cm{,x}a \
          @middle_end/flambda2/tests/tools/all \
          $(ocamldir)/tools/dumpobj.bc

.PHONY: minimize-failure
minimize-failure: boot-minimizer boot-compiler runtime-stdlib
	SYSTEM=$(SYSTEM) MODEL=$(MODEL) \
          ASPP="$(ASPP)" ASPPFLAGS="$(ASPPFLAGS)" \
          ./_build/default/chamelon/chamelon.exe dune build \
          $(ws_main) \
          --only-packages=ocaml @install \
          tools/regalloc/regalloc.exe \
          oxcaml/testsuite/tools/expect.exe \
          oxcaml/testsuite/tools/expectnat.exe \
          oxcaml/testsuite/tools/codegen_main.exe \
          oxcaml/testsuite/tools/asmgen_$(ARCH).o \
          testsuite/lib/lib.cm{,x}a \
          testsuite/lib/testing.cm{,x}a \
          $(ocamldir)/tools/dumpobj.bc

.PHONY: minimize-stdlib
minimize-stdlib: boot-minimizer boot-compiler
	./_build/default/chamelon/chamelon.exe dune build \
          $(ws_runstd) \
          --only-packages=ocaml_runtime_stdlib @install

# We want to be able to build the @runtest dune alias, but exclude
# external/merlin from that (since Merlin only builds in the boot workspace).
# Dune doesn't offer a native way to do this, so instead we list all directories
# and build @runtest in each directory, excluding external/merlin and any
# directories not in the dune workspace. (We can exclude external/ as a whole
# since all the non-merlin directories in that folder are vendored anyways.)
runtest_targets := $(sort $(addprefix @, $(addsuffix runtest, $(filter-out autom4te.cache/ build-aux/ external/ _%, $(dir $(wildcard */.))))))

# CR dkalinichenko: [runtest] is built using the main profile,
# which uses the boot compiler. Use the final compiler for [runtest].
# ([runtest-upstream-boot] below runs the upstream testsuite with the
# boot compiler, for testing when the final compiler itself is
# miscompiled.)
runtest: compiler
	OXCAML_NAME_MANGLING=$(NAME_MANGLING_SCHEME) OXCAML_POLL_INSERTION=$(POLL_INSERTION) $(dune) build $(ws_main) $(runtest_targets)

runtest-llvmize: compiler
	OXCAML_NAME_MANGLING=$(NAME_MANGLING_SCHEME) $(dune) build @runtest-llvmize $(ws_main)

runtest-dwarf: compiler
	OXCAML_NAME_MANGLING=$(NAME_MANGLING_SCHEME) $(dune) build @runtest-dwarf $(ws_main)

# This Makefile supports old versions that don't have $(file), so we're using
# environment var trickery to get a multiline string into a file
duneconf/boot.ws: export contents = $(dune_boot_context)
duneconf/runtime_stdlib.ws: export contents = $(dune_runtime_stdlib_context)
duneconf/main.ws: export contents = $(dune_main_context)
duneconf/%.ws:
	echo "$$contents" > $@

# We need to disable ocaml/otherlibs when compiling with coverage, because we
# need to compile against the user's opam instead. Unfortunately, Dune gives us
# no nicer way of declaring data_only_dirs differently in different workspaces,
# so we have to output a file to be included in ocaml/dune.
#
# Also, Dune only allows one (data_only_dirs) declaration per file, so here we
# have to account for the declaration that would already have been in
# ocaml/dune.
$(ocamldir)/duneconf/dirs-to-ignore.inc:
	echo "(data_only_dirs yacc $(ocaml_subdirs_to_ignore))" > $@

# Targets that should be prerequisites to any target that runs Dune
dune_config_targets = \
  duneconf/boot.ws \
  duneconf/runtime_stdlib.ws \
  duneconf/main.ws \
  $(ocamldir)/duneconf/dirs-to-ignore.inc \
  $(ocamldir)/duneconf/ox-extra.inc \
  dune-project

_build/_bootinstall: Makefile.config $(dune_config_targets)
	echo -n '$(NATDYNLINKOPTS)' > $(ocamldir)/natdynlinkops

# flags.sexp
# Do not include :standard as it is ignored
# See: https://github.com/ocaml/dune/issues/13225
	echo '($(if $(filter true,$(FUNCTION_SECTIONS)),-function-sections,))' > ocamlopt_upstream_flags.sexp
	echo '($(OXCAML_DWARF_FLAGS_FOR_COMPILER) $(ASSEMBLY_FLAG_FOR_COMPILER) $(if $(filter true,$(FUNCTION_SECTIONS)),-function-sections,))' > ocamlopt_oxcaml_flags.sexp
	echo '( )' > boot_oc_cflags.sexp
	echo '( $(OC_CFLAGS) )' > oc_cflags.sexp
	echo '( $(subst -I $(ROOTDIR)/,-I $(CURDIR)/,$(OC_CPPFLAGS)) )' > oc_cppflags.sexp
	echo '( $(SHAREDLIB_CFLAGS) )' > sharedlib_cflags.sexp

# _build/_bootinstall: a minimal install directory for the boot compiler,
# which is placed on PATH for subsequent builds
	rm -rf _build/_bootinstall
	mkdir -p _build/_bootinstall/{bin,lib/ocaml}
	cp $^ _build/_bootinstall/lib/ocaml
	ln -sf ../../default/$(boot_ocamlopt) _build/_bootinstall/bin/ocamlopt.opt
	ln -sf ../../default/$(boot_ocamlc) _build/_bootinstall/bin/ocamlc.opt
	ln -sf ../../default/$(boot_ocamlj) _build/_bootinstall/bin/ocamlj.opt
	ln -sf ../../default/$(boot_ocamlmklib) _build/_bootinstall/bin/ocamlmklib.opt
	ln -sf ../../default/$(boot_ocamldep) _build/_bootinstall/bin/ocamldep.opt
	ln -sf ../../default/$(boot_ocamlobjinfo) _build/_bootinstall/bin/ocamlobjinfo.opt
	ln -sf "`$(opam_exec) which ocamllex`" _build/_bootinstall/bin/ocamllex.opt
	for prog in ocamlopt ocamlj ocamlc ocamllex ocamldep ocamlmklib; do \
	  ln -sf "$$prog.opt" "_build/_bootinstall/bin/$$prog"; \
	done

# save a bit of disk space in build trees by using cp -l on Linux
# (not available on e.g. OS X)
cpl=$(if $(filter linux,$(SYSTEM)),cp -l,cp -L)

# Assemble the contents of the install directory in _install
# This is needed to run the upstream testsuite (see runtest-upstream below)
# We use a local directory rather than the final install path, since
# the final install path may be on a different filesystem (and hence be
# slow and/or unable to make hardlinks)
.PHONY: _install install install_for_opam
_install: compiler
	rm -rf _install
	mkdir -p _install/{bin,lib/ocaml}
	$(cpl) _build/runtime_stdlib_install/bin/* _install/bin/
	$(cpl) _build/install/main/bin/* _install/bin/
	( cd _install/bin; for i in *.opt; do ln -s $$i $${i%.opt}; done )
	$(cpl) -R _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/* _install/lib/ocaml/
	rm -f _install/lib/ocaml/{META,dune-package,Makefile.config,dynlink.cmxa,dynlink/dynlink.cmxa}
	$(cpl) -R _build/install/main/lib/ocaml/* _install/lib/ocaml/
	if [ "x$(legacy_layout)" == "xyes" ] ; \
	then \
          for libdir in unix str dynlink bigarray ; do \
	    mv _install/lib/ocaml/$${libdir}/* _install/lib/ocaml/ ; \
            rmdir _install/lib/ocaml/$${libdir} ; \
          done \
	fi
	rm -f _install/lib/ocaml/{META,dune-package}
	rm -f _install/lib/ocaml/compiler-libs/*.cmo
	$(cpl) {_build/install/main,_install}/lib/ocaml/compiler-libs/topstart.cmo
	for file in $(toplevels_installed); do \
	  cp -f _install/lib/ocaml/compiler-libs/$${file}dirs.{cmi,mli,cmt,cmti} _install/lib/ocaml; \
	done
	mkdir _install/lib/stublibs
	cp _build/main/parser.cmly _install/lib/ocaml/compiler-libs/
	find _build/main/ \( -name "flambda2*.cmi" \
          -or -name "flambda2*.cmsi" -or -name "flambda2*.cms" \
          -or -name "flambda2*.cmti" -or -name "flambda2*.cmt" \) \
          -exec cp -f {} _install/lib/ocaml/compiler-libs \;


# Copy _install to the final install directory (no-op if they are the same)
install: _install
	mkdir -p '$(prefix)'
	rsync --chmod=u+rw,go+r -rl _install/ '$(prefix)'

# Same as above, but relies on a successfull earlier _install
install_for_opam:
	mkdir -p '$(prefix)'
	rsync --chmod=u+rw,go+r -rl _install/ '$(prefix)'

main_prefix = _build/install/main
main_build = _build/main
boot_build = _build/default

# The following horror will be removed when work to allow the testsuite to
# run on an installed tree (led by David Allsopp) is completed.
#
# The canned recipe below sets up the _runtest directory used to run the
# upstream testsuite. It is shared between [install_for_test] (test the main
# compiler) and [install_for_test_boot] (test the boot compiler), and is
# parameterized by the following target-specific variables:
# - [test_build]: build directory providing the testsuite tools and
#   libraries;
# - [test_stublibs]: directory providing the dynamically-loaded stubs;
# - [test_tools_build]: build directory providing the asmgen objects and
#   fexprc (differs from [test_build] in the boot flow, where they are
#   built in the boot context);
# - [test_codegen]: path of the codegen tool (built in a different
#   directory in the boot flow, see oxcaml/testsuite/tools/boot/dune);
# - [boot_flow]: non-empty when testing the boot compiler, in which case
#   the pieces that would require building the native compiler-libs with
#   the boot compiler (expectnat, ocamlnat) or the otherlibs are not
#   available: the tests that need them fail, and whole directories of
#   them are excluded via oxcaml/testsuite/boot-test-list.
.PHONY: runtest-upstream test install_for_test
.PHONY: runtest-upstream-boot test-boot install_for_test_boot
define prepare_runtest_dir
	rm -rf _runtest
	mkdir _runtest
	ln -s ../_install _runtest/_install
	# Use rsync to ensure hardlinks are created on both Linux and macOS
	rsync --link-dest=../../$(ocamldir)/testsuite/ -a $(ocamldir)/testsuite/ _runtest/testsuite/
	 # replace backend-specific testsuite/tools with their new versions
	rm -f _runtest/testsuite/tools/*
	cp -a oxcaml/testsuite/tools/* _runtest/testsuite/tools/
	cp $(test_build)/oxcaml/testsuite/tools/expect.exe _runtest/testsuite/tools/expect
	chmod 755 _runtest/testsuite/tools/expect
	cp $(test_tools_build)/middle_end/flambda2/tests/tools/fexprc.exe \
          _runtest/testsuite/tools/fexprc
	chmod 755 _runtest/testsuite/tools/fexprc
	cp $(test_codegen) _runtest/testsuite/tools/codegen
	chmod 755 _runtest/testsuite/tools/codegen
	cp $(test_tools_build)/oxcaml/testsuite/tools/asmgen_*.o \
          _runtest/testsuite/tools/
	if [ -z "$(boot_flow)" ]; then \
	  cp $(test_build)/oxcaml/testsuite/tools/expectnat.exe _runtest/testsuite/tools/expectnat; \
	  chmod 755 _runtest/testsuite/tools/expectnat; \
	fi
	cp $(test_build)/testsuite/lib/lib.{a,cmxa,cma} \
          _runtest/testsuite/lib/
	cp $(test_build)/testsuite/lib/.lib.objs/byte/lib.cm* \
          _runtest/testsuite/lib/
	cp $(test_build)/testsuite/lib/.lib.objs/native/lib.cm* \
          _runtest/testsuite/lib/
	cp $(test_build)/testsuite/lib/testing.{a,cmxa,cma} \
          _runtest/testsuite/lib/
	cp $(test_build)/testsuite/lib/.testing.objs/byte/testing.cm* \
          _runtest/testsuite/lib/
	cp $(test_build)/testsuite/lib/.testing.objs/native/testing.cm* \
          _runtest/testsuite/lib/
	 # replace backend-specific testsuite/tests/asmcomp with their new versions
	rm _runtest/testsuite/tests/asmcomp/*
	cp -a oxcaml/testsuite/tests/asmcomp/* _runtest/testsuite/tests/asmcomp/
	 # replace backend-specific testsuite/tests/asmgen with their new versions
	rm _runtest/testsuite/tests/asmgen/*
	cp -a oxcaml/testsuite/tests/asmgen/* _runtest/testsuite/tests/asmgen/
	 # add extension library tests that are not supported by the upstream compiler
	rm _runtest/testsuite/tests/lib-extensions/*
	cp -a oxcaml/testsuite/tests/lib-extensions/* _runtest/testsuite/tests/lib-extensions

	cp $(ocamldir)/Makefile.* _runtest/

#	Create an OCaml directory laid out like the testsuite expects,
#	by copying and symlinking in bits from the install/build directory
	(cd _runtest; \
	 for exe in _install/bin/*; do ln -s $$exe; done; \
         ln -s . boot; \
	 for exe in ocamlc ocamlopt ocamllex; do \
	   rm -f $$exe; ln -s $$exe.byte $$exe; \
         touch ocamlc.opt ocamlopt.opt; \
	 done; \
	 ln -s _install/lib/ocaml stdlib; \
	 mkdir runtime; \
	 for f in ocamlrun* stdlib/caml stdlib/stublibs/* runtime/caml/threads.h; do \
	   ln -s ../$$f runtime/`basename $$f`; \
	 done; \
	 ln -s . lex; ln -s . yacc; \
	 ln -s _install/lib/ocaml/compiler-libs compilerlibs; \
	 mkdir -p otherlibs/{unix,dynlink/native,str,bigarray,runtime_events,eval}; \
	 if [ -z "$(boot_flow)" ]; then \
	   ln -s ../stdlib/threads otherlibs/systhreads; \
           $(cpl) stdlib/unix/{lib,}unix* otherlibs/unix; \
           $(cpl) stdlib/dynlink/dynlink* otherlibs/dynlink; \
           $(cpl) stdlib/str/{lib,}str* otherlibs/str; \
           $(cpl) stdlib/{lib,}eval* otherlibs/eval; \
	   $(cpl) stdlib/runtime_events/{lib,}runtime_events* otherlibs/runtime_events; \
	 fi; \
	 for universe in upstream_compatible stable beta alpha ; do \
		mkdir -p otherlibs/{stdlib_,}$${universe}; \
		$(cpl) stdlib/stdlib_$${universe}/* otherlibs/stdlib_$${universe}; \
	 done; \
	 ln -s ../$(test_build)/$(ocamldir)/toplevel/byte/.ocamltoplevel.objs/byte toplevel; \
	)

	# Various directories are put on the -I paths by tools/Makefile;
	# utils/ is one such, so we just dump the .cm* files in there for
	# various things.
	mkdir _runtest/utils
	cp _install/lib/ocaml/compiler-libs/*.cmi _runtest/utils
	cp $(test_build)/$(ocamldir)/.ocamlcommon.objs/byte/*.cmo _runtest/utils
	rm -f _runtest/utils/{topdirs,opttopdirs}.cmi
	cp _install/lib/ocaml/*.{cmi,cma,a,cmxa} _runtest/utils
	if [ -z "$(boot_flow)" ]; then \
	  cp _install/lib/ocaml/compiler-libs/*.cmx _runtest/utils; \
	  cp _install/lib/ocaml/{unix,str,dynlink}/*.{cmi,cma,a,cmxa} _runtest/utils; \
	  cp $(test_build)/$(ocamldir)/.ocamlcommon.objs/native/config.o _runtest/utils; \
	fi
	# Needed for tests/warnings
	cp $(ocamldir)/utils/warnings.ml _runtest/utils
	# Suppress linker errors about -I directories not existing.
	for dir in asmcomp bytecomp driver file_formats lambda middle_end \
	  parsing typing; do ln -s utils _runtest/$$dir; done
	# stublibs
	mkdir -p _runtest/lib/ocaml/stublibs/
	cp $(test_stublibs)/*.so _runtest/lib/ocaml/stublibs
	# ocamldebug
	mkdir _runtest/debugger
	ln -s ../ocamldebug _runtest/debugger
	if [ -z "$(boot_flow)" ]; then \
	  cp $(test_build)/$(ocamldir)/debugger/.ocamldebug.objs/byte/*.cm* \
	    _runtest/debugger; \
	fi
	# The ast_invariants test needs VERSION to be present.  In fact ideally
	# we should have all the source files in _runtest too for this test,
	# but for the moment we accept it being a weaker check.  We're not
	# working on parts of the compiler that deal with the AST anyway in
	# this repo.
	touch _runtest/VERSION
	# tools
	mkdir _runtest/tools
	if [ -z "$(boot_flow)" ]; then \
	  ln -s ../_install/bin/ocamlmklib.byte _runtest/tools/ocamlmklib; \
	  ln -s ../_install/bin/ocamlobjinfo.byte _runtest/tools/ocamlobjinfo; \
	  ln -s ../_install/bin/dumpobj.byte _runtest/tools/dumpobj; \
	  ln -s ../_install/bin/ocamlfilt _runtest/tools/ocamlfilt; \
	else \
	  for tool in ocamlmklib ocamlobjinfo; do \
	    $(cpl) $(test_build)/oxcaml/testsuite/tools/compiler_shim.bc \
              _runtest/tools/$$tool; \
	    ln -s ../_install/bin/$$tool.opt _runtest/tools/$$tool.opt; \
	  done; \
	  ln -s ../_install/bin/dumpobj.byte _runtest/tools/dumpobj; \
	fi
        # ocamldoc
	# rm _runtest/ocamldoc
	# mkdir _runtest/ocamldoc
	# ln -s ../../_install/bin/ocamldoc.byte _runtest/ocamldoc/ocamldoc
	# cp $(main_build)/$(ocamldir)/ocamldoc/.odoc_lib.objs/byte/*.cm* _runtest/ocamldoc
	# ocamltest itself
	mkdir _runtest/ocamltest
	cp $(boot_build)/ocamltest/ocamltest.native _runtest/ocamltest/ocamltest
endef

install_for_test: test_build = $(main_build)
install_for_test: test_stublibs = $(main_prefix)/lib/ocaml/stublibs
install_for_test: test_tools_build = $(main_build)
install_for_test: test_codegen = \
  $(main_build)/oxcaml/testsuite/tools/codegen_main.exe
install_for_test: boot_flow =
install_for_test: install
	$(prepare_runtest_dir)

# Support libraries and tools needed to run the upstream testsuite with the
# boot compiler, built in the main context (that is, by the boot compiler,
# against the runtime and stdlib produced by [runtime-stdlib]). The
# compilers that the testsuite exercises are the boot compiler's own native
# binaries (see [boot-_install]); ".byte" compiler requests are served by
# the bytecode shim, so the native middle end (in particular flambda2,
# i.e. ocamloptcomp — by far the largest library) is never compiled to
# bytecode. The bytecode compiler-libs (ocamlcommon, ocamlbytecomp,
# ocamltoplevel) *are* built: they are cheap (bytecode produced by the
# native boot compiler) and provide the expect tool, the byte toplevel and
# dumpobj, which large parts of the testsuite need. The tools whose
# dependencies are all bootstrap-compatible (fexprc, codegen) are built in
# the boot context instead, where the system compiler has already built the
# native compiler-libs — see [boot_test_boot_context_targets]. The
# remaining tools cannot exist in this mode and their tests fail: expectnat
# and ocamlnat would need the native compiler-libs built by the boot
# compiler (their sources — the native toplevel, otherlibs — are allowed to
# use syntax the system compiler does not support, so they cannot be built
# in the boot context either).
boot_test_targets = \
  ocamlyacc \
  oxcaml/testsuite/tools/compiler_shim.bc \
  oxcaml/testsuite/tools/expect.exe \
  toplevel/byte/bytetop \
  toplevel/expunge.bc \
  tools/dumpobj.bc \
  ocamlcommon.cma \
  ocamlbytecomp.cma \
  toplevel/byte/ocamltoplevel.cma \
  testsuite/lib/lib.cm{,x}a \
  testsuite/lib/testing.cm{,x}a \
  otherlibs/stdlib_upstream_compatible/stdlib_upstream_compatible.cm{,x}a \
  otherlibs/stdlib_stable/stdlib_stable.cm{,x}a \
  otherlibs/stdlib_beta/stdlib_beta.cm{,x}a \
  otherlibs/stdlib_alpha/stdlib_alpha.cm{,x}a

# Native testsuite tools built in the boot context (that is, by the system
# compiler, which has already built the native compiler-libs there for the
# boot compiler itself), so that the asmgen, codegen and fexpr tests can
# run without building any native compiler-libs with the boot compiler.
# codegen needs unix, which cannot be built in the boot context, hence the
# dedicated stanza in oxcaml/testsuite/tools/boot/dune.
boot_test_boot_context_targets = \
  middle_end/flambda2/tests/tools/fexprc.exe \
  oxcaml/testsuite/tools/boot/codegen_main.exe \
  oxcaml/testsuite/tools/asmgen_$(ARCH).o

.PHONY: boot-test-artifacts
boot-test-artifacts: runtime-stdlib
	SYSTEM=$(SYSTEM) MODEL=$(MODEL) \
          ASPP="$(ASPP)" ASPPFLAGS="$(ASPPFLAGS)" \
          $(dune) build $(ws_main) $(boot_test_targets)
	SYSTEM=$(SYSTEM) MODEL=$(MODEL) \
          ASPP="$(ASPP)" ASPPFLAGS="$(ASPPFLAGS)" \
          $(dune) build $(ws_boot) $(boot_test_boot_context_targets)

# Extend the boot compiler installation in _install (see [boot-_install])
# with the pieces needed by the upstream testsuite, laid out as the main
# compiler's installation would be. The ".byte" tools are the bytecode shim
# (see oxcaml/testsuite/tools/compiler_shim.ml): tests that request them
# run the boot compiler's native binaries instead.
.PHONY: boot-test-install
boot-test-install: boot-_install boot-test-artifacts
	$(cpl) $(main_build)/oxcaml/testsuite/tools/compiler_shim.bc \
          _install/bin/ocamlc.byte
	$(cpl) $(main_build)/oxcaml/testsuite/tools/compiler_shim.bc \
          _install/bin/ocamlopt.byte
	$(cpl) $(main_build)/oxcaml/testsuite/tools/compiler_shim.bc \
          _install/bin/ocamllex.byte
	$(cpl) $(main_build)/ocamlyacc _install/bin/ocamlyacc
	$(cpl) $(main_build)/toplevel/byte/bytetop _install/bin/ocaml
	$(cpl) $(main_build)/tools/dumpobj.bc _install/bin/dumpobj.byte
	$(cpl) $(main_build)/toplevel/expunge.bc _install/lib/ocaml/expunge
	mkdir -p _install/lib/ocaml/stublibs
	$(cpl) -f _install/lib/stublibs/*.so _install/lib/ocaml/stublibs/
	$(cpl) $(main_build)/ocamlcommon.cma $(main_build)/ocamlbytecomp.cma \
          _install/lib/ocaml/compiler-libs/
	$(cpl) $(main_build)/toplevel/byte/ocamltoplevel.cma \
          _install/lib/ocaml/compiler-libs/
	$(cpl) -f $(main_build)/.ocamlcommon.objs/byte/*.cmi \
          _install/lib/ocaml/compiler-libs/
	$(cpl) -f $(main_build)/.ocamlbytecomp.objs/byte/*.cmi \
          _install/lib/ocaml/compiler-libs/
	$(cpl) -f $(main_build)/toplevel/byte/.ocamltoplevel.objs/byte/*.cmi \
          _install/lib/ocaml/compiler-libs/
	$(cpl) -f $(main_build)/toplevel/byte/.ocamltoplevel.objs/byte/topdirs.{cmt,cmti} \
          _install/lib/ocaml/compiler-libs/
	$(cpl) -f $(main_build)/toplevel/byte/topdirs.mli \
          _install/lib/ocaml/compiler-libs/
	cp -f _install/lib/ocaml/compiler-libs/topdirs.{cmi,mli,cmt,cmti} \
          _install/lib/ocaml
	for universe in upstream_compatible stable beta alpha ; do \
	  mkdir -p _install/lib/ocaml/stdlib_$$universe; \
	  $(cpl) $(main_build)/otherlibs/stdlib_$$universe/stdlib_$$universe.{cma,cmxa,a} \
            _install/lib/ocaml/stdlib_$$universe/; \
	  $(cpl) $(main_build)/otherlibs/stdlib_$$universe/.stdlib_$$universe.objs/byte/*.cmi \
            _install/lib/ocaml/stdlib_$$universe/; \
	  $(cpl) $(main_build)/otherlibs/stdlib_$$universe/.stdlib_$$universe.objs/native/*.cmx \
            _install/lib/ocaml/stdlib_$$universe/; \
	done

# Like [install_for_test], but for testing the boot compiler: the compilers
# that the testsuite exercises are the boot compiler's own native binaries,
# and nothing expensive is built — only the stdlib, the stdlib_* universes,
# the testsuite support libraries and the *bytecode* compiler-libs (for the
# expect tool, the byte toplevel and dumpobj); never the native middle end
# in bytecode. Tests that request the ".byte" compilers transparently run
# the native ones through the compiler shim; fexprc and codegen are built
# in the boot context by the system compiler. Only expectnat and ocamlnat
# do not exist in this mode (see [boot_test_targets] above): their tests
# fail, and whole directories that cannot work are excluded via
# oxcaml/testsuite/boot-test-list. Note also that unlike
# [install_for_test], nothing is installed to the configured prefix, so the
# rare tests that look outside of _runtest (e.g. via +compiler-libs, which
# expands to the configured standard library path) can fail.
install_for_test_boot: test_build = $(main_build)
install_for_test_boot: test_stublibs = _install/lib/ocaml/stublibs
install_for_test_boot: test_tools_build = $(boot_build)
install_for_test_boot: test_codegen = \
  $(boot_build)/oxcaml/testsuite/tools/boot/codegen_main.exe
install_for_test_boot: boot_flow = true
install_for_test_boot: boot-test-install
	$(prepare_runtest_dir)

# The canned recipe below runs the upstream testsuite in _runtest. It is
# parameterized by the [test_skip_lists] target-specific variable: when it is
# non-empty, only the test directories not mentioned in any of the listed
# files are run.
define run_upstream_testsuite
	if [ -n "$(strip $(test_skip_lists))" ]; then \
	  for path in `cd testsuite; ls -1 -d tests/*`; do \
	    if [[ -d "testsuite/$$path" ]] && ! grep -q "^  $$path " $(test_skip_lists); then \
	      echo "  $$path"; \
	    fi; \
	  done > _runtest/test-list; \
	fi
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite \
	  && if $$(which parallel > /dev/null 2>&1); \
             then \
	       echo "Running testsuite in parallel (nproc=$$(nproc))"; \
               if [ -n "$(strip $(test_skip_lists))" ]; then \
                 make --no-print-directory list-parallel FILE=$$(pwd)/../test-list; \
	       else \
                 make --no-print-directory parallel; \
               fi \
             else \
	       echo "Running testsuite sequentially"; \
               if [ -n "$(strip $(test_skip_lists))" ]; then \
                 make --no-print-directory list FILE=$$(pwd)/../test-list; \
	       else \
                 make --no-print-directory all; \
               fi \
             fi)
endef

test: test_skip_lists = \
  $(if $(filter flambda2,$(middle_end)),oxcaml/testsuite/flambda2-test-list)
test: install_for_test
	$(run_upstream_testsuite)

test-boot: test_skip_lists = \
  $(if $(filter flambda2,$(middle_end)),oxcaml/testsuite/flambda2-test-list) \
  oxcaml/testsuite/boot-test-list
test-boot: install_for_test_boot
	$(run_upstream_testsuite)

promote-failed:
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite && make promote-failed)

runtest-upstream: test

# Run the upstream testsuite with the boot compiler instead of the final
# compiler; see [install_for_test_boot] above.
runtest-upstream-boot: test-boot

test-one: install_for_test
	$(MAKE) test-one-no-rebuild

# If the TEST argument is passed as `testsuite/tests/foo` (as is invited by
# tab completion) then look for it in `tests/foo`. Otherwise, if it's passed as
# just `foo`, then look for it in `tests/foo` for backward compatibility.
locate_test = \
  $(shell \
    test=$(shell echo "$1" | sed 's|^testsuite/tests/||g'); \
    echo "tests/$${test}"; \
  )

test-one-no-rebuild:
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite && make one $(if $(TEST),TEST=$(call locate_test,$(TEST))) $(if $(DIR),DIR=$(call locate_test,$(DIR))))

promote-one: install_for_test
	$(MAKE) promote-one-no-rebuild

promote-one-no-rebuild:
	(export OCAMLSRCDIR=$$(pwd)/_runtest; \
	 export CAML_LD_LIBRARY_PATH=$$(pwd)/_runtest/lib/ocaml/stublibs; \
	 if $$(which gfortran > /dev/null 2>&1); then \
	   export LIBRARY_PATH=$$(dirname $$(gfortran -print-file-name=libgfortran.a)); \
	 fi; \
	 cd _runtest/testsuite && make promote $(if $(TEST),TEST=$(call locate_test,$(TEST))) $(if $(DIR),DIR=$(call locate_test,$(DIR))))

# This target is like a polling version of upstream "make ocamlopt"
.PHONY: hacking
hacking: _build/_bootinstall
	$(dune) build $(ws_boot) -w @merlin-support $(boot_targets)

# The `hacking-emacs-poller` and `hacking-emacs-builder` targets make it
# possible to run the polling build with Emacs's `M-x compile`.  You should run
# `make hacking-emacs-poller` in your terminal from the root directory of the
# repo, and set Emacs's `compile-command` to `make hacking-emacs-builder` (from
# the appropriate directory).

.PHONY: hacking-emacs-poller
hacking-emacs-poller: _build/_bootinstall
	$(dune) build $(ws_boot) --passive-watch-mode

.PHONY: hacking-emacs-builder
hacking-emacs-builder: _build/_bootinstall
	$(dune) rpc build $(ws_boot) -w @merlin-support $(boot_targets)
	$(dune) diagnostics

.PHONY: debug-printers
debug-printers: runtime-stdlib # required for $(ws_main) to work
	 $(dune) build $(ws_main) $(ocamldir)/tools/debug_printers
	@echo
	@echo To load into ocamldebug, use:
	@echo source \"$$(realpath _build/main/$(ocamldir)/tools/debug_printers)\"

# boot-_install installs the bootstrapped compiler into _install. It is mostly
# just copied from the install phrase.
# This allows tools/compare.sh to function as expected, which is useful because
# it allows us to easily run the bootstrapped compiler, especially with
# tools/compare.sh
.PHONY: boot-_install
boot-_install: runtime-stdlib
	rm -rf _install
	mkdir -p _install/{bin,lib/ocaml}
	$(cpl) _build/runtime_stdlib_install/bin/* _install/bin/
	# can't use a hard link here because ocamllex comes from the system and
	# is possibly on a different device
	ln -sf $(realpath _build/_bootinstall/bin/ocamllex.opt) _install/bin/ocamllex.opt
	$(cpl) _build/_bootinstall/bin/ocaml{c,opt,mklib,dep,objinfo}.opt _install/bin/
	( cd _install/bin; for i in *.opt; do ln -s $$i $${i%.opt}; done )
	$(cpl) -R _build/runtime_stdlib_install/lib/ocaml_runtime_stdlib/* \
    _install/lib/ocaml/
	rm -f _install/lib/ocaml/{META,dune-package,Makefile.config,dynlink.cmxa,dynlink/dynlink.cmxa}
	$(cpl) -R _build/_bootinstall/lib/ocaml/* _install/lib/ocaml/
	rm -f _install/lib/ocaml/{META,dune-package}
	rm -f _install/lib/ocaml/compiler-libs/*.cmo
	mkdir _install/lib/stublibs
	find _build/default -name "dll*.so" \
       -print0 | xargs -0 -I '{}' cp -f '{}' _install/lib/stublibs
	mkdir -p _install/lib/ocaml/compiler-libs
	cp _build/default/parser.cmly _install/lib/ocaml/compiler-libs/
	find _build/default/ \( -name "flambda2*.cmi" \
          -or -name "flambda2*.cmti" -or -name "flambda2*.cmt" \) \
          -print0 | xargs -0 -I '{}' cp -f '{}' _install/lib/ocaml/compiler-libs
