(* TEST
 readonly_files = "ppx_duplicate_binding.ml";
 include ocamlcommon;
 native-compiler;
 setup-ocamlopt.opt-build-env;
 program = "${test_build_directory}/ppx_duplicate_binding.exe";
 all_modules = "ppx_duplicate_binding.ml";
 ocamlopt.opt;
 unset libraries;
 program = "${test_build_directory}/names_shared_locations.exe";
 all_modules = "names_shared_locations.ml";
 flags = "-g -ppx ${test_build_directory}/ppx_duplicate_binding.exe";
 ocamlopt.opt;
 run;
 check-program-output;
*)

(* [ppx_duplicate_binding.ml] duplicates each binding marked [@duplicate]
   below, so that [raiser] and [raiser_copy], and [caller] and [caller_copy],
   have exactly the same locations, as the specialisations of one function
   generated by a ppx do.  Each of them must get its own debuginfo record in
   the frametable: the records only differ in their defname, which is derived
   from the scopes, and the scopes are ignored by [Debuginfo.Dbg.compare]. *)

exception E of int

let[@inline never] raiser n = raise (E n) [@@duplicate]

let[@inline never] caller f n = (f n [@nontail]) [@@duplicate]

let show f =
  match f () with
  | () -> assert false
  | exception E _ -> Printexc.print_backtrace stdout

let () =
  Printexc.record_backtrace true;
  show (fun () -> caller raiser 1);
  show (fun () -> caller_copy raiser_copy 2)
