/**************************************************************************/
/*                                                                        */
/*                                 OCaml                                  */
/*                                                                        */
/*      KC Sivaramakrishnan, Indian Institute of Technology, Madras       */
/*                   Tom Kelly, OCaml Labs Consultancy                    */
/*                 Stephen Dolan, University of Cambridge                 */
/*                                                                        */
/*   Copyright 2019 Indian Institute of Technology, Madras                */
/*   Copyright 2021 OCaml Labs Consultancy Ltd                            */
/*   Copyright 2019 University of Cambridge                               */
/*                                                                        */
/*   All rights reserved.  This file is distributed under the terms of    */
/*   the GNU Lesser General Public License version 2.1, with the          */
/*   special exception on linking described in the file LICENSE.          */
/*                                                                        */
/**************************************************************************/

#define CAML_INTERNALS

#include "caml/platform.h"
#include "caml/frame_descriptors.h"
#include "caml/major_gc.h" /* for caml_major_cycles_completed */
#include "caml/memory.h"
#include "caml/fail.h"
#include "caml/shared_heap.h"
#include "caml/backtrace_prim.h"
#include <stddef.h>

/* A small descriptor does not carry its own return address (it is
   reconstructed by walking the delta chain when a frametable is
   registered), so each hash-table slot stores the absolute return
   address alongside the descriptor-body pointer. An empty slot has
   [fd == NULL]. */
typedef struct {
  uintnat retaddr;
  frame_descr *fd;
} frame_descr_entry;

struct caml_frame_descrs {
  int num_descr;
  int mask;
  frame_descr_entry *descriptors;
  caml_frametable_list *frametables;
  caml_frametable_list *zombies;
  caml_plat_mutex mutex;
};
/* Let us call 'capacity' the length of the descriptors array.

   We maintain the following invariants:
     capacity = mask + 1
     capacity = 0 || Is_power_of_2(capacity)
     num_desc <= 2 * num_descr <= capacity

   For an extensible array we would maintain
      num_desc <= capacity,
    but this is a linear-problem hash table, we need to ensure that
    free slots are frequent enough, so we use a twice-larger capacity:
      num_desc * 2 <= capacity

   We keep the list of frametables that was used to build the hashtable.
   We use it when rebuilding the table after resizing.

   We keep the list of frametables which need to be removed (zombies).
   We remove them in a STW handler before any new addition.

   We allow the user to call functions for frametable removal at any
   time, even inside a STW section (e.g. during custom block finalization).
   To this end, we use a mutex to protect the frametable insertions in
   the zombies list.

   All other modifications should only happen in a STW section.
*/

/* Defined in code generated by ocamlopt */
extern intnat * caml_frametable[];

/* Note: [cur] is bound by this macro */
#define iter_list(list,cur) \
  for (caml_frametable_list *cur = list; cur != NULL; cur = cur->next)

/* Decode one descriptor (small or escaped) into [out], filling in its
   flags, sizes, and the pointers needed to locate its live offsets,
   allocation sizes, and debug words. [d] points at the descriptor body
   (the byte after its LEB128 delta / escape byte). */
void caml_decode_frame_descr(frame_descr *d, struct frame_descr_decoded *out)
{
  memset(out, 0, sizeof(*out));
  if (frame_is_small(d)) {
    const unsigned char *p = (const unsigned char *)d;
    unsigned char sf = *p++; /* size+flags byte */
    out->is_small = true;
    out->has_allocs = (sf & FRAME_DESCRIPTOR_ALLOC) != 0;
    out->has_debug = (sf & FRAME_DESCRIPTOR_DEBUG) != 0;
    out->frame_size = (((uint32_t)(sf >> 2)) + 1) * 16;
    if (out->has_allocs) {
      out->small_reg_bitmap = *p++;
      out->small_num_allocs = *p++;
      out->small_allocs = p;
      p += (out->small_num_allocs + 1) / 2; /* 4-bit alloc sizes */
      out->num_live = *p++;
    } else {
      out->num_live = *p++;
    }
    out->small_live = p;
    p += out->num_live; /* one byte per live stack slot (word offset) */
    out->end_of_live = p;
    out->num_debuginfo = out->has_allocs ? out->small_num_allocs : 1;
    if (out->has_debug) {
      p += sizeof(uint32_t) * out->num_debuginfo;
    }
    out->end = p;
    return;
  }

  /* Escaped descriptor: normal or long format. */
  if (frame_return_to_C(d)) {
    out->return_to_C = true;
    /* Top of an ML stack chunk: an empty descriptor. */
    CAMLassert(caml_read_unaligned_uint16(d + Frame_num_live_ofs) == 0);
    out->end_of_live = out->end = d + Frame_live_ofs;
    return;
  }
  out->is_long = frame_is_long(d);
  out->has_allocs = frame_has_allocs(d);
  out->has_debug = frame_has_debug(d);
  out->frame_size = frame_size(d);
  if (out->is_long) {
    out->num_live = caml_read_unaligned_uint32(d + Frame_long_num_live_ofs);
  } else {
    out->num_live = caml_read_unaligned_uint16(d + Frame_num_live_ofs);
  }
  const unsigned char *p = frame_end_of_live_ofs(d);
  out->end_of_live = p;
  out->num_debuginfo = 1;
  if (out->has_allocs) {
    out->small_num_allocs = *p;
    out->num_debuginfo = *p;
    p += (uintnat)(*p) + 1; /* num_allocs byte + one byte per alloc */
  }
  if (out->has_debug) {
    p += sizeof(uint32_t) * out->num_debuginfo;
  }
  out->end = p;
}

/* Iterate over the descriptors of one frametable, reconstructing the
   absolute return address of each descriptor by walking the delta chain.
   An escaped descriptor carries an absolute return address (retaddr_rel);
   a small descriptor's address is the running address plus its delta. */
typedef struct {
  const unsigned char *next; /* points at the next descriptor's delta byte */
  uintnat retaddr;           /* running absolute return address */
  intnat remaining;          /* descriptors left to yield */
} frametable_iter;

static void frametable_iter_start(frametable_iter *it, intnat *tbl)
{
  it->remaining = (intnat)caml_read_unaligned_uintnat(tbl);
  it->next = (const unsigned char *)(tbl + 1);
  it->retaddr = 0;
}

/* Yield the next descriptor body and its absolute return address. Must
   only be called while [it->remaining > 0]. */
static frame_descr *frametable_iter_next(frametable_iter *it,
                                         uintnat *retaddr_out)
{
  const unsigned char *p = it->next;
  frame_descr *d;
  if (*p == FRAME_DELTA_ESCAPE) {
    p++;
    d = (frame_descr *)p;
    it->retaddr = Retaddr_frame(d);
  } else {
    /* Unsigned LEB128 delta (>= 1, so it never starts with a 0 byte). */
    uintnat delta = 0;
    int shift = 0;
    unsigned char byte;
    do {
      byte = *p++;
      delta |= (uintnat)(byte & 0x7f) << shift;
      shift += 7;
    } while (byte & 0x80);
    it->retaddr += delta;
    d = (frame_descr *)p;
  }
  struct frame_descr_decoded dec;
  caml_decode_frame_descr(d, &dec);
  it->next = dec.end;
  it->remaining--;
  *retaddr_out = it->retaddr;
  return d;
}

static intnat count_descriptors(caml_frametable_list *list) {
  intnat num_descr = 0;
  iter_list(list,cur) {
    num_descr += (intnat)caml_read_unaligned_uintnat(cur->frametable);
  }
  return num_descr;
}

static caml_frametable_list* frametables_list_tail(caml_frametable_list *list) {
  caml_frametable_list *tail = NULL;
  iter_list(list,cur) {
    tail = cur;
  }
  return tail;
}

static int capacity(caml_frame_descrs table) {
  int capacity = table.mask + 1;
  CAMLassert(capacity == 0 || Is_power_of_2(capacity));
  return capacity;
}

static void fill_hashtable(
  caml_frame_descrs *table, caml_frametable_list *new_frametables)
{
  iter_list(new_frametables,cur) {
    frametable_iter it;
    frametable_iter_start(&it, (intnat *) cur->frametable);
    while (it.remaining > 0) {
      uintnat retaddr;
      frame_descr *d = frametable_iter_next(&it, &retaddr);
      uintnat h = Hash_retaddr(retaddr, table->mask);
      while (table->descriptors[h].fd != NULL) {
        h = (h+1) & table->mask;
      }
      table->descriptors[h].retaddr = retaddr;
      table->descriptors[h].fd = d;
    }
  }
}

static void remove_entry(caml_frame_descrs *table, uintnat retaddr,
                         frame_descr * d) {
  uintnat i;
  uintnat r;
  uintnat j;

  i = Hash_retaddr(retaddr, table->mask);
  while (table->descriptors[i].fd != d) {
    i = (i+1) & table->mask;
  }

 r1:
  j = i;
  table->descriptors[i].fd = NULL;
 r2:
  i = (i+1) & table->mask;
  // r3
  if(table->descriptors[i].fd == NULL) return;
  r = Hash_retaddr(table->descriptors[i].retaddr, table->mask);
  /* If r is between i and j (cyclically), i.e. if
     table->descriptors[i]->retaddr don't need to be moved */
  if(( ( j < r )  && ( r <= i ) ) ||
     ( ( i < j )  && ( j < r )  ) ||      /* i cycled, r not */
     ( ( r <= i ) && ( i < j ) )     ) {  /* i and r cycled */
    goto r2;
  }
  // r4
  table->descriptors[j] = table->descriptors[i];
  goto r1;
}

static void clean_frame_descriptors(caml_frame_descrs *table)
{
  intnat decrease = 0;
  caml_frametable_list *cur = table->zombies, *rem;
  while (cur != NULL) {
    frametable_iter it;
    frametable_iter_start(&it, (intnat *) cur->frametable);
    intnat len = it.remaining;
    while (it.remaining > 0) {
      uintnat retaddr;
      frame_descr *d = frametable_iter_next(&it, &retaddr);
      remove_entry(table, retaddr, d);
    }
    decrease += len;
    rem = cur;
    cur = cur->next;
    caml_stat_free(rem);
  }
  table->num_descr -= decrease;
  table->zombies = NULL;
}

/* ---- Frametable measurement ---- */

/* Walks the frametables in the new ("small") on-disk format and reports
 * their real sizes, so we can track how much the compact encoding saves.
 * Settable via GC tweaks OCAMLRUNPARAM=Xmeasure_frametables (the
 * frametables registered in this batch) and Xmeasure_all_frametables (all
 * units linked into the executable, via the caml_all_frametables set). */

extern uintnat caml_measure_frametables;
extern uintnat caml_measure_all_frametables;

struct frametable_stats {
  size_t frametables;
  size_t descrs;         /* total descriptors */
  size_t small_descrs;   /* small-format descriptors */
  size_t escaped_descrs; /* escaped (normal/long) descriptors */
  size_t wide_deltas;    /* small descrs whose LEB128 delta needs >1 byte */
  size_t return_to_C;
  size_t with_alloc;
  size_t with_debug;

  size_t descr_bytes;    /* bytes of frame descriptors (incl. delta bytes) */
  size_t header_bytes;   /* per-frametable count words */
  size_t debuginfo_bytes;
  size_t debuginfo_count;
};

static void report_bytes(char *buf, size_t space, size_t val)
{
  if (val < 1024) {
    snprintf(buf, space, "%zu", val);
  } else {
    char suffix[] = " kMGTE";
    double scaled = val;
    char *p = suffix;
    while (scaled > 1000 && *p) {
      scaled /= 1024.0;
      ++p;
    }
    snprintf(buf, space, "%.2f %ciB", scaled, *p);
  }
}

/* Record stats for the descriptors of one frametable. */
static void add_frametable_to_stats(intnat *frametable,
                                    struct frametable_stats *stats)
{
  ++stats->frametables;
  stats->header_bytes += sizeof(intnat);
  caml_debuginfo_reset();

  frametable_iter it;
  frametable_iter_start(&it, frametable);
  const unsigned char *start = it.next;
  while (it.remaining > 0) {
    const unsigned char *delta_at = it.next;
    unsigned char delta0 = *delta_at;
    uintnat retaddr;
    frame_descr *d = frametable_iter_next(&it, &retaddr);
    ++stats->descrs;
    if (delta0 == FRAME_DELTA_ESCAPE) {
      ++stats->escaped_descrs;
    } else {
      ++stats->small_descrs;
      /* Count small descriptors whose LEB128 delta needed more than one
         byte (the high bit of the first byte is set). */
      if (delta0 & 0x80) ++stats->wide_deltas;
    }

    struct frame_descr_decoded dec;
    caml_decode_frame_descr(d, &dec);
    if (dec.return_to_C) ++stats->return_to_C;
    if (dec.has_allocs) ++stats->with_alloc;
    if (dec.has_debug) {
      ++stats->with_debug;
      const unsigned char *p = dec.end_of_live;
      if (!dec.is_small && dec.has_allocs) {
        /* escaped: skip num_allocs byte + alloc bytes */
        p += (uintnat)(*p) + 1;
      }
      for (uint32_t i = 0; i < dec.num_debuginfo; ++i) {
        uint32_t offset = caml_read_unaligned_uint32(p);
        if (offset) {
          caml_debuginfo_measure((debuginfo)(p + offset));
        }
        p += sizeof(uint32_t);
      }
    }
  }
  /* it.next now points just past the last descriptor. */
  stats->descr_bytes += (size_t)(it.next - start);

  char *dbg_low, *dbg_high;
  size_t dbg_count;
  caml_debuginfo_measurements(&dbg_count, &dbg_low, &dbg_high);
  dbg_high = Align_to(dbg_high, uintnat);
  if (dbg_count) {
    stats->debuginfo_bytes += (size_t)(dbg_high - dbg_low);
    stats->debuginfo_count += dbg_count;
  }
}

static void report_stats(struct frametable_stats *stats)
{
  char buf[64];
  size_t total = stats->header_bytes + stats->descr_bytes
                 + stats->debuginfo_bytes;
  printf("Summary of %zu frametables, %zu descriptors "
         "(%zu small, %zu escaped, %zu multi-byte-delta).\n",
         stats->frametables, stats->descrs, stats->small_descrs,
         stats->escaped_descrs, stats->wide_deltas);
  printf("return-to-C %zu  alloc %zu  debug %zu\n",
         stats->return_to_C, stats->with_alloc, stats->with_debug);
  report_bytes(buf, sizeof(buf), stats->descr_bytes);
  printf("%s descriptors (%5.2f%%; %f bytes each)\n", buf,
         total ? (double)stats->descr_bytes / total * 100.0 : 0.0,
         stats->descrs ? (double)stats->descr_bytes / stats->descrs : 0.0);
  report_bytes(buf, sizeof(buf), stats->header_bytes);
  printf("%s frametable headers\n", buf);
  report_bytes(buf, sizeof(buf), stats->debuginfo_bytes);
  printf("%s Debuginfo (%5.2f%%; %zu entries)\n", buf,
         total ? (double)stats->debuginfo_bytes / total * 100.0 : 0.0,
         stats->debuginfo_count);
}

static void report_frametables_stats(caml_frametable_list *new_frametables)
{
  struct frametable_stats stats;
  memset(&stats, 0, sizeof(stats));
  iter_list(new_frametables, cur) {
    add_frametable_to_stats(cur->frametable, &stats);
  }
  report_stats(&stats);
}

/* The backend emits one pointer per linked unit into the caml_all_frametables
 * section; the linker concatenates them and provides these bounds. Weak so the
 * runtime still links where no such section exists (both NULL). */
extern intnat *__start_caml_all_frametables[] __attribute__((weak));
extern intnat *__stop_caml_all_frametables[] __attribute__((weak));

/* Measure every frametable in the executable - including dynlink-available
 * units that are never registered in caml_frametable[]. Reads only static data
 * and read-only frame descriptors; runs no module initializers. */
static void report_all_frametables_stats(void)
{
  struct frametable_stats stats;
  memset(&stats, 0, sizeof(stats));
  for (intnat **p = __start_caml_all_frametables;
       p < __stop_caml_all_frametables; p++) {
    add_frametable_to_stats(*p, &stats);
  }
  report_stats(&stats);
}

static void add_frame_descriptors(
  caml_frame_descrs *table,
  caml_frametable_list *new_frametables)
{
  CAMLassert(new_frametables != NULL);

  caml_frametable_list *tail = frametables_list_tail(new_frametables);
  intnat increase = count_descriptors(new_frametables);
  intnat tblsize = capacity(*table);

  /* The size of the hashtable is a power of 2 that must remain
     greater or equal to 2 times the number of descriptors. */

  /* Reallocate the caml_frame_descriptor table if it is too small */
  if(tblsize < (table->num_descr + increase) * 2) {

    /* Merge both lists */
    tail->next = table->frametables;
    table->frametables = NULL;

    intnat num_descr = table->num_descr + increase;

    tblsize = 4;
    while (tblsize < 2 * num_descr) tblsize *= 2;

    table->num_descr = num_descr;
    table->mask = tblsize - 1;

    if (table->descriptors != NULL) caml_stat_free(table->descriptors);
    table->descriptors =
      (frame_descr_entry *) caml_stat_calloc_noexc(tblsize,
                                                   sizeof(frame_descr_entry));
    if (table->descriptors == NULL) caml_raise_out_of_memory();

    fill_hashtable(table, new_frametables);
    if (caml_measure_frametables) {
      report_frametables_stats(new_frametables);
    }
  } else {
    table->num_descr += increase;
    fill_hashtable(table, new_frametables);
    if (caml_measure_frametables) {
      report_frametables_stats(new_frametables);
    }
    tail->next = table->frametables;
  }

  table->frametables = new_frametables;
}

/* protected by STW sections */
static caml_frame_descrs current_frame_descrs =
  { 0, -1, NULL, NULL, NULL, CAML_PLAT_MUTEX_INITIALIZER };

static caml_frametable_list *cons(
  intnat *frametable, caml_frametable_list *tl)
{
  caml_frametable_list *li = caml_stat_alloc(sizeof(caml_frametable_list));
  li->frametable = frametable;
  li->next = tl;
  return li;
}

/* This function not only creates a new caml_frametable_list cell but
   also makes a copy of the new frametable.
   Here, we allocate, in a single malloc call, the space for the cons
   cell and the (appended) frametable copy. This way, we do not have
   to change the code that unregisters the frametable since calling free
   on the cons cell will automatically free the frametable copy at the
   same time.
*/
static caml_frametable_list *copy_cons(
  intnat **frametable, intnat size, caml_frametable_list *tl)
{
  caml_frametable_list *li =
    caml_stat_alloc(sizeof(caml_frametable_list) + size);
  intnat *frametable_copy = (intnat*)(li + 1);
  memcpy(frametable_copy, *frametable, size);
  *frametable = frametable_copy;
  li->frametable = frametable_copy;
  li->next = tl;
  return li;
}

void caml_init_frame_descriptors(void)
{
  caml_frametable_list *frametables = NULL;
  for (int i = 0; caml_frametable[i] != 0; i++)
    frametables = cons(caml_frametable[i], frametables);

  /* `init_frame_descriptors` is called from `init_gc`, before
     any mutator can run. We can mutate [current_frame_descrs]
     at will. */
  add_frame_descriptors(&current_frame_descrs, frametables);

  if (caml_measure_all_frametables) {
    report_all_frametables_stats();
  }
}

static void register_frametables_from_stw_single(
  caml_frametable_list *new_frametables)
{
  clean_frame_descriptors(&current_frame_descrs);
  add_frame_descriptors(&current_frame_descrs, new_frametables);
}

static void stw_register_frametables(
    caml_domain_state* domain,
    void* frametables,
    int participating_count,
    caml_domain_state** participating)
{
  Caml_global_barrier_if_final(participating_count) {
    register_frametables_from_stw_single((caml_frametable_list *) frametables);
  }
}

void caml_register_frametables(void **table, int ntables) {
  caml_frametable_list *new_frametables = NULL;
  for (int i = 0; i < ntables; i++)
    new_frametables = cons(table[i], new_frametables);

  do {} while (!caml_try_run_on_all_domains(
                 &stw_register_frametables, new_frametables, 0));
}

void caml_copy_and_register_frametables(
  void **table, int * sizes, int ntables)
{
  caml_frametable_list *new_frametables = NULL;
  for (int i = 0; i < ntables; i++)
    new_frametables = copy_cons((intnat **)(table + i),
                                sizes[i], new_frametables);

  do {} while (!caml_try_run_on_all_domains(
                 &stw_register_frametables, new_frametables, 0));
}

static void remove_frame_descriptors(
  caml_frame_descrs * table, void ** frametables, int ntables)
{
  void *frametable;
  caml_frametable_list ** previous;

  /* cannot release the domain lock here (e.g. custom block finaliser) */
  caml_plat_lock_blocking(&table->mutex);

  previous = &table->frametables;

  iter_list(table->frametables, current) {
  resume:
    for (int i = 0; i < ntables; i++) {
      if (current->frametable == frametables[i]) {
        *previous = current->next;
        current->next = table->zombies;
        table->zombies = current;
        ntables--;
        if (ntables == 0) goto release;
        current = *previous;
        frametable = frametables[i];
        frametables[i] = frametables[ntables];
        frametables[ntables] = frametable;
        goto resume;
      }
    }
    previous = &current->next;
  }

 release:
  caml_plat_unlock(&table->mutex);
}

void caml_unregister_frametables(void ** frametables, int ntables)
{
  remove_frame_descriptors(&current_frame_descrs, frametables, ntables);
}

void caml_register_frametable(void * frametables)
{
  caml_register_frametables(&frametables, 1);
}

void* caml_copy_and_register_frametable(void * frametable, int size)
{
  caml_copy_and_register_frametables(&frametable, &size, 1);
  return frametable;
}

void caml_unregister_frametable(void * frametables)
{
  caml_unregister_frametables(&frametables, 1);
}

caml_frame_descrs* caml_get_frame_descrs(void)
{
  return &current_frame_descrs;
}

frame_descr* caml_find_frame_descr(caml_frame_descrs *fds, uintnat pc)
{
  uintnat h;

  h = Hash_retaddr(pc, fds->mask);
  while (1) {
    frame_descr_entry e = fds->descriptors[h];
    if (e.fd == NULL)
      return NULL; /* can happen if some code compiled without -g */
    if (e.retaddr == pc) return e.fd;
    h = (h+1) & fds->mask;
  }
}
