/**************************************************************************/
/*                                                                        */
/*                                 OCaml                                  */
/*                                                                        */
/*                Nick Barnes, Jane Street                                */
/*                                                                        */
/*   Copyright 2026 Jane Street Group LLC                                 */
/*                                                                        */
/*   All rights reserved.  This file is distributed under the terms of    */
/*   the GNU Lesser General Public License version 2.1, with the          */
/*   special exception on linking described in the file LICENSE.          */
/*                                                                        */
/**************************************************************************/

/* Generates asm_offsets.inc: the offsets into C structures which the
   assembly-language stubs (amd64.S, arm64.S) need, computed from the
   real definitions so that they cannot go stale.  Compiled with the
   target compiler and run at build time (so no cross-compilation).

   The set of names is the same for every architecture: for each
   field, a bare <name>_offset value and an operand macro <name>.
   Only the operand-macro shape is per-target: flat object-like on
   amd64 (Stack_sp(%r10) expands to 0(%r10)), function-like
   [reg, #ofs] on arm64. */

#define CAML_INTERNALS

#include <stddef.h>
#include <stdio.h>

#include "caml/config.h"
#include "caml/misc.h"
#include "caml/mlvalues.h"
#include "caml/fiber.h"
#include "caml/dynamic.h"

static void def(const char *name, unsigned long v)
{
  printf("#define %-28s %lu\n", name, v);
}

/* A bare offset value and a memory-operand macro for a field at
   offset [off]. */
static void field(const char *name, unsigned long off)
{
  char offset_name[64];
  snprintf(offset_name, sizeof offset_name, "%s_offset", name);
  def(offset_name, off);
#ifdef TARGET_arm64
  if (off == 0)
    printf("#define %s(reg) [reg]\n", name);
  else
    printf("#define %s(reg) [reg, #%lu]\n", name, off);
#else
  def(name, off);
#endif
}

int main(void)
{
  printf("/* Generated by gen_asm_offsets.c; do not edit. */\n");

  printf("\n/* struct stack_info; _from_cont is the handler field as"
         "\n   addressed from a tagged continuation-fiber pointer. */\n");
  field("Stack_sp", offsetof(struct stack_info, sp));
  field("Stack_exception", offsetof(struct stack_info, exception_ptr));
  field("Stack_handler", offsetof(struct stack_info, handler));
  field("Stack_handler_from_cont",
        offsetof(struct stack_info, handler) - 1);
  field("Stack_id", offsetof(struct stack_info, id));
  field("Stack_local_sp", offsetof(struct stack_info, local_sp));
  field("Stack_local_top", offsetof(struct stack_info, local_top));
  field("Stack_local_limit", offsetof(struct stack_info, local_limit));

  printf("\n/* struct stack_handler */\n");
  field("Handler_value", offsetof(struct stack_handler, handle_value));
  field("Handler_exception", offsetof(struct stack_handler, handle_exn));
  field("Handler_effect", offsetof(struct stack_handler, handle_effect));
  field("Handler_parent", offsetof(struct stack_handler, parent));

  printf("\n/* struct dynamic_cache_s */\n");
  def("Dynamic_cache", offsetof(dynamic_cache_s, tbl));
  def("Dynamic_binding_size", sizeof(dynamic_binding_s));
  def("Dynamic_binding_var", offsetof(dynamic_binding_s, dyn));
  def("Dynamic_cache_entries", DYNAMIC_CACHE_SIZE);

  printf("\n/* struct c_stack_link (its padding field keeps the C stack"
         "\n   16-aligned in caml_start_program) */\n");
  field("Cstack_stack", offsetof(struct c_stack_link, stack));
  field("Cstack_sp", offsetof(struct c_stack_link, sp));
  field("Cstack_prev", offsetof(struct c_stack_link, prev));
  field("Cstack_async_exn_handler",
      offsetof(struct c_stack_link, async_exn_handler));
  def("SIZEOF_C_STACK_LINK", sizeof(struct c_stack_link));

  return 0;
}
