(* TEST
   compile_only = "true";
   ocamlopt_flags += " -flambda2-join-points -flambda2-join-algorithm=n-way";
   flambda2;
   setup-ocamlopt.byte-build-env;
   ocamlopt.byte with dump-raw, dump-simplify;
   check-fexpr-dump;
 *)

(* This test is making sure that we don't lose information about
   variables not being null when performing a join.
   
   The code is written to make sure it is a situation where not
   knowing the variable is not null would change the code
   generated by simplify. *)

let f bit bit' =
  let c =
    if bit' < 0
    then false
    else (bit > bit')
  in
  (* If we don't know that [c] is necessarily
     [not_null] here, it prevents unboxing. *)
  if c
  then bit <> 0
  else false
