(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/debug.ml *)
(* [oxcaml] = false *)

open! Stdlib

let series = ref None

let stop_profiling () =
  match !series with Some _x -> series := None | None -> ()

let start_profiling name =
  let path = name ^ ".spacetime" in
  stop_profiling ();
  Format.eprintf "Start profiling %s\n%!" path;
  ()

let take_snapshot () =
  match !series with
  | None -> ()
  | Some _series ->
    Gc.minor ();
    ()

let debugs : (string * bool ref) list ref = ref []

let available () = List.map !debugs ~f:fst

let find ?(even_if_quiet = false) s =
  let state =
    match List.string_assoc s !debugs with
    | Some s -> s
    | None ->
      let state = ref false in
      debugs := (s, state) :: !debugs;
      state
  in
  fun () ->
    if String.equal s "times" then take_snapshot ();
    (even_if_quiet || not !Warning.quiet) && !state

let enable s =
  match List.string_assoc s !debugs with
  | Some s -> s := true
  | None -> failwith (Printf.sprintf "The debug named %S doesn't exist" s)

let disable s =
  match List.string_assoc s !debugs with
  | Some s -> s := false
  | None -> failwith (Printf.sprintf "The debug named %S doesn't exist" s)
