(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/debug.mli *)
(* [oxcaml] = false *)

val available : unit -> string list

val find : ?even_if_quiet:bool -> string -> unit -> bool

val enable : string -> unit

val disable : string -> unit

val stop_profiling : unit -> unit

val start_profiling : string -> unit
