(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/int_set.mli *)
(* [oxcaml] = false *)

[@@@ocaml.text
" Persistent sets of non-negative integers.\n\n\
\    The set is a Patricia tree (a binary trie indexed by the bits of\n\
\    the elements, with path compression) whose leaves are small\n\
\    bitmaps. A set of a few elements is just a few small blocks,\n\
\    whatever the elements, and dense sets are packed 32 elements per\n\
\    leaf. Set operations ([union], [inter], [diff], [equal]) work\n\
\    structurally. The interface is a subset of [Set.S] (extended as\n\
\    in {!Stdlib.Set.S}), with the same semantics; in particular, the\n\
\    elements are always visited in increasing order. The only\n\
\    difference is that the elements must be non-negative: [add]\n\
\    raises [Invalid_argument] on a negative one. "]

module type S = sig
  type elt

  type t

  val empty : t

  val is_empty : t -> bool

  val mem : elt -> t -> bool

  val add : elt -> t -> t
  [@@ocaml.doc " Returns the set itself when the element is already present. "]

  val singleton : elt -> t

  val remove : elt -> t -> t
  [@@ocaml.doc " Returns the set itself when the element is not present. "]

  val union : t -> t -> t

  val inter : t -> t -> t

  val diff : t -> t -> t

  val equal : t -> t -> bool

  val compare : t -> t -> int
  [@@ocaml.doc " A total order, compatible with [equal]. "]

  val subset : t -> t -> bool

  val disjoint : t -> t -> bool

  val iter : (elt -> unit) -> t -> unit

  val fold : (elt -> 'a -> 'a) -> t -> 'a -> 'a

  val for_all : (elt -> bool) -> t -> bool

  val exists : (elt -> bool) -> t -> bool

  val filter : (elt -> bool) -> t -> t

  val map : (elt -> elt) -> t -> t

  val cardinal : t -> int

  val elements : t -> elt list

  val min_elt : t -> elt

  val max_elt : t -> elt

  val choose : t -> elt [@@ocaml.doc " Returns the smallest element. "]

  val of_list : elt list -> t

  val to_seq : t -> elt Seq.t

  val compare_cardinal_with : t -> int -> int
  [@@ocaml.doc " [compare_cardinal_with s n] is [compare (cardinal s) n]. "]

  val to_list_bounded : int -> t -> elt list option
  [@@ocaml.doc
    " [to_list_bounded n s] returns [Some (elements s)] if [s] has at\n\
    \      most [n] elements, and [None] otherwise. "]
end

include S with type elt = int
