(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/int_trie.mli *)
(* [oxcaml] = false *)

[@@@ocaml.text
" Persistent maps indexed by non-negative integers.\n\n\
\    The map is a 32-way trie indexed by the bits of the key. A lookup\n\
\    only follows a few pointers (four levels are enough for a million\n\
\    keys), and the bindings of consecutive keys are stored next to\n\
\    each other. This is much faster than a balanced tree when the\n\
\    keys are dense, as the addresses of the blocks of a program.\n\n\
\    The interface is a subset of [Map.S], with the same semantics. In\n\
\    particular, the bindings are always visited in increasing key\n\
\    order. The only difference is that the keys must be non-negative:\n\
\    [add] and [update] raise [Invalid_argument] on a negative key. "]

type key = int

type +'a t

val empty : 'a t

val singleton : key -> 'a -> 'a t

val add : key -> 'a -> 'a t -> 'a t
[@@ocaml.doc
  " Returns the map itself when the key is already bound to the same\n\
  \    (physically equal) value. "]

val remove : key -> 'a t -> 'a t

val update : key -> ('a option -> 'a option) -> 'a t -> 'a t

val find : key -> 'a t -> 'a

val find_opt : key -> 'a t -> 'a option

val mem : key -> 'a t -> bool

val cardinal : 'a t -> int

val is_empty : 'a t -> bool

val choose : 'a t -> key * 'a
[@@ocaml.doc " Returns the binding with the smallest key. "]

val min_binding : 'a t -> key * 'a

val max_binding : 'a t -> key * 'a

val iter : (key -> 'a -> unit) -> 'a t -> unit

val fold : (key -> 'a -> 'b -> 'b) -> 'a t -> 'b -> 'b

val map : ('a -> 'b) -> 'a t -> 'b t

val mapi : (key -> 'a -> 'b) -> 'a t -> 'b t

val filter : (key -> 'a -> bool) -> 'a t -> 'a t

val filter_map : (key -> 'a -> 'b option) -> 'a t -> 'b t

val equal : ('a -> 'a -> bool) -> 'a t -> 'a t -> bool

val bindings : 'a t -> (key * 'a) list

val to_seq : 'a t -> (key * 'a) Seq.t

val to_rev_seq : 'a t -> (key * 'a) Seq.t

val of_seq : (key * 'a) Seq.t -> 'a t
[@@ocaml.doc
  " Builds a map in one go, which is much cheaper than repeatedly\n\
  \    calling [add]. Later bindings take precedence. "]
