(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/reserved.mli *)
(* [oxcaml] = false *)

open Stdlib

val keyword : StringSet.t

val provided : StringSet.t
