(* Generated by [make jsoo-imports]; do not edit. *)
(* Source: external/js_of_ocaml/compiler/lib/targetint.mli *)
(* [oxcaml] = false *)

include Sizable_int.S

val max_i31s : t lazy_t

val min_i31s : t lazy_t

val is_within_i31s : t -> bool
