(subdir build (dynamic_include ../dune_rules/stdlib.dune))

;; We're trying to copy a few files around, but copy_files triggers a bug
;; in dependency cycle detection when in a statically visible dune stanza.
;; So here's a weird workaround, to hide copy_files inside dynamic_include.
;; See https://github.com/ocaml/dune/issues/16516
(subdir copy_workaround
  (rule (target headers.dune) (action (write-file %{target} "(copy_files ../../../runtime/caml/*.{h,tbl})")))
  (rule (target meta.dune) (action (write-file %{target} "(copy_files ../../META)")))
  (rule (target fake_dynlink.dune) (action (write-file %{target} "(rule (target dynlink.cmxa) (action (write-file \%{target} \"\")))"))))
(subdir build/caml (dynamic_include ../../copy_workaround/headers.dune))
(subdir build/stdlib (dynamic_include ../../copy_workaround/meta.dune))
(subdir build/dynlink (dynamic_include ../../copy_workaround/fake_dynlink.dune))

