#!/usr/bin/env bash

#**************************************************************************#
#*                                                                        *#
#*                                 OCaml                                  *#
#*                                                                        *#
#*                    James Rayman, Jane Street, New York                 *#
#*                                                                        *#
#*   Copyright 2025 Jane Street Group LLC                                 *#
#*                                                                        *#
#*   All rights reserved.  This file is distributed under the terms of    *#
#*   the GNU Lesser General Public License version 2.1, with the          *#
#*   special exception on linking described in the file LICENSE.          *#
#*                                                                        *#
#**************************************************************************#

# 80ch.sh: A GitHub-actions-friendly script which finds lines added in the
#          current feature which are longer than 80 characters. To be less
#          annoying, 80ch.sh never fails, but instead emits warnings, and only
#          checks a subset of all files (See SKIP FILES).

set -u

# Use configured opam switch from Makefile.config
repo_root_for_config=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")
if [ -f "$repo_root_for_config/Makefile.config" ]; then
  opam_exec=$(grep '^opam_exec = ' "$repo_root_for_config/Makefile.config" \
    2>/dev/null | cut -d= -f2- | sed 's/^ *//')
fi
opam_exec=${opam_exec:-}

. "$(dirname "$0")/added-lines.sh"

check_line_length() {
  local changed_file="$1"
  local current_line="$2"
  local line_content="$3"
  if [ ${#line_content} -gt 80 ]; then
    printf \
'::error file=%s,line=%s,title=%s::Line %s is too long in %s\n' \
      "$changed_file" "$current_line" \
      'Line is longer than 80 characters' \
      "$current_line" \
      "$changed_file"
  fi
}

should_check_file() {
  local changed_file="$1"

  # This case statement skips a hard-coded set of files.
  case "$changed_file" in
    # Don't check tests for long lines
    # (a more sophisticated script would instead remove %%expect blocks).
    # Don't check files generated by menhir either.
    # Don't check external directory.
    # Don't check generated simd instruction defs.
    # Don't check debug_printers, which needs to have single-line let-bindings.
    testsuite/tests/* | \
    oxcaml/tests/* | \
    external/* | \
    middle_end/flambda2/parser/flambda_parser.ml | \
    middle_end/flambda2/parser/flambda_lex.ml | \
    tools/simdgen/amd64_simd_instrs.ml | \
    tools/debug_printers.ml)
      return 1 ;;
  esac

  # Only check ml, mli, and mly files for long lines
  case "$changed_file" in
    *.ml | *.mli | *.mly) ;;
    *) return 1 ;;
  esac

  # Don't check autoformatted files (there's a bug in `ocamlformat` that
  # sometimes produces lines over 80 characters)
  $opam_exec ocamlformat --print-config "$changed_file" 2>&1 \
  | grep -q disable=false && return 1

  return 0
}

run_added_lines_check should_check_file check_line_length
