(library
 (name windowing)
 (wrapped false)
 (libraries unix)
 (modules (:standard \ coeff_check)))

(executable
 (name coeff_check)
 (modules coeff_check)
 (libraries windowing))

(rule
 (target scale.tbl)
 (deps
  (:platform_scale
   scale.%{ocaml-config:system}.%{ocaml-config:architecture}.tbl))
 (action (copy %{platform_scale} %{target})))

(rule
 (alias runtest)
 (deps scale.tbl)
 (action (run %{dep:coeff_check.exe})))
