(* TEST
 include stdlib_stable;
 include stdlib_upstream_compatible;
 modules = "idx_repr.ml stubs.c";
 bytecode;
*)
(** This is code generated by [test_generation.ml]. *)

[@@@warning "-23"]
type unit_u : void mod everything
external unbox_unit : unit -> unit_u = "%unbox_unit"
external globalize : local_ 'a -> 'a = "%obj_dup";;
let int64x2_u_equal (_ : int64x2#) (_ : int64x2#) = failwith "should not be called from bytecode"

open Stdlib_upstream_compatible
open Stdlib_stable

external[@layout_poly] makearray_dynamic_local :
  ('a : any mod separable) . int -> 'a -> 'a array @ local =
  "%makearray_dynamic"

external[@layout_poly] makearray_dynamic :
  ('a : any mod separable) . int -> 'a -> 'a array =
  "%makearray_dynamic"

external[@layout_poly] get :
  ('a : any mod separable) . ('a array[@local_opt]) -> (int[@local_opt]) -> 'a =
  "%array_safe_get"

external[@layout_poly] set :
  ('a : any mod separable) . ('a array[@local_opt]) -> (int[@local_opt]) -> 'a -> unit =
  "%array_safe_set"

let failwithf fmt = Printf.ksprintf failwith fmt

(* Redefine iter to infer locality *)
let rec iter ~f = function
    [] -> ()
  | a::l -> f a; iter ~f l

module Int_set = Set.Make(Int)

let tests_run = ref Int_set.empty

let mark_test_run test_id =
  tests_run := Int_set.add test_id !tests_run

(* Various interesting values *)

let sizes = [ 0; 1; 2; 30 ]

let indices_in_deepening_tests = [0; 100_000]

type packed = P : 'a -> packed
let ref_to_force_heap_allocation : packed ref = ref (P 0)

type t0 = { mutable a0 : int [@atomic]; mutable b0 : int [@atomic] } (* { int; int } *)
type t1 = { mutable a1 : int [@atomic]; mutable b1 : int [@atomic]; mutable c1 : int [@atomic] } (* { int; int; int } *)
type t2 = #{ a2 : int } (* #{ int } *)
type t3 = { mutable a3 : int [@atomic]; mutable b3 : t2 [@atomic] } (* { int; #{ int } } *)
type t4 = #{ a4 : float } (* #{ float } *)
type t5 = { mutable a5 : int [@atomic]; mutable b5 : t4 [@atomic] } (* { int; #{ float } } *)
type t6 = { mutable a6 : int64 [@atomic] } (* { int64 } *)
type t7 = { mutable a7 : float [@atomic]; mutable b7 : int [@atomic]; mutable c7 : int [@atomic] } (* { float; int; int } *)
type t8 = { mutable a8 : float [@atomic]; mutable b8 : int64 [@atomic] } (* { float; int64 } *)
type t9 = { mutable a9 : float [@atomic]; mutable b9 : float [@atomic]; mutable c9 : int [@atomic] } (* { float; float; int } *)
type v10 = C10_0 of unit_u (* (| unit_u) *)
type t11 = { mutable a11 : float [@atomic]; mutable b11 : v10 [@atomic] } (* { float; (| unit_u) } *)
type t12 = #{ a12 : string } (* #{ string } *)
type t13 = { mutable a13 : string [@atomic]; mutable b13 : t12 [@atomic] } (* { string; #{ string } } *)
type t14 = { mutable a14 : v10 [@atomic]; mutable b14 : int [@atomic] } (* { (| unit_u); int } *)
type t15 = { mutable a15 : t12 [@atomic]; mutable b15 : string [@atomic] } (* { #{ string }; string } *)

let to_run () =
  (*************************)
  (*   t0 = { int; int }   *)
  (*************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a0 r2.a0 && (fun a b -> Int.equal a b) r1.b0 r2.b0) in
  let r = { a0 = 0; b0 = 1 } in
  (* Paths of depth 1 *)
  let next_r = { a0 = 100; b0 = 101 } in
  (* .a0 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a0 = next_r.a0 } in
  Idx_atomic.set r ((.a0) : (t0, _) idx_atomic) next_r.a0;
  mark_test_run 1;
  let test = eq r expected in
  if not test then failwithf "test 1 failed";
  mark_test_run 2;
  let test = sub_eq (Idx_atomic.get r ((.a0) : (t0, _) idx_atomic)) next_r.a0 in
  if not test then failwithf "test 2 failed";
  let r = { a0 = 0; b0 = 1 } in
  (* Paths of depth 1 *)
  let next_r = { a0 = 100; b0 = 101 } in
  (* .b0 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with b0 = next_r.b0 } in
  Idx_atomic.set r ((.b0) : (t0, _) idx_atomic) next_r.b0;
  mark_test_run 3;
  let test = eq r expected in
  if not test then failwithf "test 3 failed";
  mark_test_run 4;
  let test = sub_eq (Idx_atomic.get r ((.b0) : (t0, _) idx_atomic)) next_r.b0 in
  if not test then failwithf "test 4 failed";
  (******************************)
  (*   t1 = { int; int; int }   *)
  (******************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a1 r2.a1 && (fun a b -> Int.equal a b) r1.b1 r2.b1 && (fun a b -> Int.equal a b) r1.c1 r2.c1) in
  let r = { a1 = 0; b1 = 1; c1 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a1 = 100; b1 = 101; c1 = 102 } in
  (* .a1 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a1 = next_r.a1 } in
  Idx_atomic.set r ((.a1) : (t1, _) idx_atomic) next_r.a1;
  mark_test_run 5;
  let test = eq r expected in
  if not test then failwithf "test 5 failed";
  mark_test_run 6;
  let test = sub_eq (Idx_atomic.get r ((.a1) : (t1, _) idx_atomic)) next_r.a1 in
  if not test then failwithf "test 6 failed";
  let r = { a1 = 0; b1 = 1; c1 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a1 = 100; b1 = 101; c1 = 102 } in
  (* .b1 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with b1 = next_r.b1 } in
  Idx_atomic.set r ((.b1) : (t1, _) idx_atomic) next_r.b1;
  mark_test_run 7;
  let test = eq r expected in
  if not test then failwithf "test 7 failed";
  mark_test_run 8;
  let test = sub_eq (Idx_atomic.get r ((.b1) : (t1, _) idx_atomic)) next_r.b1 in
  if not test then failwithf "test 8 failed";
  let r = { a1 = 0; b1 = 1; c1 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a1 = 100; b1 = 101; c1 = 102 } in
  (* .c1 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with c1 = next_r.c1 } in
  Idx_atomic.set r ((.c1) : (t1, _) idx_atomic) next_r.c1;
  mark_test_run 9;
  let test = eq r expected in
  if not test then failwithf "test 9 failed";
  mark_test_run 10;
  let test = sub_eq (Idx_atomic.get r ((.c1) : (t1, _) idx_atomic)) next_r.c1 in
  if not test then failwithf "test 10 failed";
  (******************************)
  (*   t3 = { int; #{ int } }   *)
  (******************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a3 r2.a3 && (fun #{ a2 = a21 } #{ a2 = a22 } -> (fun a b -> Int.equal a b) a21 a22) r1.b3 r2.b3) in
  let r = { a3 = 0; b3 = #{ a2 = 1 } } in
  (* Paths of depth 1 *)
  let next_r = { a3 = 100; b3 = #{ a2 = 101 } } in
  (* .a3 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a3 = next_r.a3 } in
  Idx_atomic.set r ((.a3) : (t3, _) idx_atomic) next_r.a3;
  mark_test_run 11;
  let test = eq r expected in
  if not test then failwithf "test 11 failed";
  mark_test_run 12;
  let test = sub_eq (Idx_atomic.get r ((.a3) : (t3, _) idx_atomic)) next_r.a3 in
  if not test then failwithf "test 12 failed";
  let r = { a3 = 0; b3 = #{ a2 = 1 } } in
  (* Paths of depth 1 *)
  let next_r = { a3 = 100; b3 = #{ a2 = 101 } } in
  (* .b3 *)
  let sub_eq = (fun #{ a2 = a21 } #{ a2 = a22 } -> (fun a b -> Int.equal a b) a21 a22) in
  let expected = { r with b3 = next_r.b3 } in
  Idx_atomic.set r ((.b3) : (t3, _) idx_atomic) next_r.b3;
  mark_test_run 13;
  let test = eq r expected in
  if not test then failwithf "test 13 failed";
  mark_test_run 14;
  let test = sub_eq (Idx_atomic.get r ((.b3) : (t3, _) idx_atomic)) next_r.b3 in
  if not test then failwithf "test 14 failed";
  (* Paths of depth 2 *)
  let next_r = { a3 = 200; b3 = #{ a2 = 201 } } in
  (* .b3.#a2 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with b3 = #{ r.b3 with a2 = next_r.b3.#a2 } } in
  Idx_atomic.set r ((.b3.#a2) : (t3, _) idx_atomic) next_r.b3.#a2;
  mark_test_run 15;
  let test = eq r expected in
  if not test then failwithf "test 15 failed";
  mark_test_run 16;
  let test = sub_eq (Idx_atomic.get r ((.b3.#a2) : (t3, _) idx_atomic)) next_r.b3.#a2 in
  if not test then failwithf "test 16 failed";
  (********************************)
  (*   t5 = { int; #{ float } }   *)
  (********************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a5 r2.a5 && (fun #{ a4 = a41 } #{ a4 = a42 } -> (fun a b -> Float.equal (globalize a) (globalize b)) a41 a42) r1.b5 r2.b5) in
  let r = { a5 = 0; b5 = #{ a4 = 1. } } in
  (* Paths of depth 1 *)
  let next_r = { a5 = 100; b5 = #{ a4 = 101. } } in
  (* .a5 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a5 = next_r.a5 } in
  Idx_atomic.set r ((.a5) : (t5, _) idx_atomic) next_r.a5;
  mark_test_run 17;
  let test = eq r expected in
  if not test then failwithf "test 17 failed";
  mark_test_run 18;
  let test = sub_eq (Idx_atomic.get r ((.a5) : (t5, _) idx_atomic)) next_r.a5 in
  if not test then failwithf "test 18 failed";
  let r = { a5 = 0; b5 = #{ a4 = 1. } } in
  (* Paths of depth 1 *)
  let next_r = { a5 = 100; b5 = #{ a4 = 101. } } in
  (* .b5 *)
  let sub_eq = (fun #{ a4 = a41 } #{ a4 = a42 } -> (fun a b -> Float.equal (globalize a) (globalize b)) a41 a42) in
  let expected = { r with b5 = next_r.b5 } in
  Idx_atomic.set r ((.b5) : (t5, _) idx_atomic) next_r.b5;
  mark_test_run 19;
  let test = eq r expected in
  if not test then failwithf "test 19 failed";
  mark_test_run 20;
  let test = sub_eq (Idx_atomic.get r ((.b5) : (t5, _) idx_atomic)) next_r.b5 in
  if not test then failwithf "test 20 failed";
  (* Paths of depth 2 *)
  let next_r = { a5 = 200; b5 = #{ a4 = 201. } } in
  (* .b5.#a4 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with b5 = #{ r.b5 with a4 = next_r.b5.#a4 } } in
  Idx_atomic.set r ((.b5.#a4) : (t5, _) idx_atomic) next_r.b5.#a4;
  mark_test_run 21;
  let test = eq r expected in
  if not test then failwithf "test 21 failed";
  mark_test_run 22;
  let test = sub_eq (Idx_atomic.get r ((.b5.#a4) : (t5, _) idx_atomic)) next_r.b5.#a4 in
  if not test then failwithf "test 22 failed";
  (**********************)
  (*   t6 = { int64 }   *)
  (**********************)
  let eq = (fun r1 r2 -> (fun a b -> Int64.equal (globalize a) (globalize b)) r1.a6 r2.a6) in
  let r = { a6 = 0L } in
  (* Paths of depth 1 *)
  let next_r = { a6 = 100L } in
  (* .a6 *)
  let sub_eq = (fun a b -> Int64.equal (globalize a) (globalize b)) in
  let expected = { r with a6 = next_r.a6 } in
  Idx_atomic.set r ((.a6) : (t6, _) idx_atomic) next_r.a6;
  mark_test_run 23;
  let test = eq r expected in
  if not test then failwithf "test 23 failed";
  mark_test_run 24;
  let test = sub_eq (Idx_atomic.get r ((.a6) : (t6, _) idx_atomic)) next_r.a6 in
  if not test then failwithf "test 24 failed";
  (********************************)
  (*   t7 = { float; int; int }   *)
  (********************************)
  let eq = (fun r1 r2 -> (fun a b -> Float.equal (globalize a) (globalize b)) r1.a7 r2.a7 && (fun a b -> Int.equal a b) r1.b7 r2.b7 && (fun a b -> Int.equal a b) r1.c7 r2.c7) in
  let r = { a7 = 0.; b7 = 1; c7 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a7 = 100.; b7 = 101; c7 = 102 } in
  (* .a7 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with a7 = next_r.a7 } in
  Idx_atomic.set r ((.a7) : (t7, _) idx_atomic) next_r.a7;
  mark_test_run 25;
  let test = eq r expected in
  if not test then failwithf "test 25 failed";
  mark_test_run 26;
  let test = sub_eq (Idx_atomic.get r ((.a7) : (t7, _) idx_atomic)) next_r.a7 in
  if not test then failwithf "test 26 failed";
  let r = { a7 = 0.; b7 = 1; c7 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a7 = 100.; b7 = 101; c7 = 102 } in
  (* .b7 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with b7 = next_r.b7 } in
  Idx_atomic.set r ((.b7) : (t7, _) idx_atomic) next_r.b7;
  mark_test_run 27;
  let test = eq r expected in
  if not test then failwithf "test 27 failed";
  mark_test_run 28;
  let test = sub_eq (Idx_atomic.get r ((.b7) : (t7, _) idx_atomic)) next_r.b7 in
  if not test then failwithf "test 28 failed";
  let r = { a7 = 0.; b7 = 1; c7 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a7 = 100.; b7 = 101; c7 = 102 } in
  (* .c7 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with c7 = next_r.c7 } in
  Idx_atomic.set r ((.c7) : (t7, _) idx_atomic) next_r.c7;
  mark_test_run 29;
  let test = eq r expected in
  if not test then failwithf "test 29 failed";
  mark_test_run 30;
  let test = sub_eq (Idx_atomic.get r ((.c7) : (t7, _) idx_atomic)) next_r.c7 in
  if not test then failwithf "test 30 failed";
  (*****************************)
  (*   t8 = { float; int64 }   *)
  (*****************************)
  let eq = (fun r1 r2 -> (fun a b -> Float.equal (globalize a) (globalize b)) r1.a8 r2.a8 && (fun a b -> Int64.equal (globalize a) (globalize b)) r1.b8 r2.b8) in
  let r = { a8 = 0.; b8 = 1L } in
  (* Paths of depth 1 *)
  let next_r = { a8 = 100.; b8 = 101L } in
  (* .a8 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with a8 = next_r.a8 } in
  Idx_atomic.set r ((.a8) : (t8, _) idx_atomic) next_r.a8;
  mark_test_run 31;
  let test = eq r expected in
  if not test then failwithf "test 31 failed";
  mark_test_run 32;
  let test = sub_eq (Idx_atomic.get r ((.a8) : (t8, _) idx_atomic)) next_r.a8 in
  if not test then failwithf "test 32 failed";
  let r = { a8 = 0.; b8 = 1L } in
  (* Paths of depth 1 *)
  let next_r = { a8 = 100.; b8 = 101L } in
  (* .b8 *)
  let sub_eq = (fun a b -> Int64.equal (globalize a) (globalize b)) in
  let expected = { r with b8 = next_r.b8 } in
  Idx_atomic.set r ((.b8) : (t8, _) idx_atomic) next_r.b8;
  mark_test_run 33;
  let test = eq r expected in
  if not test then failwithf "test 33 failed";
  mark_test_run 34;
  let test = sub_eq (Idx_atomic.get r ((.b8) : (t8, _) idx_atomic)) next_r.b8 in
  if not test then failwithf "test 34 failed";
  (**********************************)
  (*   t9 = { float; float; int }   *)
  (**********************************)
  let eq = (fun r1 r2 -> (fun a b -> Float.equal (globalize a) (globalize b)) r1.a9 r2.a9 && (fun a b -> Float.equal (globalize a) (globalize b)) r1.b9 r2.b9 && (fun a b -> Int.equal a b) r1.c9 r2.c9) in
  let r = { a9 = 0.; b9 = 1.; c9 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a9 = 100.; b9 = 101.; c9 = 102 } in
  (* .a9 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with a9 = next_r.a9 } in
  Idx_atomic.set r ((.a9) : (t9, _) idx_atomic) next_r.a9;
  mark_test_run 35;
  let test = eq r expected in
  if not test then failwithf "test 35 failed";
  mark_test_run 36;
  let test = sub_eq (Idx_atomic.get r ((.a9) : (t9, _) idx_atomic)) next_r.a9 in
  if not test then failwithf "test 36 failed";
  let r = { a9 = 0.; b9 = 1.; c9 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a9 = 100.; b9 = 101.; c9 = 102 } in
  (* .b9 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with b9 = next_r.b9 } in
  Idx_atomic.set r ((.b9) : (t9, _) idx_atomic) next_r.b9;
  mark_test_run 37;
  let test = eq r expected in
  if not test then failwithf "test 37 failed";
  mark_test_run 38;
  let test = sub_eq (Idx_atomic.get r ((.b9) : (t9, _) idx_atomic)) next_r.b9 in
  if not test then failwithf "test 38 failed";
  let r = { a9 = 0.; b9 = 1.; c9 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a9 = 100.; b9 = 101.; c9 = 102 } in
  (* .c9 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with c9 = next_r.c9 } in
  Idx_atomic.set r ((.c9) : (t9, _) idx_atomic) next_r.c9;
  mark_test_run 39;
  let test = eq r expected in
  if not test then failwithf "test 39 failed";
  mark_test_run 40;
  let test = sub_eq (Idx_atomic.get r ((.c9) : (t9, _) idx_atomic)) next_r.c9 in
  if not test then failwithf "test 40 failed";
  (***********************************)
  (*   t11 = { float; (| unit_u) }   *)
  (***********************************)
  let eq = (fun r1 r2 -> (fun a b -> Float.equal (globalize a) (globalize b)) r1.a11 r2.a11 && (fun a b -> match a, b with C10_0(a0), C10_0(b0) -> (fun _ _ -> true) a0 b0) r1.b11 r2.b11) in
  let r = { a11 = 0.; b11 = (C10_0 (unbox_unit ())) } in
  (* Paths of depth 1 *)
  let next_r = { a11 = 100.; b11 = (C10_0 (unbox_unit ())) } in
  (* .a11 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with a11 = next_r.a11 } in
  Idx_atomic.set r ((.a11) : (t11, _) idx_atomic) next_r.a11;
  mark_test_run 41;
  let test = eq r expected in
  if not test then failwithf "test 41 failed";
  mark_test_run 42;
  let test = sub_eq (Idx_atomic.get r ((.a11) : (t11, _) idx_atomic)) next_r.a11 in
  if not test then failwithf "test 42 failed";
  let r = { a11 = 0.; b11 = (C10_0 (unbox_unit ())) } in
  (* Paths of depth 1 *)
  let next_r = { a11 = 100.; b11 = (C10_0 (unbox_unit ())) } in
  (* .b11 *)
  let sub_eq = (fun a b -> match a, b with C10_0(a0), C10_0(b0) -> (fun _ _ -> true) a0 b0) in
  let expected = { r with b11 = next_r.b11 } in
  Idx_atomic.set r ((.b11) : (t11, _) idx_atomic) next_r.b11;
  mark_test_run 43;
  let test = eq r expected in
  if not test then failwithf "test 43 failed";
  mark_test_run 44;
  let test = sub_eq (Idx_atomic.get r ((.b11) : (t11, _) idx_atomic)) next_r.b11 in
  if not test then failwithf "test 44 failed";
  (*************************************)
  (*   t13 = { string; #{ string } }   *)
  (*************************************)
  let eq = (fun r1 r2 -> (fun a b -> String.equal (globalize a) (globalize b)) r1.a13 r2.a13 && (fun #{ a12 = a121 } #{ a12 = a122 } -> (fun a b -> String.equal (globalize a) (globalize b)) a121 a122) r1.b13 r2.b13) in
  let r = { a13 = "0"; b13 = #{ a12 = "1" } } in
  (* Paths of depth 1 *)
  let next_r = { a13 = "100"; b13 = #{ a12 = "101" } } in
  (* .a13 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with a13 = next_r.a13 } in
  Idx_atomic.set r ((.a13) : (t13, _) idx_atomic) next_r.a13;
  mark_test_run 45;
  let test = eq r expected in
  if not test then failwithf "test 45 failed";
  mark_test_run 46;
  let test = sub_eq (Idx_atomic.get r ((.a13) : (t13, _) idx_atomic)) next_r.a13 in
  if not test then failwithf "test 46 failed";
  let r = { a13 = "0"; b13 = #{ a12 = "1" } } in
  (* Paths of depth 1 *)
  let next_r = { a13 = "100"; b13 = #{ a12 = "101" } } in
  (* .b13 *)
  let sub_eq = (fun #{ a12 = a121 } #{ a12 = a122 } -> (fun a b -> String.equal (globalize a) (globalize b)) a121 a122) in
  let expected = { r with b13 = next_r.b13 } in
  Idx_atomic.set r ((.b13) : (t13, _) idx_atomic) next_r.b13;
  mark_test_run 47;
  let test = eq r expected in
  if not test then failwithf "test 47 failed";
  mark_test_run 48;
  let test = sub_eq (Idx_atomic.get r ((.b13) : (t13, _) idx_atomic)) next_r.b13 in
  if not test then failwithf "test 48 failed";
  (* Paths of depth 2 *)
  let next_r = { a13 = "200"; b13 = #{ a12 = "201" } } in
  (* .b13.#a12 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with b13 = #{ r.b13 with a12 = next_r.b13.#a12 } } in
  Idx_atomic.set r ((.b13.#a12) : (t13, _) idx_atomic) next_r.b13.#a12;
  mark_test_run 49;
  let test = eq r expected in
  if not test then failwithf "test 49 failed";
  mark_test_run 50;
  let test = sub_eq (Idx_atomic.get r ((.b13.#a12) : (t13, _) idx_atomic)) next_r.b13.#a12 in
  if not test then failwithf "test 50 failed";
  (*********************************)
  (*   t14 = { (| unit_u); int }   *)
  (*********************************)
  let eq = (fun r1 r2 -> (fun a b -> match a, b with C10_0(a0), C10_0(b0) -> (fun _ _ -> true) a0 b0) r1.a14 r2.a14 && (fun a b -> Int.equal a b) r1.b14 r2.b14) in
  let r = { a14 = (C10_0 (unbox_unit ())); b14 = 0 } in
  (* Paths of depth 1 *)
  let next_r = { a14 = (C10_0 (unbox_unit ())); b14 = 100 } in
  (* .a14 *)
  let sub_eq = (fun a b -> match a, b with C10_0(a0), C10_0(b0) -> (fun _ _ -> true) a0 b0) in
  let expected = { r with a14 = next_r.a14 } in
  Idx_atomic.set r ((.a14) : (t14, _) idx_atomic) next_r.a14;
  mark_test_run 51;
  let test = eq r expected in
  if not test then failwithf "test 51 failed";
  mark_test_run 52;
  let test = sub_eq (Idx_atomic.get r ((.a14) : (t14, _) idx_atomic)) next_r.a14 in
  if not test then failwithf "test 52 failed";
  let r = { a14 = (C10_0 (unbox_unit ())); b14 = 0 } in
  (* Paths of depth 1 *)
  let next_r = { a14 = (C10_0 (unbox_unit ())); b14 = 100 } in
  (* .b14 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with b14 = next_r.b14 } in
  Idx_atomic.set r ((.b14) : (t14, _) idx_atomic) next_r.b14;
  mark_test_run 53;
  let test = eq r expected in
  if not test then failwithf "test 53 failed";
  mark_test_run 54;
  let test = sub_eq (Idx_atomic.get r ((.b14) : (t14, _) idx_atomic)) next_r.b14 in
  if not test then failwithf "test 54 failed";
  (*************************************)
  (*   t15 = { #{ string }; string }   *)
  (*************************************)
  let eq = (fun r1 r2 -> (fun #{ a12 = a121 } #{ a12 = a122 } -> (fun a b -> String.equal (globalize a) (globalize b)) a121 a122) r1.a15 r2.a15 && (fun a b -> String.equal (globalize a) (globalize b)) r1.b15 r2.b15) in
  let r = { a15 = #{ a12 = "0" }; b15 = "1" } in
  (* Paths of depth 1 *)
  let next_r = { a15 = #{ a12 = "100" }; b15 = "101" } in
  (* .a15 *)
  let sub_eq = (fun #{ a12 = a121 } #{ a12 = a122 } -> (fun a b -> String.equal (globalize a) (globalize b)) a121 a122) in
  let expected = { r with a15 = next_r.a15 } in
  Idx_atomic.set r ((.a15) : (t15, _) idx_atomic) next_r.a15;
  mark_test_run 55;
  let test = eq r expected in
  if not test then failwithf "test 55 failed";
  mark_test_run 56;
  let test = sub_eq (Idx_atomic.get r ((.a15) : (t15, _) idx_atomic)) next_r.a15 in
  if not test then failwithf "test 56 failed";
  (* Paths of depth 2 *)
  let next_r = { a15 = #{ a12 = "200" }; b15 = "201" } in
  (* .a15.#a12 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with a15 = #{ r.a15 with a12 = next_r.a15.#a12 } } in
  Idx_atomic.set r ((.a15.#a12) : (t15, _) idx_atomic) next_r.a15.#a12;
  mark_test_run 57;
  let test = eq r expected in
  if not test then failwithf "test 57 failed";
  mark_test_run 58;
  let test = sub_eq (Idx_atomic.get r ((.a15.#a12) : (t15, _) idx_atomic)) next_r.a15.#a12 in
  if not test then failwithf "test 58 failed";
  let r = { a15 = #{ a12 = "0" }; b15 = "1" } in
  (* Paths of depth 1 *)
  let next_r = { a15 = #{ a12 = "100" }; b15 = "101" } in
  (* .b15 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with b15 = next_r.b15 } in
  Idx_atomic.set r ((.b15) : (t15, _) idx_atomic) next_r.b15;
  mark_test_run 59;
  let test = eq r expected in
  if not test then failwithf "test 59 failed";
  mark_test_run 60;
  let test = sub_eq (Idx_atomic.get r ((.b15) : (t15, _) idx_atomic)) next_r.b15 in
  if not test then failwithf "test 60 failed";
  ()
;;
let () = to_run ();;

for i = 1 to 60 do
  if not (Int_set.mem i !tests_run) then failwithf "test %d not run" i
done;;
let () = Printf.printf "All tests passed.%!\n";;
