(* TEST
 include stdlib_stable;
 include stdlib_upstream_compatible;
 modules = "idx_repr.ml stubs.c";
 bytecode;
*)
(** This is code generated by [test_generation.ml]. *)

[@@@warning "-23"]
type unit_u : void mod everything
external unbox_unit : unit -> unit_u = "%unbox_unit"
external globalize : local_ 'a -> 'a = "%obj_dup";;
let int64x2_u_equal (_ : int64x2#) (_ : int64x2#) = failwith "should not be called from bytecode"

open Stdlib_upstream_compatible
open Stdlib_stable

external[@layout_poly] makearray_dynamic_local :
  ('a : any mod separable) . int -> 'a -> 'a array @ local =
  "%makearray_dynamic"

external[@layout_poly] makearray_dynamic :
  ('a : any mod separable) . int -> 'a -> 'a array =
  "%makearray_dynamic"

external[@layout_poly] get :
  ('a : any mod separable) . ('a array[@local_opt]) -> (int[@local_opt]) -> 'a =
  "%array_safe_get"

external[@layout_poly] set :
  ('a : any mod separable) . ('a array[@local_opt]) -> (int[@local_opt]) -> 'a -> unit =
  "%array_safe_set"

let failwithf fmt = Printf.ksprintf failwith fmt

(* Redefine iter to infer locality *)
let rec iter ~f = function
    [] -> ()
  | a::l -> f a; iter ~f l

module Int_set = Set.Make(Int)

let tests_run = ref Int_set.empty

let mark_test_run test_id =
  tests_run := Int_set.add test_id !tests_run

(* Various interesting values *)

let sizes = [ 0; 1; 2; 30 ]

let indices_in_deepening_tests = [0; 100_000]

type packed = P : 'a -> packed
let ref_to_force_heap_allocation : packed ref = ref (P 0)

type t0 = { mutable a0 : int [@atomic] } (* { int } *)
type t1 = { mutable a1 : int [@atomic]; mutable b1 : int [@atomic] } (* { int; int } *)
type t2 = { mutable a2 : int [@atomic]; mutable b2 : int64 [@atomic] } (* { int; int64 } *)
type v3 = C3_0 of unit_u (* (| unit_u) *)
type t4 = { mutable a4 : int [@atomic]; mutable b4 : v3 [@atomic] } (* { int; (| unit_u) } *)
type t5 = { mutable a5 : int64 [@atomic]; mutable b5 : float [@atomic] } (* { int64; float } *)
type t6 = { mutable a6 : float [@atomic]; mutable b6 : float [@atomic]; mutable c6 : int [@atomic] } (* { float; float; int } *)
type t7 = { mutable a7 : string [@atomic]; mutable b7 : string [@atomic] } (* { string; string } *)
type t8 = { mutable a8 : string [@atomic]; mutable b8 : string [@atomic]; mutable c8 : string [@atomic] } (* { string; string; string } *)
type t9 = #{ a9 : int } (* #{ int } *)
type t10 = { mutable a10 : t9 [@atomic] } (* { #{ int } } *)
type t11 = #{ a11 : string } (* #{ string } *)
type t12 = { mutable a12 : t11 [@atomic] } (* { #{ string } } *)
type t13 = { mutable a13 : t11 [@atomic]; mutable b13 : string [@atomic] } (* { #{ string }; string } *)

let to_run () =
  (********************)
  (*   t0 = { int }   *)
  (********************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a0 r2.a0) in
  let r = { a0 = 0 } in
  (* Paths of depth 1 *)
  let next_r = { a0 = 100 } in
  (* .a0 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a0 = next_r.a0 } in
  Idx_atomic.set r ((.a0) : (t0, _) idx_atomic) next_r.a0;
  mark_test_run 1;
  let test = eq r expected in
  if not test then failwithf "test 1 failed";
  mark_test_run 2;
  let test = sub_eq (Idx_atomic.get r ((.a0) : (t0, _) idx_atomic)) next_r.a0 in
  if not test then failwithf "test 2 failed";
  (*************************)
  (*   t1 = { int; int }   *)
  (*************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a1 r2.a1 && (fun a b -> Int.equal a b) r1.b1 r2.b1) in
  let r = { a1 = 0; b1 = 1 } in
  (* Paths of depth 1 *)
  let next_r = { a1 = 100; b1 = 101 } in
  (* .a1 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a1 = next_r.a1 } in
  Idx_atomic.set r ((.a1) : (t1, _) idx_atomic) next_r.a1;
  mark_test_run 3;
  let test = eq r expected in
  if not test then failwithf "test 3 failed";
  mark_test_run 4;
  let test = sub_eq (Idx_atomic.get r ((.a1) : (t1, _) idx_atomic)) next_r.a1 in
  if not test then failwithf "test 4 failed";
  let r = { a1 = 0; b1 = 1 } in
  (* Paths of depth 1 *)
  let next_r = { a1 = 100; b1 = 101 } in
  (* .b1 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with b1 = next_r.b1 } in
  Idx_atomic.set r ((.b1) : (t1, _) idx_atomic) next_r.b1;
  mark_test_run 5;
  let test = eq r expected in
  if not test then failwithf "test 5 failed";
  mark_test_run 6;
  let test = sub_eq (Idx_atomic.get r ((.b1) : (t1, _) idx_atomic)) next_r.b1 in
  if not test then failwithf "test 6 failed";
  (***************************)
  (*   t2 = { int; int64 }   *)
  (***************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a2 r2.a2 && (fun a b -> Int64.equal (globalize a) (globalize b)) r1.b2 r2.b2) in
  let r = { a2 = 0; b2 = 1L } in
  (* Paths of depth 1 *)
  let next_r = { a2 = 100; b2 = 101L } in
  (* .a2 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a2 = next_r.a2 } in
  Idx_atomic.set r ((.a2) : (t2, _) idx_atomic) next_r.a2;
  mark_test_run 7;
  let test = eq r expected in
  if not test then failwithf "test 7 failed";
  mark_test_run 8;
  let test = sub_eq (Idx_atomic.get r ((.a2) : (t2, _) idx_atomic)) next_r.a2 in
  if not test then failwithf "test 8 failed";
  let r = { a2 = 0; b2 = 1L } in
  (* Paths of depth 1 *)
  let next_r = { a2 = 100; b2 = 101L } in
  (* .b2 *)
  let sub_eq = (fun a b -> Int64.equal (globalize a) (globalize b)) in
  let expected = { r with b2 = next_r.b2 } in
  Idx_atomic.set r ((.b2) : (t2, _) idx_atomic) next_r.b2;
  mark_test_run 9;
  let test = eq r expected in
  if not test then failwithf "test 9 failed";
  mark_test_run 10;
  let test = sub_eq (Idx_atomic.get r ((.b2) : (t2, _) idx_atomic)) next_r.b2 in
  if not test then failwithf "test 10 failed";
  (********************************)
  (*   t4 = { int; (| unit_u) }   *)
  (********************************)
  let eq = (fun r1 r2 -> (fun a b -> Int.equal a b) r1.a4 r2.a4 && (fun a b -> match a, b with C3_0(a0), C3_0(b0) -> (fun _ _ -> true) a0 b0) r1.b4 r2.b4) in
  let r = { a4 = 0; b4 = (C3_0 (unbox_unit ())) } in
  (* Paths of depth 1 *)
  let next_r = { a4 = 100; b4 = (C3_0 (unbox_unit ())) } in
  (* .a4 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a4 = next_r.a4 } in
  Idx_atomic.set r ((.a4) : (t4, _) idx_atomic) next_r.a4;
  mark_test_run 11;
  let test = eq r expected in
  if not test then failwithf "test 11 failed";
  mark_test_run 12;
  let test = sub_eq (Idx_atomic.get r ((.a4) : (t4, _) idx_atomic)) next_r.a4 in
  if not test then failwithf "test 12 failed";
  let r = { a4 = 0; b4 = (C3_0 (unbox_unit ())) } in
  (* Paths of depth 1 *)
  let next_r = { a4 = 100; b4 = (C3_0 (unbox_unit ())) } in
  (* .b4 *)
  let sub_eq = (fun a b -> match a, b with C3_0(a0), C3_0(b0) -> (fun _ _ -> true) a0 b0) in
  let expected = { r with b4 = next_r.b4 } in
  Idx_atomic.set r ((.b4) : (t4, _) idx_atomic) next_r.b4;
  mark_test_run 13;
  let test = eq r expected in
  if not test then failwithf "test 13 failed";
  mark_test_run 14;
  let test = sub_eq (Idx_atomic.get r ((.b4) : (t4, _) idx_atomic)) next_r.b4 in
  if not test then failwithf "test 14 failed";
  (*****************************)
  (*   t5 = { int64; float }   *)
  (*****************************)
  let eq = (fun r1 r2 -> (fun a b -> Int64.equal (globalize a) (globalize b)) r1.a5 r2.a5 && (fun a b -> Float.equal (globalize a) (globalize b)) r1.b5 r2.b5) in
  let r = { a5 = 0L; b5 = 1. } in
  (* Paths of depth 1 *)
  let next_r = { a5 = 100L; b5 = 101. } in
  (* .a5 *)
  let sub_eq = (fun a b -> Int64.equal (globalize a) (globalize b)) in
  let expected = { r with a5 = next_r.a5 } in
  Idx_atomic.set r ((.a5) : (t5, _) idx_atomic) next_r.a5;
  mark_test_run 15;
  let test = eq r expected in
  if not test then failwithf "test 15 failed";
  mark_test_run 16;
  let test = sub_eq (Idx_atomic.get r ((.a5) : (t5, _) idx_atomic)) next_r.a5 in
  if not test then failwithf "test 16 failed";
  let r = { a5 = 0L; b5 = 1. } in
  (* Paths of depth 1 *)
  let next_r = { a5 = 100L; b5 = 101. } in
  (* .b5 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with b5 = next_r.b5 } in
  Idx_atomic.set r ((.b5) : (t5, _) idx_atomic) next_r.b5;
  mark_test_run 17;
  let test = eq r expected in
  if not test then failwithf "test 17 failed";
  mark_test_run 18;
  let test = sub_eq (Idx_atomic.get r ((.b5) : (t5, _) idx_atomic)) next_r.b5 in
  if not test then failwithf "test 18 failed";
  (**********************************)
  (*   t6 = { float; float; int }   *)
  (**********************************)
  let eq = (fun r1 r2 -> (fun a b -> Float.equal (globalize a) (globalize b)) r1.a6 r2.a6 && (fun a b -> Float.equal (globalize a) (globalize b)) r1.b6 r2.b6 && (fun a b -> Int.equal a b) r1.c6 r2.c6) in
  let r = { a6 = 0.; b6 = 1.; c6 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a6 = 100.; b6 = 101.; c6 = 102 } in
  (* .a6 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with a6 = next_r.a6 } in
  Idx_atomic.set r ((.a6) : (t6, _) idx_atomic) next_r.a6;
  mark_test_run 19;
  let test = eq r expected in
  if not test then failwithf "test 19 failed";
  mark_test_run 20;
  let test = sub_eq (Idx_atomic.get r ((.a6) : (t6, _) idx_atomic)) next_r.a6 in
  if not test then failwithf "test 20 failed";
  let r = { a6 = 0.; b6 = 1.; c6 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a6 = 100.; b6 = 101.; c6 = 102 } in
  (* .b6 *)
  let sub_eq = (fun a b -> Float.equal (globalize a) (globalize b)) in
  let expected = { r with b6 = next_r.b6 } in
  Idx_atomic.set r ((.b6) : (t6, _) idx_atomic) next_r.b6;
  mark_test_run 21;
  let test = eq r expected in
  if not test then failwithf "test 21 failed";
  mark_test_run 22;
  let test = sub_eq (Idx_atomic.get r ((.b6) : (t6, _) idx_atomic)) next_r.b6 in
  if not test then failwithf "test 22 failed";
  let r = { a6 = 0.; b6 = 1.; c6 = 2 } in
  (* Paths of depth 1 *)
  let next_r = { a6 = 100.; b6 = 101.; c6 = 102 } in
  (* .c6 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with c6 = next_r.c6 } in
  Idx_atomic.set r ((.c6) : (t6, _) idx_atomic) next_r.c6;
  mark_test_run 23;
  let test = eq r expected in
  if not test then failwithf "test 23 failed";
  mark_test_run 24;
  let test = sub_eq (Idx_atomic.get r ((.c6) : (t6, _) idx_atomic)) next_r.c6 in
  if not test then failwithf "test 24 failed";
  (*******************************)
  (*   t7 = { string; string }   *)
  (*******************************)
  let eq = (fun r1 r2 -> (fun a b -> String.equal (globalize a) (globalize b)) r1.a7 r2.a7 && (fun a b -> String.equal (globalize a) (globalize b)) r1.b7 r2.b7) in
  let r = { a7 = "0"; b7 = "1" } in
  (* Paths of depth 1 *)
  let next_r = { a7 = "100"; b7 = "101" } in
  (* .a7 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with a7 = next_r.a7 } in
  Idx_atomic.set r ((.a7) : (t7, _) idx_atomic) next_r.a7;
  mark_test_run 25;
  let test = eq r expected in
  if not test then failwithf "test 25 failed";
  mark_test_run 26;
  let test = sub_eq (Idx_atomic.get r ((.a7) : (t7, _) idx_atomic)) next_r.a7 in
  if not test then failwithf "test 26 failed";
  let r = { a7 = "0"; b7 = "1" } in
  (* Paths of depth 1 *)
  let next_r = { a7 = "100"; b7 = "101" } in
  (* .b7 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with b7 = next_r.b7 } in
  Idx_atomic.set r ((.b7) : (t7, _) idx_atomic) next_r.b7;
  mark_test_run 27;
  let test = eq r expected in
  if not test then failwithf "test 27 failed";
  mark_test_run 28;
  let test = sub_eq (Idx_atomic.get r ((.b7) : (t7, _) idx_atomic)) next_r.b7 in
  if not test then failwithf "test 28 failed";
  (***************************************)
  (*   t8 = { string; string; string }   *)
  (***************************************)
  let eq = (fun r1 r2 -> (fun a b -> String.equal (globalize a) (globalize b)) r1.a8 r2.a8 && (fun a b -> String.equal (globalize a) (globalize b)) r1.b8 r2.b8 && (fun a b -> String.equal (globalize a) (globalize b)) r1.c8 r2.c8) in
  let r = { a8 = "0"; b8 = "1"; c8 = "2" } in
  (* Paths of depth 1 *)
  let next_r = { a8 = "100"; b8 = "101"; c8 = "102" } in
  (* .a8 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with a8 = next_r.a8 } in
  Idx_atomic.set r ((.a8) : (t8, _) idx_atomic) next_r.a8;
  mark_test_run 29;
  let test = eq r expected in
  if not test then failwithf "test 29 failed";
  mark_test_run 30;
  let test = sub_eq (Idx_atomic.get r ((.a8) : (t8, _) idx_atomic)) next_r.a8 in
  if not test then failwithf "test 30 failed";
  let r = { a8 = "0"; b8 = "1"; c8 = "2" } in
  (* Paths of depth 1 *)
  let next_r = { a8 = "100"; b8 = "101"; c8 = "102" } in
  (* .b8 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with b8 = next_r.b8 } in
  Idx_atomic.set r ((.b8) : (t8, _) idx_atomic) next_r.b8;
  mark_test_run 31;
  let test = eq r expected in
  if not test then failwithf "test 31 failed";
  mark_test_run 32;
  let test = sub_eq (Idx_atomic.get r ((.b8) : (t8, _) idx_atomic)) next_r.b8 in
  if not test then failwithf "test 32 failed";
  let r = { a8 = "0"; b8 = "1"; c8 = "2" } in
  (* Paths of depth 1 *)
  let next_r = { a8 = "100"; b8 = "101"; c8 = "102" } in
  (* .c8 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with c8 = next_r.c8 } in
  Idx_atomic.set r ((.c8) : (t8, _) idx_atomic) next_r.c8;
  mark_test_run 33;
  let test = eq r expected in
  if not test then failwithf "test 33 failed";
  mark_test_run 34;
  let test = sub_eq (Idx_atomic.get r ((.c8) : (t8, _) idx_atomic)) next_r.c8 in
  if not test then failwithf "test 34 failed";
  (**************************)
  (*   t10 = { #{ int } }   *)
  (**************************)
  let eq = (fun r1 r2 -> (fun #{ a9 = a91 } #{ a9 = a92 } -> (fun a b -> Int.equal a b) a91 a92) r1.a10 r2.a10) in
  let r = { a10 = #{ a9 = 0 } } in
  (* Paths of depth 1 *)
  let next_r = { a10 = #{ a9 = 100 } } in
  (* .a10 *)
  let sub_eq = (fun #{ a9 = a91 } #{ a9 = a92 } -> (fun a b -> Int.equal a b) a91 a92) in
  let expected = { r with a10 = next_r.a10 } in
  Idx_atomic.set r ((.a10) : (t10, _) idx_atomic) next_r.a10;
  mark_test_run 35;
  let test = eq r expected in
  if not test then failwithf "test 35 failed";
  mark_test_run 36;
  let test = sub_eq (Idx_atomic.get r ((.a10) : (t10, _) idx_atomic)) next_r.a10 in
  if not test then failwithf "test 36 failed";
  (* Paths of depth 2 *)
  let next_r = { a10 = #{ a9 = 200 } } in
  (* .a10.#a9 *)
  let sub_eq = (fun a b -> Int.equal a b) in
  let expected = { r with a10 = #{ r.a10 with a9 = next_r.a10.#a9 } } in
  Idx_atomic.set r ((.a10.#a9) : (t10, _) idx_atomic) next_r.a10.#a9;
  mark_test_run 37;
  let test = eq r expected in
  if not test then failwithf "test 37 failed";
  mark_test_run 38;
  let test = sub_eq (Idx_atomic.get r ((.a10.#a9) : (t10, _) idx_atomic)) next_r.a10.#a9 in
  if not test then failwithf "test 38 failed";
  (*****************************)
  (*   t12 = { #{ string } }   *)
  (*****************************)
  let eq = (fun r1 r2 -> (fun #{ a11 = a111 } #{ a11 = a112 } -> (fun a b -> String.equal (globalize a) (globalize b)) a111 a112) r1.a12 r2.a12) in
  let r = { a12 = #{ a11 = "0" } } in
  (* Paths of depth 1 *)
  let next_r = { a12 = #{ a11 = "100" } } in
  (* .a12 *)
  let sub_eq = (fun #{ a11 = a111 } #{ a11 = a112 } -> (fun a b -> String.equal (globalize a) (globalize b)) a111 a112) in
  let expected = { r with a12 = next_r.a12 } in
  Idx_atomic.set r ((.a12) : (t12, _) idx_atomic) next_r.a12;
  mark_test_run 39;
  let test = eq r expected in
  if not test then failwithf "test 39 failed";
  mark_test_run 40;
  let test = sub_eq (Idx_atomic.get r ((.a12) : (t12, _) idx_atomic)) next_r.a12 in
  if not test then failwithf "test 40 failed";
  (* Paths of depth 2 *)
  let next_r = { a12 = #{ a11 = "200" } } in
  (* .a12.#a11 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with a12 = #{ r.a12 with a11 = next_r.a12.#a11 } } in
  Idx_atomic.set r ((.a12.#a11) : (t12, _) idx_atomic) next_r.a12.#a11;
  mark_test_run 41;
  let test = eq r expected in
  if not test then failwithf "test 41 failed";
  mark_test_run 42;
  let test = sub_eq (Idx_atomic.get r ((.a12.#a11) : (t12, _) idx_atomic)) next_r.a12.#a11 in
  if not test then failwithf "test 42 failed";
  (*************************************)
  (*   t13 = { #{ string }; string }   *)
  (*************************************)
  let eq = (fun r1 r2 -> (fun #{ a11 = a111 } #{ a11 = a112 } -> (fun a b -> String.equal (globalize a) (globalize b)) a111 a112) r1.a13 r2.a13 && (fun a b -> String.equal (globalize a) (globalize b)) r1.b13 r2.b13) in
  let r = { a13 = #{ a11 = "0" }; b13 = "1" } in
  (* Paths of depth 1 *)
  let next_r = { a13 = #{ a11 = "100" }; b13 = "101" } in
  (* .a13 *)
  let sub_eq = (fun #{ a11 = a111 } #{ a11 = a112 } -> (fun a b -> String.equal (globalize a) (globalize b)) a111 a112) in
  let expected = { r with a13 = next_r.a13 } in
  Idx_atomic.set r ((.a13) : (t13, _) idx_atomic) next_r.a13;
  mark_test_run 43;
  let test = eq r expected in
  if not test then failwithf "test 43 failed";
  mark_test_run 44;
  let test = sub_eq (Idx_atomic.get r ((.a13) : (t13, _) idx_atomic)) next_r.a13 in
  if not test then failwithf "test 44 failed";
  (* Paths of depth 2 *)
  let next_r = { a13 = #{ a11 = "200" }; b13 = "201" } in
  (* .a13.#a11 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with a13 = #{ r.a13 with a11 = next_r.a13.#a11 } } in
  Idx_atomic.set r ((.a13.#a11) : (t13, _) idx_atomic) next_r.a13.#a11;
  mark_test_run 45;
  let test = eq r expected in
  if not test then failwithf "test 45 failed";
  mark_test_run 46;
  let test = sub_eq (Idx_atomic.get r ((.a13.#a11) : (t13, _) idx_atomic)) next_r.a13.#a11 in
  if not test then failwithf "test 46 failed";
  let r = { a13 = #{ a11 = "0" }; b13 = "1" } in
  (* Paths of depth 1 *)
  let next_r = { a13 = #{ a11 = "100" }; b13 = "101" } in
  (* .b13 *)
  let sub_eq = (fun a b -> String.equal (globalize a) (globalize b)) in
  let expected = { r with b13 = next_r.b13 } in
  Idx_atomic.set r ((.b13) : (t13, _) idx_atomic) next_r.b13;
  mark_test_run 47;
  let test = eq r expected in
  if not test then failwithf "test 47 failed";
  mark_test_run 48;
  let test = sub_eq (Idx_atomic.get r ((.b13) : (t13, _) idx_atomic)) next_r.b13 in
  if not test then failwithf "test 48 failed";
  ()
;;
let () = to_run ();;

for i = 1 to 48 do
  if not (Int_set.mem i !tests_run) then failwithf "test %d not run" i
done;;
let () = Printf.printf "All tests passed.%!\n";;
