#!/usr/bin/env python3
import sys

# asyncio.timeout and asyncio.TaskGroup need 3.11.
if sys.version_info < (3, 11):
    raise SystemExit("oxfuzzer: Python 3.11 or newer is required.")

import asyncio
import argparse
import os
from pathlib import Path
import platform
import random
import shlex
import shutil
import signal
import subprocess
import time
from dataclasses import dataclass
from collections.abc import Sequence
import tempfile

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
BUILD_DIR = REPOSITORY_ROOT / "_build/main"

OXFUZZER = BUILD_DIR / "tools/oxfuzzer/oxfuzzer.exe"
OCAMLC = BUILD_DIR / "main_native.exe"
OCAMLOPT = BUILD_DIR / "oxcaml_main_native.exe"

OCAMLLIB = REPOSITORY_ROOT / "_build/runtime_stdlib_install/lib/ocaml_runtime_stdlib"
OCAMLRUN = REPOSITORY_ROOT / "_build/runtime_stdlib_install/bin/ocamlrun"

OTHERLIBS = BUILD_DIR / "otherlibs"
LIBRARIES = ("stdlib_stable", "stdlib_upstream_compatible")

# Flags necessary to import libraries required for compilation of programs
# generated by oxfuzzer.exe. Mirror `libraries` from lib/program.ml.
def library_flags(archive_suffix: str) -> tuple[str, ...]:
    flags: list[str] = []
    for library in LIBRARIES:
        flags += ["-I", str(OTHERLIBS / library / f".{library}.objs/byte")]
        if archive_suffix == "cmxa":
            flags += ["-I", str(OTHERLIBS / library / f".{library}.objs/native")]
    flags += [
        str(OTHERLIBS / library / f"{library}.{archive_suffix}")
        for library in LIBRARIES
    ]
    return tuple(flags)


@dataclass(frozen=True)
class Configuration:
    name: str
    compiler: Path
    flags: tuple[str, ...]


CONFIGURATIONS = [
    # Configuration(
    #     name="ocamlc",
    #     compiler=OCAMLC,
    #     flags=(*library_flags("cma")),
    # ),
    Configuration(
        name="ocamlopt-O4",
        compiler=OCAMLOPT,
        flags=(*library_flags("cmxa"), "-O4"),
    ),
    Configuration(
        name="ocamlopt-Oclassic",
        compiler=OCAMLOPT,
        flags=(*library_flags("cmxa"), "-Oclassic"),
    ),
]

COMPILE_TIMEOUT_SEC = 100.0
RUN_TIMEOUT_SEC = 10.0
GENERATE_TIMEOUT_SEC = 1.0

RATE_SMOOTHING = 0.01
PROGRESS_INTERVAL_SEC = 30.0

# Make sure `make compiler` was run before the fuzzer is executed and that
# all dependencies are available.
def check_dependencies() -> None:
    missing = [
        path
        for path in [OXFUZZER, OCAMLC, OCAMLOPT]
        if not path.is_file() or not os.access(path, os.X_OK)
    ]
    if not OCAMLLIB.is_dir():
        missing.append(OCAMLLIB)
    if not os.access(OCAMLRUN, os.X_OK):
        missing.append(OCAMLRUN)

    if missing:
        formatted = "\n".join(f"  {path}" for path in missing)
        raise SystemExit(f"""oxfuzzer: some dependencies are missing.

Missing files:
{formatted}

From the compiler root, run:
  make compiler
""")

@dataclass(frozen=True)
class CommandResult:
    returncode: int
    stdout: bytes
    stderr: bytes
    timed_out: bool

def kill_process_group(process: asyncio.subprocess.Process) -> None:
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        pass


# stdout and stderr go to <output_prefix>.stdout and <output_prefix>.stderr
# rather than pipes.
async def run_command(
        command: str,
        args: Sequence[str],
        *,
        cwd: Path | None = None,
        env: dict[str, str] | None = None,
        timeout_sec: float,
        output_prefix: Path,
) -> CommandResult:
    stdout_path = output_prefix.with_suffix(".stdout")
    stderr_path = output_prefix.with_suffix(".stderr")
    with open(stdout_path, "wb") as stdout, open(stderr_path, "wb") as stderr:
        process = await asyncio.create_subprocess_exec(
            command,
            *args,
            cwd=cwd,
            env=None if env is None else {**os.environ, **env},
            stdin=asyncio.subprocess.DEVNULL,
            stdout=stdout,
            stderr=stderr,
            # Start new session, so that we can use killpg to reliably kill the
            # command along with all the children it spawned.
            start_new_session=True,
        )

    timed_out = False
    try:
        async with asyncio.timeout(timeout_sec):
            await process.wait()
    except TimeoutError:
        kill_process_group(process)
        await process.wait()
        timed_out = True
    except asyncio.CancelledError:
        # Cancellation does not stop the subprocess, so we kill it manually.
        kill_process_group(process)
        await process.wait()
        raise

    assert process.returncode is not None

    return CommandResult(
        returncode=process.returncode,
        stdout=stdout_path.read_bytes(),
        stderr=stderr_path.read_bytes(),
        timed_out=timed_out,
    )


@dataclass(frozen=True)
class ConfigurationResult:
    configuration: Configuration
    compilation: CommandResult
    execution: CommandResult | None

def compile_command(
    configuration: Configuration, *, source: Path, executable: Path
) -> list[str]:
    return [
        str(configuration.compiler),
        *configuration.flags,
        "-o",
        str(executable),
        str(source),
    ]


async def compile(
    configuration: Configuration,
    *,
    source: Path,
    executable: Path,
) -> CommandResult:
    command = compile_command(configuration, source=source, executable=executable)
    return await run_command(
        command[0],
        command[1:],
        cwd=source.parent,
        env={"OCAMLLIB": str(OCAMLLIB)},
        timeout_sec=COMPILE_TIMEOUT_SEC,
        output_prefix=source.parent / "compile",
    )


async def run(executable: Path) -> CommandResult:
    return await run_command(
        str(executable),
        [],
        cwd=executable.parent,
        timeout_sec=RUN_TIMEOUT_SEC,
        output_prefix=executable.parent / "run",
    )


async def run_configuration(
        configuration: Configuration,
        *,
        program: bytes,
        work_dir: Path,
        slots: asyncio.Semaphore,
) -> ConfigurationResult:
    async with slots:
        work_dir.mkdir(parents=True)
        source = work_dir / "program.ml"
        source.write_bytes(program)
        executable = work_dir / "program.exe"
        compilation = await compile(
            configuration, source=source, executable=executable
        )
        if compilation.timed_out or compilation.returncode != 0:
            return ConfigurationResult(
                configuration=configuration, compilation=compilation, execution=None
            )

        execution = await run(executable)
        return ConfigurationResult(
            configuration=configuration, compilation=compilation, execution=execution
        )

async def generate(seed: int, *, work_dir: Path) -> bytes:
    work_dir.mkdir(parents=True, exist_ok=True)
    result = await run_command(
        str(OXFUZZER),
        ["-seed", str(seed)],
        timeout_sec=GENERATE_TIMEOUT_SEC,
        output_prefix=work_dir / "generate",
    )
    stderr = result.stderr.decode(errors="replace")
    # Generation failing is a fatal error.
    if result.timed_out:
        raise SystemExit(f"generation timed out. seed: {seed}.\n{stderr}")
    if result.returncode != 0:
        raise SystemExit(
            f"generation exited with code {result.returncode}. seed: {seed}.\n"
            f"{stderr}"
        )

    return result.stdout


@dataclass
class Stats:
    """Statistics of a fuzzer's run. Describes how many programs passed, were
    discarded or failed."""
    passed: int = 0
    discarded: int = 0
    failed: int = 0
    last_completion: float | None = None
    smoothed_interval: float | None = None
    last_report: float | None = None

    def record_completion(self) -> None:
        now = time.monotonic()
        if self.last_completion is not None:
            interval = now - self.last_completion
            if self.smoothed_interval is None:
                self.smoothed_interval = interval
            else:
                self.smoothed_interval += RATE_SMOOTHING * (
                    interval - self.smoothed_interval
                )
        self.last_completion = now

    def cases_per_hour(self) -> float | None:
        if not self.smoothed_interval:
            return None
        return 3600 / self.smoothed_interval

    def summary(self) -> str:
        rate = self.cases_per_hour()
        rate_text = "--" if rate is None else f"{rate:,.0f}"
        return (
            f"{self.passed} passed, {self.discarded} discarded, "
            f"{self.failed} failed, {rate_text} cases/h"
        )

    def print_line(self) -> None:
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        print(f"{timestamp} {self.summary()}", file=sys.stderr, flush=True)

    # On a terminal the status is a single line updated in place. Otherwise
    # a timestamped line is printed at most every PROGRESS_INTERVAL_SEC seconds.
    def report(self) -> None:
        self.record_completion()
        if sys.stderr.isatty():
            print(f"\r{self.summary()}", end="", file=sys.stderr, flush=True)
            return
        now = time.monotonic()
        if (
            self.last_report is not None
            and now - self.last_report < PROGRESS_INTERVAL_SEC
        ):
            return
        self.last_report = now
        self.print_line()

    def final_report(self) -> None:
        if sys.stderr.isatty():
            print(file=sys.stderr)
        else:
            self.print_line()


def command_output(command: Sequence[str], *, cwd: Path | None = None) -> str:
    try:
        completed = subprocess.run(
            command, cwd=cwd, capture_output=True, text=True, timeout=30
        )
    except (OSError, subprocess.TimeoutExpired):
        return "unknown"
    if completed.returncode != 0:
        return "unknown"
    return completed.stdout.strip()


def source_revision() -> str:
    # We try to get both the git and hg revision as both may be potentially used.
    revision = command_output(["git", "rev-parse", "HEAD"], cwd=REPOSITORY_ROOT)
    if revision != "unknown":
        dirty = command_output(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=REPOSITORY_ROOT,
        )
        return f"git {revision}{' (dirty)' if dirty else ''}"
    revision = command_output(["hg", "id", "-i"], cwd=REPOSITORY_ROOT)
    if revision != "unknown":
        return f"hg {revision}"  # hg appends '+' itself when dirty.
    return "unknown"


def run_metadata(base_seed: int) -> str:
    lines = [
        f"command: {shlex.join(sys.argv)}",
        f"base seed: {base_seed}",
        f"host: {platform.node()}",
        f"platform: {platform.platform()}",
        f"python: {sys.version.split()[0]}",
        f"source revision: {source_revision()}",
        f"ocamlopt version: {command_output([str(OCAMLOPT), '-version'])}",
        f"ocamlc version: {command_output([str(OCAMLC), '-version'])}",
        f"OCAMLLIB: {OCAMLLIB}",
        f"OCAMLPARAM: {os.environ.get('OCAMLPARAM', '(unset)')}",
        f"OCAMLRUNPARAM: {os.environ.get('OCAMLRUNPARAM', '(unset)')}",
        f"compile timeout: {COMPILE_TIMEOUT_SEC}s",
        f"run timeout: {RUN_TIMEOUT_SEC}s",
    ]
    for binary in (OXFUZZER, *(c.compiler for c in CONFIGURATIONS)):
        modified = time.strftime(
            "%Y-%m-%d %H:%M:%S", time.localtime(binary.stat().st_mtime)
        )
        lines.append(f"binary: {binary} (modified {modified})")
    return "\n".join(lines) + "\n"


def failure_metadata(seed: int, run_info: str) -> str:
    return (
        f"seed: {seed}\n"
        f"time: {time.strftime('%Y-%m-%d %H:%M:%S %z')}\n"
        + run_info
    )


def status_text(result: CommandResult) -> str:
    if result.timed_out:
        return "timeout"
    if result.returncode < 0:
        return f"signal {-result.returncode}"
    return str(result.returncode)


def write_command_result(directory: Path, prefix: str, result: CommandResult) -> None:
    (directory / f"{prefix}.status").write_text(status_text(result) + "\n")
    (directory / f"{prefix}.stdout").write_bytes(result.stdout)
    (directory / f"{prefix}.stderr").write_bytes(result.stderr)


def reproduction_script(configuration: Configuration, seed: int) -> str:
    command = compile_command(
        configuration, source=Path("../program.ml"), executable=Path("program.exe")
    )
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            f"# oxfuzzer: configuration {configuration.name}, seed {seed}.",
            "set -eu",
            'cd "$(dirname "$0")"',
            f"export OCAMLLIB={shlex.quote(str(OCAMLLIB))}",
            shlex.join(command),
            "./program.exe",
            "",
        ]
    )


# Save everything needed to reproduce and diagnose a failing case under
# <output_dir>/seed-<seed>/:
#   program.ml   the generated program
#   reason.txt   why the case failed
#   meta.txt     seed, time and the run-level metadata (see run_metadata)
#   <config>/    one directory per configuration containing run.sh (a
#                standalone reproducer), compile.{status,stdout,stderr} and,
#                if the program was run, run.{status,stdout,stderr}
def save_failure(
    output_dir: Path,
    run_info: str,
    seed: int,
    program: bytes,
    results: Sequence[ConfigurationResult],
    reason: str,
) -> None:
    failure_dir = output_dir / f"seed-{seed}"
    failure_dir.mkdir(parents=True, exist_ok=True)
    (failure_dir / "program.ml").write_bytes(program)
    (failure_dir / "reason.txt").write_text(reason + "\n")
    (failure_dir / "meta.txt").write_text(failure_metadata(seed, run_info))
    for result in results:
        directory = failure_dir / result.configuration.name
        directory.mkdir(exist_ok=True)
        script = directory / "run.sh"
        script.write_text(reproduction_script(result.configuration, seed))
        script.chmod(0o755)
        write_command_result(directory, "compile", result.compilation)
        if result.execution is not None:
            write_command_result(directory, "run", result.execution)
    print(f"\nseed {seed}: {reason}", file=sys.stderr)
    print(f"saved failure to {failure_dir}", file=sys.stderr)


# A case passes when every configuration compiles and runs successfully and
# the outputs (stdout, stderr) are identical. A case is discarded when any
# execution times out. A case fails when any compilation times out or fails,
# any execution exits with a non-zero status, or the outputs differ.
def check_case(
    seed: int,
    program: bytes,
    results: Sequence[ConfigurationResult],
    stats: Stats,
    output_dir: Path,
    run_info: str,
) -> None:
    failed = [
        r for r in results
        if r.compilation.timed_out or r.compilation.returncode != 0
    ]
    if failed:
        names = ", ".join(
            f"{r.configuration.name} ({status_text(r.compilation)})"
            for r in failed
        )
        save_failure(
            output_dir, run_info, seed, program, results,
            f"compilation failed or timed out: {names}",
        )
        stats.failed += 1
        stats.report()
        return
    # If any of the executions time out, we discard the case.
    if any(r.execution.timed_out for r in results):
        stats.discarded += 1
        stats.report()
        return
    # Generated programs terminate normally by construction, so a non-zero exit
    # is a bug in the generator, the compiler or the runtime, even when all
    # configurations agree on it.
    error = [r for r in results if r.execution.returncode != 0]
    if error:
        names = ", ".join(
            f"{r.configuration.name} ({status_text(r.execution)})"
            for r in error
        )
        save_failure(
            output_dir, run_info, seed, program, results,
            f"error exit: {names}",
        )
        stats.failed += 1
        stats.report()
        return
    reference, *others = results
    for other in others:
        reference_outcome = (reference.execution.stdout, reference.execution.stderr)
        other_outcome = (other.execution.stdout, other.execution.stderr)

        if reference_outcome != other_outcome:
            save_failure(
                output_dir,
                run_info,
                seed,
                program,
                results,
                f"{reference.configuration.name} and "
                f"{other.configuration.name} disagree",
            )
            stats.failed += 1
            stats.report()
            return
    stats.passed += 1
    stats.report()


async def run_case(
    run_dir: Path,
    seed: int,
    stats: Stats,
    output_dir: Path,
    run_info: str,
    slots: asyncio.Semaphore,
) -> None:
    case_dir = run_dir / f"case-{seed}"
    try:
        program = await generate(seed, work_dir=case_dir)
        results = await asyncio.gather(
            *(
                run_configuration(
                    configuration,
                    program=program,
                    work_dir=case_dir / configuration.name,
                    slots=slots,
                )
                for configuration in CONFIGURATIONS
            )
        )
        check_case(seed, program, results, stats, output_dir, run_info)
    finally:
        shutil.rmtree(case_dir, ignore_errors=True)


SELF_CHECK_SEED = 0


# Compile and run one generated program before running the fuzzer. This
# is supposed to give more informative messages when the compilation
# pipeline itself is broken.
async def self_check(run_dir: Path) -> None:
    program = await generate(SELF_CHECK_SEED, work_dir=run_dir / "self-check")
    slots = asyncio.Semaphore(len(CONFIGURATIONS))
    results = await asyncio.gather(
        *(
            run_configuration(
                configuration,
                program=program,
                work_dir=run_dir / "self-check" / configuration.name,
                slots=slots,
            )
            for configuration in CONFIGURATIONS
        )
    )
    for result in results:
        name = result.configuration.name
        if result.compilation.timed_out or result.compilation.returncode != 0:
            raise SystemExit(
                f"oxfuzzer: self-check failed: {name} did not compile the program "
                f"generated from seed {SELF_CHECK_SEED} "
                f"({status_text(result.compilation)}).\n"
                + result.compilation.stderr.decode(errors="replace")
            )
        assert result.execution is not None
        if result.execution.timed_out or result.execution.returncode != 0:
            raise SystemExit(
                f"oxfuzzer: self-check failed: {name} did not run the program "
                f"generated from seed {SELF_CHECK_SEED} "
                f"({status_text(result.execution)}).\n"
                + result.execution.stderr.decode(errors="replace")
            )


async def fuzz(
    *,
    run_dir: Path,
    iterations: int,
    jobs: int,
    output_dir: Path,
    base_seed: int,
    run_info: str,
    stats: Stats,
) -> None:
    rng = random.Random(base_seed)
    pending = (rng.getrandbits(62) for _ in range(iterations))
    slots = asyncio.Semaphore(jobs)

    async def iteration_worker() -> None:
        # Shared iterator: each seed is taken by exactly one worker.
        for seed in pending:
            await run_case(run_dir, seed, stats, output_dir, run_info, slots)

    async with asyncio.TaskGroup() as group:
        for _ in range(jobs):
            group.create_task(iteration_worker())


async def main() -> None:
    parser = argparse.ArgumentParser(
        prog="oxfuzzer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description="""\
Differential fuzzer for the OxCaml compiler.

Each case generates a random program with oxfuzzer.exe, compiles it with every
configuration specified by the CONFIGURATIONS constant, runs the resulting
executables and compares their stdout and stderr.

A case fails if compilation fails in any configuration, a program exits with a
non-zero status, or the configurations disagree. A case is discarded if
execution times out. Each failure is saved under
<output>/seed-<generator_seed>/.

Exit status is 1 if any case failed, 0 otherwise.""",
        epilog="Before first use, run `make compiler` from the repository root.",
    )
    parser.add_argument(
        "--iterations",
        type=int,
        default=100_000,
        metavar="N",
        help="number of cases to run (default: %(default)s)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="directory in which failing inputs are saved",
    )
    parser.add_argument(
        "--jobs",
        type=int,
        default=max(1, len(os.sched_getaffinity(0)) // 2),
        metavar="N",
        help="maximum concurrent compiler/program processes "
        "(default: %(default)s, half the available CPUs)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="seed for the sequence of case seeds (default: random, printed)",
    )
    args = parser.parse_args()
    check_dependencies()
    base_seed = (
        args.seed if args.seed is not None else random.SystemRandom().getrandbits(62)
    )
    print(f"seed: {base_seed}", file=sys.stderr)
    run_info = run_metadata(base_seed)
    stats = Stats()

    # Cancel task on SIGTERM (SIGINT already installed by default by asyncio.run).
    main_task = asyncio.current_task()
    assert main_task is not None
    asyncio.get_running_loop().add_signal_handler(signal.SIGTERM, main_task.cancel)

    with tempfile.TemporaryDirectory(prefix="oxfuzzer-") as run_dir:
        try:
            await self_check(Path(run_dir))
            await fuzz(
                run_dir=Path(run_dir),
                iterations=args.iterations,
                jobs=args.jobs,
                output_dir=args.output,
                base_seed=base_seed,
                run_info=run_info,
                stats=stats,
            )
        except asyncio.CancelledError:
            stats.final_report()
            print("oxfuzzer: interrupted", file=sys.stderr)
            raise SystemExit(130)
    stats.final_report()
    if stats.failed:
        raise SystemExit(1)


if __name__ == "__main__":
    asyncio.run(main())
