window.IKINDS_GRAPH_DATA = {
  "nodes": [
    {"id": "typing/ikinds/ikinds.ml", "label": "typing/ikinds/ikinds.ml", "loc": 666, "loc_mli": 73, "info": "Ikinds facade: builds the LDD solver, normalizes jkinds, and exposes subkind/substitution APIs consumed by typing.*"},
    {"id": "typing/ikinds/ikind.ml", "label": "typing/ikinds/ikind.ml", "loc": 92, "loc_mli": 74, "info": "Ikind core layer: defines rigid atoms and instantiates Ikind.Ldd over Axis_lattice_bits and the chosen backend."},
    {"id": "typing/ikinds/ldd_jkind_solver.ml", "label": "typing/ikinds/ldd_jkind_solver.ml", "loc": 331, "loc_mli": 142, "info": "JKind solver functor: interprets jkinds as lattice polynomials and provides normalize/leq/round_up operations."},
    {"id": "typing/ikinds/axis_lattice_bits.ml", "label": "typing/ikinds/axis_lattice_bits.ml", "loc": 588, "loc_mli": 93, "info": "Bitset-backed axis lattice with modality masks, conversions to/from mod bounds, and canned constants."},
    {"id": "typing/jkind.ml", "label": "typing/jkind.ml", "info": "Jkind definitions, allowance helpers, and normalization logic that Ikinds reuses."},
    {"id": "typing/types.mli", "label": "typing/types.mli", "info": "Types interface defining type_ikind and constructor_ikind as opaque types, with ikinds passing data via Obj.magic."},
    {"id": "typing/ikinds/ldd.ml", "label": "typing/ikinds/ldd.ml", "loc": 34, "loc_mli": 84, "info": "Backend switchboard: currently configured to use the non-memoized implementation via Ldd_no_memo.Make."},
    {"id": "typing/ikinds/ldd_no_memo.ml", "label": "typing/ikinds/ldd_no_memo.ml", "loc": 504, "loc_mli": 85, "info": "Non-memoized lattice decision diagram backend implementing solver primitives."},
    {"id": "typing/ikinds/ldd_memo.ml", "label": "typing/ikinds/ldd_memo.ml", "loc": 728, "loc_mli": 85, "info": "Memoizing LDD backend with unique tables and global counter instrumentation hooks."},
    {"id": "typing/ikinds/global_counters.ml", "label": "typing/ikinds/global_counters.ml", "loc": 7, "loc_mli": 3, "info": "Global counter table used for lightweight solver profiling/instrumentation."},
    {"id": "typing/ikinds/axis_lattice.ml", "label": "typing/ikinds/axis_lattice.ml", "loc": 446, "loc_mli": 38, "info": "Array-based axis lattice mirroring Jkind axis order and wrapping the generic product lattice."},
    {"id": "typing/ikinds/product_lattice.ml", "label": "typing/ikinds/product_lattice.ml", "loc": 68, "loc_mli": 54, "info": "Generic product lattice functor providing join/meet/co_sub over fixed axis shapes."},
    {"id": "typing/jkind_axis.ml", "label": "typing/jkind_axis.ml", "info": "Axis metadata (modal and nonmodal) shared by jkinds and the lattice encoders."},
    {"id": "typing/mode.ml", "label": "typing/mode.ml", "info": "Mode and modality crossing definitions supplying per-axis constants."},
    {"id": "typing/ctype.ml", "label": "typing/ctype.ml", "info": "Type checker routines that defer subjkind/intersection and crossing logic to Ikinds."},
    {"id": "typing/typedecl.ml", "label": "typing/typedecl.ml", "info": "Type declaration processing that normalizes jkinds and caches constructor polynomials via Ikinds."},
    {"id": "typing/typemod.ml", "label": "typing/typemod.ml", "info": "Module typing entry that precomputes constructor ikinds for predefs when -ikinds is enabled."},
    {"id": "typing/includecore.ml", "label": "typing/includecore.ml", "info": "Signature inclusion checks that call Ikinds with origin tagging for diagnostics."},
    {"id": "typing/subst.ml", "label": "typing/subst.ml", "info": "Substitution utilities that preserve constructor ikinds by remapping rigid atoms without Env access."},
    {"id": "typing/path.ml", "label": "typing/path.ml", "info": "Path representation and manipulation for type constructor names, used throughout the type system."},
    {"id": "typing/ident.ml", "label": "typing/ident.ml", "info": "Identifier representation for binding names, used when processing label declarations."},
    {"id": "typing/btype.ml", "label": "typing/btype.ml", "info": "Basic type operations including row type analysis for variant immediacy checking."},
    {"id": "typing/jkind_types.ml", "label": "typing/jkind_types.ml", "info": "Jkind type definitions and sort constants used to determine constructor argument properties."},
    {"id": "driver/clflags.ml", "label": "driver/clflags.ml", "info": "Compiler flags controlling feature enablement, including the -ikinds flag."}
  ],
  "edges": [
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/ikinds/ikind.ml", "style": "solid", "label": null, "info": "Ikinds builds on Ikind.Ldd for lattice nodes and rigid-name helpers."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/ikinds/ldd_jkind_solver.ml", "style": "solid", "label": null, "info": "Ikinds uses the specialized Ldd_jkind_solver module to obtain JK operations."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/ikinds/axis_lattice_bits.ml", "style": "solid", "label": null, "info": "Ikinds calls Axis_lattice_bits for masks/constants when translating jkinds."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/jkind.ml", "style": "solid", "label": null, "info": "Ikinds consumes Jkind APIs (disallow/with_bounds/modality) while constructing ckinds."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/types.mli", "style": "dashed", "label": "Obj.magic", "info": "Obj.magic bridge: pack_constructor_ikind/unpack_constructor_ikind talk to Types.constructor_ikind without exposing the representation."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/path.ml", "style": "solid", "label": null, "info": "Uses Path.compare, Path.print, and Path.Map for constructor paths."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/ident.ml", "style": "solid", "label": null, "info": "Uses Ident.name to extract label names from declarations."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/btype.ml", "style": "solid", "label": null, "info": "Uses Btype functions (tvariant_not_immediate, static_row, fold_row) for variant analysis."},
    {"source": "typing/ikinds/ikinds.ml", "target": "typing/jkind_types.ml", "style": "solid", "label": null, "info": "Uses Jkind_types.Sort.Const.all_void to analyze constructor arguments."},
    {"source": "typing/ikinds/ikinds.ml", "target": "driver/clflags.ml", "style": "solid", "label": null, "info": "Reads Clflags.ikinds flag to enable/disable the ikinds system."},
    {"source": "typing/ikinds/ikind.ml", "target": "typing/path.ml", "style": "solid", "label": null, "info": "Uses Path.compare in RigidName module for constructor ordering."},
    {"source": "typing/ikinds/ikind.ml", "target": "typing/ikinds/axis_lattice_bits.ml", "style": "solid", "label": null, "info": "Ikind.Ldd uses the bitset lattice as its coefficient domain."},
    {"source": "typing/ikinds/ikind.ml", "target": "typing/ikinds/ldd.ml", "style": "solid", "label": null, "info": "Ikind.Ldd delegates diagram operations to the selected backend from Ldd."},
    {"source": "typing/ikinds/axis_lattice_bits.ml", "target": "typing/types.mli", "style": "solid", "label": null, "info": "Axis_lattice_bits reads/writes Types.Jkind_mod_bounds for conversions."},
    {"source": "typing/ikinds/axis_lattice_bits.ml", "target": "typing/jkind_axis.ml", "style": "solid", "label": null, "info": "Axis_lattice_bits iterates Jkind_axis metadata to map axes to bit positions."},
    {"source": "typing/ikinds/axis_lattice_bits.ml", "target": "typing/mode.ml", "style": "solid", "label": null, "info": "Axis_lattice_bits queries Mode.Modality constants to determine relevant axes."},
    {"source": "typing/jkind.ml", "target": "typing/types.mli", "style": "dashed", "label": "Obj.magic", "info": "Obj.magic reuse: jkinds reuse Types records when adjusting allowances and mod_bounds."},
    {"source": "typing/jkind.ml", "target": "typing/jkind_axis.ml", "style": "solid", "label": null, "info": "Jkind relies on Jkind_axis metadata when tracking with-bound relevance."},
    {"source": "typing/jkind.ml", "target": "typing/mode.ml", "style": "solid", "label": null, "info": "Jkind manipulates Mode.Crossing/Mod_bounds for modality reasoning."},
    {"source": "typing/ikinds/ldd.ml", "target": "typing/ikinds/ldd_no_memo.ml", "style": "solid", "label": null, "info": "Ldd.Make currently aliases to the non-memoized backend."},
    {"source": "typing/ikinds/ldd_memo.ml", "target": "typing/ikinds/global_counters.ml", "style": "solid", "label": null, "info": "Memo backend bumps Global_counters to track solver statistics."},
    {"source": "typing/ikinds/axis_lattice.ml", "target": "typing/types.mli", "style": "solid", "label": null, "info": "Axis_lattice encodes/decodes Types.Jkind_mod_bounds values."},
    {"source": "typing/ikinds/axis_lattice.ml", "target": "typing/ikinds/product_lattice.ml", "style": "solid", "label": null, "info": "Axis_lattice is instantiated from the generic product lattice functor."},
    {"source": "typing/ikinds/axis_lattice.ml", "target": "typing/jkind_axis.ml", "style": "solid", "label": null, "info": "Axis_lattice reuses Jkind_axis metadata for naming/ordering."},
    {"source": "typing/ikinds/axis_lattice.ml", "target": "typing/mode.ml", "style": "solid", "label": null, "info": "Axis_lattice queries Mode.Modality to compute relevant-axis masks."},
    {"source": "typing/ctype.ml", "target": "typing/ikinds/ikinds.ml", "style": "solid", "label": null, "info": "Type checker defers subjkind/intersection and crossing checks to Ikinds."},
    {"source": "typing/typedecl.ml", "target": "typing/ikinds/ikinds.ml", "style": "solid", "label": null, "info": "Type declarations normalize jkinds and cache constructor polynomials through Ikinds."},
    {"source": "typing/typemod.ml", "target": "typing/ikinds/ikinds.ml", "style": "solid", "label": null, "info": "Typemod precomputes constructor ikinds via Ikinds when bootstrapping environments."},
    {"source": "typing/includecore.ml", "target": "typing/ikinds/ikinds.ml", "style": "solid", "label": null, "info": "Inclusion checks call Ikinds with origin tags for better diagnostics."},
    {"source": "typing/subst.ml", "target": "typing/ikinds/ikinds.ml", "style": "dashed", "label": "identity env", "info": "Identity-env edge: substitution uses Ikinds.poly_of_type_function_in_identity_env to remap polynomials."}
  ]
};
