# jsoo-imports.sh: Regenerate the js_of_ocaml IR modules that the compiler
#                  links (middle_end/flambda2/to_jsir/jsoo_imports) from
#                  their sources in external/js_of_ocaml/compiler/lib.
#
# The sources use ppx_optcomp_light's [@@if] attributes, which the compiler's
# own build cannot evaluate, so this script runs the ppx and checks in its
# output. Two variants are produced: stock/ has [oxcaml] = false, for the
# bootstrap build with a stock OCaml compiler, and oxcaml/ has [oxcaml] =
# true, for the build with the bootstrapped compiler.
#
# Usage: jsoo-imports.sh DRIVER [--check]
#   DRIVER   the ppx_optcomp_light_standalone executable
#   --check  do not write; fail if the checked-in files are out of date
#
# Run through `make jsoo-imports` (or `make jsoo-build`), which builds DRIVER.

set -euo pipefail

cd "$(dirname "$0")/.." || exit 1

driver=${1:?usage: jsoo-imports.sh DRIVER [--check]}
check=0
if [ "${2:-}" = --check ]; then check=1; fi

if [ -f Makefile.config ]; then
  opam_exec=$(grep '^opam_exec = ' Makefile.config 2>/dev/null \
    | cut -d= -f2- | sed 's/^ *//')
fi
opam_exec=${opam_exec:-}

src=external/js_of_ocaml/compiler/lib
dst=middle_end/flambda2/to_jsir/jsoo_imports

modules=(code debug int_set int_trie optimization_hint parse_info reserved
  sizable_int stdlib targetint targetnativeint timer warning)

generate() {
  local oxcaml=$1 out=$2 m ext f kind
  local files=()
  mkdir -p "$out"
  for m in "${modules[@]}"; do
    for ext in ml mli; do
      f=$src/$m.$ext
      [ -e "$f" ] || continue
      case $ext in
        ml) kind=--impl ;;
        mli) kind=--intf ;;
      esac
      {
        # Separate comments, so that ocamlformat does not reflow them.
        printf '(* Generated by [make jsoo-imports]; do not edit. *)\n'
        printf '(* Source: %s *)\n' "$f"
        printf '(* [oxcaml] = %s *)\n\n' "$oxcaml"
        "$driver" -cookie "oxcaml=$oxcaml" "$kind" "$f"
      } > "$out/$m.$ext"
      files+=("$out/$m.$ext")
    done
  done
  $opam_exec ocamlformat -i "${files[@]}"
}

if [ $check = 0 ]; then
  generate false "$dst/stock"
  generate true "$dst/oxcaml"
  exit 0
fi

# Hidden directories are ignored by dune.
tmp=$(mktemp -d "$dst/.check.XXXXXX")
trap 'rm -rf "$tmp"' EXIT
generate false "$tmp/stock"
generate true "$tmp/oxcaml"
status=0
for variant in stock oxcaml; do
  for f in "$tmp/$variant"/*; do
    if ! diff -u "$dst/$variant/$(basename "$f")" "$f"; then
      status=1
    fi
  done
done
if [ $status != 0 ]; then
  echo "error: $dst is out of date; run 'make jsoo-imports'" >&2
fi
exit $status
