let type_expr : _ Format_doc.format_printer = Format_doc.compat Printtyp.raw_type_expr
let type_set : _ Format_doc.format_printer = Btype.TypeSet.debug_print
let row_field : _ Format_doc.format_printer = Format_doc.compat Printtyp.raw_field
let row_desc : _ Format_doc.format_printer = Format_doc.compat Printtyp.raw_row_desc
let ident : _ Format_doc.format_printer = Format_doc.compat Ident.print_with_scope
let path : _ Format_doc.format_printer = Format_doc.compat Path.print
let ctype_global_state : _ Format_doc.format_printer = Ctype.print_global_state
let sort : _ Format_doc.format_printer = Jkind.Sort.Debug_printers.t
let sort_var : _ Format_doc.format_printer = Jkind.Sort.Debug_printers.var
let jkind : _ Format_doc.format_printer = Jkind.Debug_printers.t
let zero_alloc_var : _ Format_doc.format_printer = Zero_alloc.debug_printer
let maybe_unique : _ Format_doc.format_printer = Uniqueness_analysis.Maybe_unique.print
let maybe_aliased : _ Format_doc.format_printer = Uniqueness_analysis.Maybe_aliased.print
let aliased : _ Format_doc.format_printer = Uniqueness_analysis.Aliased.print
let tag : _ Format_doc.format_printer = Uniqueness_analysis.Tag.print
let projection : _ Format_doc.format_printer = Uniqueness_analysis.Projection.print
let usage_tree : _ Format_doc.format_printer = Uniqueness_analysis.Usage_tree.print
let usage_forest : _ Format_doc.format_printer = Uniqueness_analysis.Usage_forest.print
let paths : _ Format_doc.format_printer = Uniqueness_analysis.Paths.print
let value : _ Format_doc.format_printer = Uniqueness_analysis.Value.print
let ienv : _ Format_doc.format_printer = Uniqueness_analysis.Ienv.print
let axis_set : _ Format_doc.format_printer = Jkind_axis.Axis_set.print
let layout : _ Format_doc.format_printer = Jkind.Layout.Debug_printers.t Jkind.Sort.Debug_printers.t
let mod_bounds : _ Format_doc.format_printer = Btype.Jkind0.Mod_bounds.debug_print
let with_bounds : _ Format_doc.format_printer = Jkind.With_bounds.debug_print
let with_bounds_types : _ Format_doc.format_printer = Jkind.With_bounds.debug_print_types
let modalities : _ Format_doc.format_printer = Format_doc.compat Mode.Modality.Const.print
