#!/usr/bin/env python3
"""Compare speculative inlining configurations and produce a PDF report.

The work is split so that the commentary is written by a person or an LLM
from the measured numbers, not generated by this script:

  run       in a source tree, for each configuration: run its clean and
            build commands (timed), harvest the .inlining.org reports and
            the sizes of the OCaml objects; then do what `analyse` does
  analyse   from harvested data: compute the statistics, draw the figures,
            write NARRATIVE_PROMPT.md (a self-contained request for the
            commentary, carrying every number) and a draft PDF whose
            commentary is placeholder text
  render    assemble the final PDF from the analysis and narrative.md

Typical use on the compiler tree:

  tools/inlining_comparison_report.py run --preset oxcaml --data report-data
  # write report-data/narrative.md from report-data/NARRATIVE_PROMPT.md
  tools/inlining_comparison_report.py render --data report-data report.pdf

For another tree, start from `example-config` and pass --config FILE.
Needs Python 3 with numpy, matplotlib and reportlab; scipy is optional
(fitted curves). The `size` tool from binutils (or the macOS one) is used
for object sizes.
"""
import argparse
import csv
import datetime
import html
import importlib.util
import json
import os
import platform
import re
import resource
import shlex
import subprocess
import sys
import time
from collections import Counter, defaultdict
from statistics import median

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)


def need(*modules):
    """Import the given modules or exit with an installation hint."""
    missing = []
    for m in modules:
        try:
            __import__(m)
        except ImportError:
            missing.append(m)
    if missing:
        sys.exit(f"missing Python modules: {' '.join(missing)}; install with e.g. "
                 f"'python3 -m pip install {' '.join(missing)}' (scipy is optional)")

PRESETS = {
    'oxcaml': {
        'title': 'Speculative inlining: the 2026 configuration against the current one',
        'tree': REPO,
        'report_dirs': ['_build/runtime_stdlib', '_build/main'],
        'object_dirs': ['_build/runtime_stdlib', '_build/main'],
        'watch_callees': ['Flambda2_algorithms__Patricia_tree', 'Flambda2_algorithms__Container_types',
                          'Flambda2_algorithms__Lmap', 'Stdlib__Set.Make', 'Stdlib__Map.Make',
                          'Stdlib__Hashtbl.Make'],
        'configs': [
            {'name': 'current',
             'label': 'current (v1 size model, threshold criterion)',
             'clean': 'rm -rf _build duneconf/*.ws',
             'command': 'make -s',
             'env': {'BUILD_OCAMLPARAM': '_,inlining-report=1'},
             'size_units': 'v1 model units'},
            {'name': '2026',
             'label': '2026 configuration (-flambda2-inline-2026)',
             'clean': 'rm -rf _build duneconf/*.ws',
             'command': 'make -s',
             'env': {'BUILD_OCAMLPARAM': '_,flambda2-inline-2026=1,inlining-report=1'},
             'size_units': 'v2 model instructions'},
        ],
    },
}

BIN_EDGES = [0] + list(range(10, 201, 10)) + [250, 300, 350, 400, 450, 500,
                                             750, 1000, 1500, 2000, 3000, 5000]
MIN_BIN = 20  # bins with fewer decisions are not drawn

# Chart chrome (light) and the categorical palette, one slot per configuration.
SURFACE, INK, INK2, MUTED = '#fcfcfb', '#0b0b0b', '#52514e', '#898781'
GRID, AXIS = '#e1e0d9', '#c3c2b7'
PALETTE = ['#2a78d6', '#eb6834', '#1baf7a']


# --------------------------------------------------------------------------
# configuration
# --------------------------------------------------------------------------

def load_config(args):
    if args.config:
        with open(args.config) as f:
            cfg = json.load(f)
    elif args.preset:
        cfg = json.loads(json.dumps(PRESETS[args.preset]))
    else:
        sys.exit('give --preset or --config')
    if getattr(args, 'tree', None):
        cfg['tree'] = args.tree
    cfg['tree'] = os.path.abspath(cfg['tree'])
    if len(cfg['configs']) < 1:
        sys.exit('no configurations')
    for c in cfg['configs']:
        c.setdefault('env', {})
        c.setdefault('clean', '')
        c.setdefault('size_units', 'model units')
    return cfg


# --------------------------------------------------------------------------
# run: build and harvest
# --------------------------------------------------------------------------

def run_command(cmd, cwd, env):
    print(f'+ {cmd}', flush=True)
    before = resource.getrusage(resource.RUSAGE_CHILDREN)
    t0 = time.time()
    r = subprocess.run(cmd, shell=True, cwd=cwd, env=env)
    wall = time.time() - t0
    after = resource.getrusage(resource.RUSAGE_CHILDREN)
    cpu = (after.ru_utime - before.ru_utime) + (after.ru_stime - before.ru_stime)
    if r.returncode != 0:
        sys.exit(f'command failed with status {r.returncode}: {cmd}')
    return wall, cpu


def ocaml_objects(tree, object_dirs):
    """Paths of .o files that have a .cmx beside them (OCaml-generated code)."""
    out = []
    for d in object_dirs:
        for root, _, files in os.walk(os.path.join(tree, d)):
            names = set(files)
            for fn in files:
                if fn.endswith('.o') and fn[:-2] + '.cmx' in names:
                    out.append(os.path.join(root, fn))
    return sorted(out)


def parse_size_output(stdout):
    """Text sizes from the output of `size` (GNU binutils Berkeley format or
    the macOS tool): one row per object, first column the text size, header
    lines mentioning `text` or `__TEXT` skipped."""
    out = []
    for line in stdout.splitlines():
        if not line.strip() or re.search(r'\btext\b|__TEXT', line):
            continue
        tok = line.split()[0]
        if tok.isdigit():
            out.append(int(tok))
    return out


def size_tool_available():
    try:
        subprocess.run(['size', '--version'], capture_output=True)
        return True
    except OSError:
        return False


def text_sizes(paths):
    """Text section size in bytes of each object via the `size` tool, or the
    file size when the tool is not installed. Returns (sizes, measure)."""
    if not size_tool_available():
        print("  warning: `size` (binutils) not found; using file sizes instead", flush=True)
        return {p: os.path.getsize(p) for p in paths}, 'file size'
    sizes = {}
    chunk = 200
    for i in range(0, len(paths), chunk):
        batch = paths[i:i + chunk]
        r = subprocess.run(['size'] + batch, capture_output=True, text=True)
        rows = parse_size_output(r.stdout)
        if len(rows) != len(batch):
            for p in batch:  # fall back to one call per file
                r1 = subprocess.run(['size', p], capture_output=True, text=True)
                rows1 = parse_size_output(r1.stdout)
                sizes[p] = rows1[0] if rows1 else 0
            continue
        for p, v in zip(batch, rows):
            sizes[p] = v
    return sizes, 'text section'


def objdump_available():
    try:
        subprocess.run(['objdump', '--version'], capture_output=True)
        return True
    except OSError:
        return False


def count_calls(path):
    """(direct calls, indirect calls, generic applications) in one object.

    Direct calls are `bl` (arm64) or `call` to a symbol (x86-64); indirect
    calls are `blr` or `call *reg`; generic applications are relocations to
    caml_applyN or caml_sendN, the calls made when the callee or its arity is
    unknown. Works with GNU and LLVM objdump."""
    direct = indirect = generic = 0
    r = subprocess.run(['objdump', '-d', '-r', path], capture_output=True, text=True,
                       errors='replace')
    for line in r.stdout.splitlines():
        if 'caml_apply' in line or 'caml_send' in line:
            if 'RELOC' in line or 'R_' in line:
                generic += 1
                continue
        # GNU objdump: "addr:<tab>bytes<tab>mnemonic<tab>operands" (x86 puts the
        # operands in the mnemonic's field); LLVM objdump: "addr: bytes<tab>
        # mnemonic<tab>operands". Take the first field that starts like a
        # mnemonic.
        parts = line.split('\t')
        m = ops = None
        for i in range(1, len(parts)):
            toks = parts[i].split()
            if not toks or all(re.fullmatch(r'[0-9a-f]{2}', t) for t in toks) \
                    or (len(toks) == 1 and re.fullmatch(r'[0-9a-f]{8}', toks[0])):
                continue  # the instruction's bytes
            mm = re.match(r'^([a-z][a-z0-9.]*)(?:\s+(.*))?$', parts[i].strip())
            if mm:
                m = mm.group(1)
                ops = mm.group(2) or (parts[i + 1].strip() if i + 1 < len(parts) else '')
                break
        if m is None:
            continue
        if m == 'bl' or (m in ('call', 'callq') and not ops.startswith('*')):
            direct += 1
        elif m == 'blr' or (m in ('call', 'callq') and ops.startswith('*')):
            indirect += 1
    return direct, indirect, generic


def harvest(cfg, c, data_dir, build_timing):
    tree = cfg['tree']
    cdir = os.path.join(data_dir, c['name'])
    os.makedirs(cdir, exist_ok=True)
    spec = importlib.util.spec_from_file_location(
        'inlining_decisions', os.path.join(HERE, 'inlining_decisions.py'))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    roots = [os.path.join(tree, d) for d in cfg['report_dirs']]
    summary = mod.collect(roots, os.path.join(cdir, 'decisions.csv'))
    print(f"  reports: {summary}")
    objs = ocaml_objects(tree, cfg['object_dirs'])
    sizes, measure = text_sizes(objs)
    with open(os.path.join(cdir, 'objects.csv'), 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['path', 'text_bytes'])
        for p in objs:
            w.writerow([os.path.relpath(p, tree), sizes.get(p, 0)])
    print(f"  objects: {len(objs)} files, {sum(sizes.values()):,} text bytes")
    if objdump_available():
        with open(os.path.join(cdir, 'calls.csv'), 'w', newline='') as f:
            w = csv.writer(f)
            w.writerow(['path', 'direct_calls', 'indirect_calls', 'generic_applies'])
            tot = [0, 0, 0]
            for p in objs:
                d, i, g = count_calls(p)
                tot[0] += d; tot[1] += i; tot[2] += g
                w.writerow([os.path.relpath(p, tree), d, i, g])
        print(f"  calls: {tot[0]:,} direct, {tot[1]:,} indirect, {tot[2]:,} generic applications")
    else:
        print("  warning: objdump not found; call instructions not counted", flush=True)
    commit = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], cwd=tree,
                            capture_output=True, text=True).stdout.strip()
    meta = {'name': c['name'], 'label': c['label'], 'clean': c['clean'],
            'command': c['command'], 'env': c['env'], 'size_units': c['size_units'],
            'wall_seconds': build_timing[0], 'cpu_seconds': build_timing[1],
            'timestamp': datetime.datetime.now().isoformat(timespec='seconds'),
            'tree': tree, 'commit': commit, 'host': platform.node(),
            'machine': platform.machine(), 'object_size_measure': measure,
            'report_summary': summary}
    with open(os.path.join(cdir, 'meta.json'), 'w') as f:
        json.dump(meta, f, indent=2)


def cmd_run(args):
    cfg = load_config(args)
    data_dir = os.path.abspath(args.data)
    os.makedirs(data_dir, exist_ok=True)
    with open(os.path.join(data_dir, 'config.json'), 'w') as f:
        json.dump(cfg, f, indent=2)
    for c in cfg['configs']:
        if args.only and c['name'] not in args.only:
            continue
        print(f"=== configuration {c['name']}: {c['label']}", flush=True)
        env = dict(os.environ)
        env.update(c['env'])
        timing = (None, None)
        old_meta = os.path.join(data_dir, c['name'], 'meta.json')
        if args.skip_build and os.path.exists(old_meta):
            with open(old_meta) as fh:
                m = json.load(fh)
            timing = (m.get('wall_seconds'), m.get('cpu_seconds'))
        if not args.skip_build:
            if c['clean']:
                run_command(c['clean'], cfg['tree'], env)
            timing = run_command(c['command'], cfg['tree'], env)
            print(f'  build: {timing[0]:.0f} s wall, {timing[1]:.0f} s cpu')
        harvest(cfg, c, data_dir, timing)
    analyse(data_dir)


# --------------------------------------------------------------------------
# analyse: statistics and figures
# --------------------------------------------------------------------------

def arch_col():
    return 'arm64' if platform.machine() in ('arm64', 'aarch64') else 'x86'


def load_decisions(cdir):
    rows = []
    with open(os.path.join(cdir, 'decisions.csv')) as f:
        for r in csv.DictReader(f):
            rows.append(r)
    return rows


def f(x, default=None):
    try:
        return float(x)
    except (TypeError, ValueError):
        return default


def bin_index(size):
    for i, e in enumerate(BIN_EDGES):
        if i + 1 == len(BIN_EDGES) or size < BIN_EDGES[i + 1]:
            return i
    return len(BIN_EDGES) - 1


def bin_label(i):
    if i + 1 < len(BIN_EDGES):
        return f'{BIN_EDGES[i]}-{BIN_EDGES[i + 1] - 1}'
    return f'{BIN_EDGES[i]}+'


def per_config_stats(rows, arch):
    o_col, s_col = 'orig_' + arch, 'simp_' + arch
    st = {}
    outcomes = Counter(r['outcome'] for r in rows)
    st['decisions'] = len(rows)
    st['decided'] = outcomes.get('decided', 0)
    st['aborted'] = outcomes.get('aborted', 0)
    st['budget_refused'] = outcomes.get('budget_exhausted', 0)
    decided = [r for r in rows if r['outcome'] == 'decided' and r['functor'] != 'True']
    inl = [r for r in decided if r['inlined'] == 'True']
    functors = [r for r in rows if r['functor'] == 'True']
    st['functor_decisions'] = len(functors)
    st['functor_inlined'] = sum(1 for r in functors if r['outcome'] == 'decided' and r['inlined'] == 'True')
    st['functor_not_completed'] = sum(1 for r in functors if r['outcome'] != 'decided')
    st['inlined'] = len(inl)
    st['rejected'] = len(decided) - len(inl)
    st['inlined_share'] = len(inl) / len(decided) if decided else 0.0
    st['distinct_callees_inlined'] = len({r['callee'] for r in inl})
    bodies = [f(r[s_col], 0.0) for r in inl]
    st['inlined_body_total'] = sum(bodies)
    st['inlined_body_median'] = median(bodies) if bodies else 0.0
    work = [f(r[o_col]) for r in rows if r['outcome'] != 'budget_exhausted']
    st['speculation_work'] = sum(w for w in work if w is not None)
    # Every non-functor speculation with a known callee size, whatever its
    # outcome: an aborted or refused speculation is a decision not to inline.
    sized = [r for r in rows if r['functor'] != 'True' and f(r[o_col]) is not None]
    st['sized_decisions'] = len(sized)
    bins = defaultdict(lambda: {'n': 0, 'inlined': 0, 'aborted': 0, 'body': 0.0})
    for r in sized:
        b = bins[bin_index(int(f(r[o_col])))]
        b['n'] += 1
        if r['outcome'] != 'decided':
            b['aborted'] += 1
        elif r['inlined'] == 'True':
            b['inlined'] += 1
            b['body'] += f(r[s_col], 0.0)
    st['bins'] = {bin_label(i): bins[i] for i in sorted(bins)}
    thr_rows = decided  # completed speculations, which have a simplified size
    callees = defaultdict(lambda: {'calls': 0, 'body': 0.0, 'orig': 0.0, 'bodies': []})
    for r in inl:
        k = callees[r['callee']]
        k['calls'] += 1
        k['body'] += f(r[s_col], 0.0)
        k['orig'] = f(r[o_col], 0.0)
        k['bodies'].append(f(r[s_col], 0.0))
    top = sorted(callees.items(), key=lambda kv: -kv[1]['body'])[:12]
    st['top_callees'] = [{'callee': k, 'calls': v['calls'], 'body': v['body'],
                          'orig': v['orig'], 'median_body': median(v['bodies'])}
                         for k, v in top]
    st['shrink'] = [(f(r[o_col]), f(r[s_col]), r['inlined'] == 'True')
                    for r in thr_rows if f(r[o_col], 0) > 0]
    ratios = [s / o for o, s, _ in st['shrink']]
    st['shrink_median_ratio'] = median(ratios) if ratios else None
    return st


def load_calls(cdir):
    p = os.path.join(cdir, 'calls.csv')
    out = {}
    if os.path.exists(p):
        with open(p) as f:
            for r in csv.DictReader(f):
                out[r['path']] = (int(r['direct_calls']), int(r['indirect_calls']), int(r['generic_applies']))
    return out


def load_callsites(cdir):
    p = os.path.join(cdir, 'decisions.callsites.csv')
    out = []
    if os.path.exists(p):
        with open(p) as f:
            for r in csv.DictReader(f):
                out.append((r['callee'], r['outcome'], r['reason'], int(r['count'])))
    return out


REASONS = ['inlined: definition', 'inlined: speculation', 'inlined: attribute', 'inlined: other',
           'not inlined: never inlinable', 'not inlined: speculation', 'not inlined: aborted',
           'not inlined: budget refused', 'not inlined: arguments not useful',
           'not inlined: inside speculation', 'not inlined: depth', 'not inlined: other']


def watch_table(callsites, prefix):
    """Call sites to callees whose path contains [prefix], by outcome and reason."""
    out = Counter()
    for callee, outcome, reason, n in callsites:
        if outcome == 'unknown' or prefix not in callee:
            continue
        key = f'{outcome}: {reason}'
        if key not in REASONS:
            key = f'{outcome}: other'
        out[key] += n
    table = {k: out.get(k, 0) for k in REASONS if out.get(k, 0)}
    table['sites'] = sum(out.values())
    return table


def load_unknown(cdir):
    p = os.path.join(cdir, 'decisions.unknown_calls.csv')
    out = {}
    if os.path.exists(p):
        with open(p) as f:
            for r in csv.DictReader(f):
                out[r['unit']] = int(r['unknown_callee_sites'])
    return out


def functor_table(rows):
    by = defaultdict(lambda: {'applications': 0, 'inlined': 0, 'rejected': 0, 'aborted': 0, 'size': 0})
    for r in rows:
        if r['functor'] != 'True':
            continue
        k = r['callee'].split('::', 1)[-1]
        b = by[k]
        b['applications'] += 1
        if r['outcome'] != 'decided':
            b['aborted'] += 1
        elif r['inlined'] == 'True':
            b['inlined'] += 1
        else:
            b['rejected'] += 1
        if r['orig_arm64'] or r['orig_x86']:
            b['size'] = int(f(r['orig_' + arch_col()], 0))
    top = sorted(by.items(), key=lambda kv: -kv[1]['applications'])[:12]
    return [dict(functor=k, **v) for k, v in top]


def load_objects(cdir):
    out = {}
    with open(os.path.join(cdir, 'objects.csv')) as f:
        for r in csv.DictReader(f):
            out[r['path']] = int(r['text_bytes'])
    return out


def dir_key(path, depth=3):
    parts = [p for p in path.split('/') if not p.startswith('.')]
    return '/'.join(parts[:depth])


def style(ax):
    ax.set_facecolor(SURFACE)
    for s in ('top', 'right'):
        ax.spines[s].set_visible(False)
    for s in ('left', 'bottom'):
        ax.spines[s].set_color(AXIS)
    ax.grid(True, color=GRID, linewidth=1)
    ax.set_axisbelow(True)
    ax.tick_params(colors=INK2, labelsize=8, length=0)


def fig_lines(path, configs, stats, key, ylabel, title, percent=False):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    fig, ax = plt.subplots(figsize=(7.2, 3.6), facecolor=SURFACE)
    fig.subplots_adjust(left=0.1, right=0.98, top=0.86, bottom=0.2)
    style(ax)
    labels = [bin_label(i) for i in range(len(BIN_EDGES))]
    for i, c in enumerate(configs):
        bins = stats[c['name']]['bins']
        xs, ys = [], []
        for j, lab in enumerate(labels):
            b = bins.get(lab)
            if not b or b['n'] < MIN_BIN:
                continue
            xs.append(j)
            if key == 'share':
                ys.append(100.0 * b['inlined'] / b['n'])
            elif key == 'inlined':
                ys.append(b['inlined'])
            elif key == 'body':
                ys.append(b['body'])
        if xs:
            ax.plot(xs, ys, color=PALETTE[i], linewidth=2, marker='o', markersize=4,
                    markeredgecolor=SURFACE, markeredgewidth=1, label=c['label'])
    ax.set_xticks(range(len(labels)))
    ax.set_xticklabels(labels, rotation=60, ha='right', fontsize=7)
    ax.set_xlabel('callee size before inlining (each configuration in its own model units)',
                  color=INK2, fontsize=8)
    ax.set_ylabel(ylabel, color=INK2, fontsize=8)
    if percent:
        ax.set_ylim(-2, 104)
    ax.legend(frameon=False, fontsize=8, labelcolor=INK2)
    fig.suptitle(title, color=INK, fontsize=10, x=0.1, ha='left', y=0.96)
    fig.text(0.1, 0.895, f'Bins with fewer than {MIN_BIN} decisions are omitted.',
             color=INK2, fontsize=7)
    fig.savefig(path, dpi=200, facecolor=SURFACE)
    plt.close(fig)


def fig_shrink(path, configs, stats):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import numpy as np
    n = len(configs)
    fig, axes = plt.subplots(1, n, figsize=(7.2, 3.4), facecolor=SURFACE, squeeze=False)
    fig.subplots_adjust(left=0.08, right=0.98, top=0.82, bottom=0.17, wspace=0.18)
    medians = {}
    for i, c in enumerate(configs):
        ax = axes[0][i]
        style(ax)
        data = stats[c['name']]['shrink']
        if not data:
            ax.set_title(c['label'], color=INK2, fontsize=8)
            continue
        xs = np.array([d[0] for d in data]); ys = np.array([d[1] / d[0] for d in data])
        xmax = float(np.percentile(xs, 99.5)) if len(xs) > 50 else float(xs.max())
        rng = np.random.default_rng(0)
        ax.scatter(xs + rng.uniform(-0.4, 0.4, len(xs)), np.clip(ys, -0.5, 2.0), s=4,
                   c=PALETTE[i], alpha=0.08, linewidths=0, rasterized=True)
        ax.axhline(1.0, color=AXIS, linewidth=1, zorder=0)
        # Median ratio per size bin (bins with at least MIN_BIN points).
        mx, my = [], []
        for j in range(len(BIN_EDGES)):
            lo = BIN_EDGES[j]
            hi = BIN_EDGES[j + 1] if j + 1 < len(BIN_EDGES) else float('inf')
            sel = (xs >= lo) & (xs < hi)
            if sel.sum() >= MIN_BIN:
                mx.append(float(np.median(xs[sel]))); my.append(float(np.median(ys[sel])))
        if mx:
            ax.plot(mx, my, color=INK, linewidth=1.6, marker='o', markersize=3, zorder=5)
            medians[c['name']] = [{'size': round(a), 'median_ratio': round(b, 3)} for a, b in zip(mx, my)]
        ax.set_xlim(0, xmax)
        ax.set_ylim(-0.5, 2.0)
        ax.set_title(c['label'], color=INK2, fontsize=8)
        ax.set_xlabel(f"callee size before inlining ({c['size_units']})", color=INK2, fontsize=7)
        if i == 0:
            ax.set_ylabel('simplified size / size before inlining', color=INK2, fontsize=8)
    fig.suptitle('How much speculation shrinks a callee, one point per completed speculation',
                 color=INK, fontsize=10, x=0.08, ha='left', y=0.96)
    fig.text(0.08, 0.885, f'Black line: median ratio per size bin (bins with at least {MIN_BIN} points); '
             'aborted speculations have no simplified size and are absent.', color=INK2, fontsize=7)
    fig.savefig(path, dpi=200, facecolor=SURFACE)
    plt.close(fig)
    return medians


def fig_objects(path, deltas, labels):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    top = sorted(deltas.items(), key=lambda kv: -abs(kv[1]))[:14]
    top = sorted(top, key=lambda kv: kv[1])
    fig, ax = plt.subplots(figsize=(7.2, 0.22 * len(top) + 1.2), facecolor=SURFACE)
    fig.subplots_adjust(left=0.36, right=0.97, top=0.84, bottom=0.17)
    style(ax)
    names = [k for k, _ in top]
    vals = [v / 1024.0 for _, v in top]
    colors = ['#e34948' if v > 0 else '#2a78d6' for v in vals]
    ax.barh(range(len(top)), vals, color=colors, height=0.6)
    ax.set_yticks(range(len(top)))
    ax.set_yticklabels(names, fontsize=7)
    ax.axvline(0, color=AXIS, linewidth=1)
    ax.set_xlabel(f'change in OCaml object text size, KiB ({labels[1]} minus {labels[0]})',
                  color=INK2, fontsize=8)
    fig.suptitle('Largest changes in generated code size by directory', color=INK, fontsize=10,
                 x=0.36, ha='left', y=0.97)
    fig.savefig(path, dpi=200, facecolor=SURFACE)
    plt.close(fig)


def analyse(data_dir):
    need('numpy', 'matplotlib', 'reportlab')
    with open(os.path.join(data_dir, 'config.json')) as f:
        cfg = json.load(f)
    arch = arch_col()
    configs = cfg['configs']
    stats, metas, objects = {}, {}, {}
    for c in configs:
        cdir = os.path.join(data_dir, c['name'])
        with open(os.path.join(cdir, 'meta.json')) as f:
            metas[c['name']] = json.load(f)
        rows = load_decisions(cdir)
        stats[c['name']] = per_config_stats(rows, arch)
        stats[c['name']]['functors'] = functor_table(rows)
        objects[c['name']] = load_objects(cdir)
        stats[c['name']]['object_text_total'] = sum(objects[c['name']].values())
        stats[c['name']]['object_count'] = len(objects[c['name']])
        calls = load_calls(cdir)
        stats[c['name']]['calls'] = calls
        stats[c['name']]['direct_calls'] = sum(v[0] for v in calls.values()) if calls else None
        stats[c['name']]['indirect_calls'] = sum(v[1] for v in calls.values()) if calls else None
        stats[c['name']]['generic_applies'] = sum(v[2] for v in calls.values()) if calls else None
        unknown = load_unknown(cdir)
        stats[c['name']]['unknown_by_unit'] = unknown
        stats[c['name']]['unknown_callee_sites'] = sum(unknown.values()) if unknown else None
        callsites = load_callsites(cdir)
        watched = {}
        for prefix in cfg.get('watch_callees', []):
            unit = prefix.split('.')[0].split('::')[0]
            entry = watch_table(callsites, prefix)
            entry['unknown_sites_in_unit'] = sum(v for u, v in unknown.items() if u == unit)
            objs = [(p, v) for p, v in calls.items() if os.path.basename(p).lower() == unit.lower() + '.o']
            if objs:
                entry['unit_calls'] = {'direct': sum(v[0] for _, v in objs), 'indirect': sum(v[1] for _, v in objs),
                                       'generic': sum(v[2] for _, v in objs)}
            watched[prefix] = entry
        stats[c['name']]['watched'] = watched
    figdir = os.path.join(data_dir, 'figures')
    os.makedirs(figdir, exist_ok=True)
    fig_lines(os.path.join(figdir, 'probability.png'), configs, stats, 'share',
              'decisions that inline (%)', 'Share of speculative decisions that inline, by callee size', percent=True)
    fig_lines(os.path.join(figdir, 'inlined.png'), configs, stats, 'inlined',
              'inlined decisions', 'Number of inlined decisions, by callee size')
    fig_lines(os.path.join(figdir, 'body.png'), configs, stats, 'body',
              'inlined body size (model units)', 'Code added by inlining, by callee size')
    medians = fig_shrink(os.path.join(figdir, 'shrink.png'), configs, stats)
    for name, med in medians.items():
        stats[name]['shrink_medians'] = med
    deltas = {}
    if len(configs) >= 2:
        a, b = configs[0]['name'], configs[-1]['name']
        by_dir_a, by_dir_b = Counter(), Counter()
        for p, v in objects[a].items():
            by_dir_a[dir_key(p)] += v
        for p, v in objects[b].items():
            by_dir_b[dir_key(p)] += v
        for d in set(by_dir_a) | set(by_dir_b):
            deltas[d] = by_dir_b[d] - by_dir_a[d]
        fig_objects(os.path.join(figdir, 'objects.png'), deltas,
                    [configs[0]['name'], configs[-1]['name']])
    call_deltas, unknown_deltas = [], []
    if len(configs) >= 2:
        a, b = configs[0]['name'], configs[-1]['name']
        ca, cb = stats[a]['calls'], stats[b]['calls']
        for p in set(ca) & set(cb):
            d = (cb[p][1] + cb[p][2]) - (ca[p][1] + ca[p][2])
            if d:
                call_deltas.append((p, ca[p][1] + ca[p][2], cb[p][1] + cb[p][2], d))
        call_deltas.sort(key=lambda t: -t[3])
        ua, ub = stats[a]['unknown_by_unit'], stats[b]['unknown_by_unit']
        for u in set(ua) & set(ub):
            if ub[u] != ua[u]:
                unknown_deltas.append((u, ua[u], ub[u], ub[u] - ua[u]))
        unknown_deltas.sort(key=lambda t: -t[3])
    out = {'generated': datetime.datetime.now().isoformat(timespec='seconds'),
           'call_deltas_top': call_deltas[:15], 'call_deltas_bottom': call_deltas[-10:],
           'unknown_deltas_top': unknown_deltas[:15],
           'arch': arch, 'configs': [c['name'] for c in configs],
           'stats': {k: {kk: vv for kk, vv in v.items() if kk not in ('shrink', 'calls', 'unknown_by_unit')} for k, v in stats.items()},
           'metas': metas,
           'object_dir_deltas': dict(sorted(deltas.items(), key=lambda kv: -abs(kv[1]))[:30])}
    with open(os.path.join(data_dir, 'stats.json'), 'w') as fh:
        json.dump(out, fh, indent=2)
    write_prompt(data_dir, cfg, out)
    render(data_dir, os.path.join(data_dir, 'draft.pdf'), narrative=None)
    print(f'analysis written to {data_dir}: stats.json, figures/, NARRATIVE_PROMPT.md, draft.pdf')


# --------------------------------------------------------------------------
# narrative prompt
# --------------------------------------------------------------------------

SECTIONS = [
    ('summary', 'Executive summary: what changed between the configurations, in four to six sentences, led by the headline numbers (object size, build time, inlining counts).'),
    ('fig-probability', 'Commentary on figure 1 (share of speculative decisions that inline, by callee size): where each configuration inlines, where it stops, and why the curves differ.'),
    ('fig-inlined', 'Commentary on figure 2 (number of inlined decisions by callee size).'),
    ('fig-body', 'Commentary on figure 3 (code added by inlining, by callee size): where the code growth comes from in each configuration.'),
    ('fig-shrink', 'Commentary on figure 4 (how much speculation shrinks a callee, with the fitted curve): what the shape says about the size reduction and the fitted parameters.'),
    ('fig-objects', 'Commentary on figure 5 (change in generated code size by directory), if present.'),
    ('table-callees', 'Remarks on the table of callees contributing most inlined code in each configuration.'),
    ('functors', 'Functor applications: how each configuration treated them (table 4) and, from the call counts, whether the calls to the resulting modules and inside them stayed direct; name any functor whose treatment looks harmful.'),
    ('calls', 'Direct and indirect calls in the generated code (table 5 and the per-unit changes): did the configuration add indirect calls or generic applications, and where.'),
    ('watched', 'The watched callees (table 7): for each, how its call sites fared in each configuration and whether its own code gained indirect calls; say plainly whether the treatment changed and whether that matters.'),
    ('conclusions', 'Conclusions and recommendations: three to six bullet points, including caveats about what the measurements cannot show.'),
]


def fmt_int(x):
    return f'{int(round(x)):,}'


def write_prompt(data_dir, cfg, out):
    names = out['configs']
    st, metas = out['stats'], out['metas']
    L = []
    L.append('# Request for the commentary of an inlining comparison report')
    L.append('')
    L.append('You are writing the commentary of a short technical report comparing speculative '
             'inlining configurations of the OxCaml compiler (Flambda 2). Every number you may '
             'use is below; do not invent any. Write plainly and factually for compiler engineers, '
             'in British English, no marketing language. Figures are referred to by number. '
             'Where a difference cannot be attributed from these data, say so.')
    L.append('')
    L.append('Write your answer as a Markdown file with exactly these second-level headings, '
             'in this order, each followed by prose paragraphs (and bullet lists where asked):')
    for key, desc in SECTIONS:
        L.append(f'- `## {key}` : {desc}')
    L.append('')
    L.append('Save it as `narrative.md` in this directory; the PDF is then produced with '
             '`inlining_comparison_report.py render --data <this directory> report.pdf`.')
    L.append('')
    L.append(f"## Report title: {cfg['title']}")
    L.append(f"Generated {out['generated']}; sizes are the {out['arch']} estimates of each model.")
    L.append('')
    L.append('## Configurations')
    for n in names:
        m = metas[n]
        L.append(f"- `{n}`: {m['label']}. Build command `{m['command']}` with environment "
                 f"{json.dumps(m['env'])}" + (f", after `{m['clean']}`" if m['clean'] else '') +
                 f". Tree {m['tree']} at commit {m['commit']} on {m['host']} ({m['machine']}). "
                 f"Size units of its reports: {m['size_units']}.")
    L.append('')
    L.append('## Headline numbers (table 1 of the report)')
    L.append('| metric | ' + ' | '.join(names) + ' |')
    L.append('|---|' + '---|' * len(names))
    def row(label, key, fmt=fmt_int, src=st):
        L.append(f'| {label} | ' + ' | '.join(fmt(src[n][key]) if src[n].get(key) is not None else 'n/a' for n in names) + ' |')
    row('build wall time (s)', 'wall_seconds', lambda x: f'{x:.0f}', metas)
    row('build CPU time (s)', 'cpu_seconds', lambda x: f'{x:.0f}', metas)
    row('OCaml objects measured', 'object_count')
    row('OCaml object text size (bytes)', 'object_text_total')
    row('speculative decisions (all outcomes)', 'decisions')
    row('  of which judged after a full speculation', 'decided')
    row('  of which aborted by the budget', 'aborted')
    row('  of which refused before speculating (budget pre-check)', 'budget_refused')
    row('  of which functor applications', 'functor_decisions')
    row('    functor applications inlined', 'functor_inlined')
    row('    functor applications aborted or refused', 'functor_not_completed')
    row('inlined', 'inlined')
    row('rejected', 'rejected')
    row('share inlined (of judged, non-functor)', 'inlined_share', lambda x: f'{100 * x:.1f}%')
    row('distinct callees inlined', 'distinct_callees_inlined')
    row('inlined body size, total (model units)', 'inlined_body_total')
    row('inlined body size, median (model units)', 'inlined_body_median', lambda x: f'{x:.0f}')
    row('speculation work: callee sizes speculated on, total (model units)', 'speculation_work')
    row('median simplified/original size ratio (completed speculations)', 'shrink_median_ratio', lambda x: f'{x:.2f}')
    row('direct call instructions in the objects', 'direct_calls')
    row('indirect call instructions (register calls)', 'indirect_calls')
    row('generic applications (calls to caml_applyN / caml_sendN)', 'generic_applies')
    row('call sites whose callee was unknown to Flambda 2 (from the reports)', 'unknown_callee_sites')
    if len(names) >= 2:
        a, b = names[0], names[-1]
        L.append('')
        L.append(f'Changes from `{a}` to `{b}`:')
        for label, key, src in [('object text size', 'object_text_total', st),
                                ('build CPU time', 'cpu_seconds', metas),
                                ('build wall time', 'wall_seconds', metas),
                                ('inlined decisions', 'inlined', st),
                                ('inlined body total', 'inlined_body_total', st),
                                ('speculation work', 'speculation_work', st),
                                ('direct calls', 'direct_calls', st),
                                ('indirect calls', 'indirect_calls', st),
                                ('generic applications', 'generic_applies', st),
                                ('unknown-callee call sites', 'unknown_callee_sites', st)]:
            va, vb = src[a].get(key), src[b].get(key)
            if va and vb is not None:
                L.append(f'- {label}: {fmt_int(va)} -> {fmt_int(vb)} ({100.0 * (vb - va) / va:+.1f}%)')
    L.append('')
    L.append('## Data behind figures 1 to 3 (per callee-size bin: decisions, inlined, aborted or refused, inlined body total)')
    labels = [bin_label(i) for i in range(len(BIN_EDGES))]
    L.append('| bin | ' + ' | '.join(f'{n}: n / inlined / aborted / body' for n in names) + ' |')
    L.append('|---|' + '---|' * len(names))
    for lab in labels:
        cells = []
        any_data = False
        for n in names:
            b = st[n]['bins'].get(lab)
            if b:
                any_data = True
                cells.append(f"{b['n']} / {b['inlined']} / {b['aborted']} / {fmt_int(b['body'])}")
            else:
                cells.append('-')
        if any_data:
            L.append(f'| {lab} | ' + ' | '.join(cells) + ' |')
    L.append('')
    L.append('Figure 4: median simplified/original size ratio per size bin (completed speculations only):')
    for n in names:
        med = st[n].get('shrink_medians') or []
        L.append(f"- `{n}`: " + (', '.join(f"{m['size']}: {m['median_ratio']:.2f}" for m in med) if med else 'no data'))
    L.append('')
    L.append('## Table 2: callees contributing most inlined code (callee; inlined calls; size before inlining; total inlined body; median body)')
    for n in names:
        L.append(f'`{n}`:')
        for t in st[n]['top_callees']:
            L.append(f"- {t['callee']}; {t['calls']}; {fmt_int(t['orig'])}; {fmt_int(t['body'])}; {fmt_int(t['median_body'])}")
    if out['object_dir_deltas']:
        L.append('')
        L.append(f"## Figure 5 and table 3: object text size change by directory, bytes ({names[-1]} minus {names[0]}), largest first")
        for d, v in out['object_dir_deltas'].items():
            L.append(f'- {d}: {v:+,}')
    L.append('')
    L.append('## Table 4: functor applications by functor (applications; inlined; rejected; aborted or refused; size before inlining)')
    for n in names:
        L.append(f'`{n}`:')
        for t in st[n]['functors']:
            L.append(f"- {t['functor']}; {t['applications']}; {t['inlined']}; {t['rejected']}; {t['aborted']}; {fmt_int(t['size'])}")
    if out.get('call_deltas_top'):
        a, b = names[0], names[-1]
        L.append('')
        L.append(f'## Table 5: objects with the largest increase in indirect calls plus generic applications ({b} minus {a}; path; {a}; {b}; change)')
        for p, va, vb, d in out['call_deltas_top']:
            L.append(f'- {p}; {va}; {vb}; {d:+}')
        L.append(f'Largest decreases:')
        for p, va, vb, d in out['call_deltas_bottom']:
            L.append(f'- {p}; {va}; {vb}; {d:+}')
    if out.get('unknown_deltas_top'):
        a, b = names[0], names[-1]
        L.append('')
        L.append(f'## Units with the largest increase in unknown-callee call sites in the reports ({b} minus {a}; unit; {a}; {b}; change)')
        for u, va, vb, d in out['unknown_deltas_top']:
            L.append(f'- {u}; {va}; {vb}; {d:+}')
    if cfg.get('watch_callees'):
        L.append('')
        L.append('## Table 7: watched callees. For each, per configuration: call sites to it by outcome and reason; '
                 'unknown-callee sites inside its own unit; and the call instructions of its own object '
                 '(direct / indirect / generic)')
        for prefix in cfg['watch_callees']:
            L.append(f'`{prefix}`:')
            for n in names:
                w = st[n]['watched'].get(prefix, {})
                parts = [f"{k} {v}" for k, v in w.items() if k not in ('sites', 'unknown_sites_in_unit', 'unit_calls')]
                uc = w.get('unit_calls')
                L.append(f"- `{n}`: {w.get('sites', 0)} sites: " + ('; '.join(parts) or 'none') +
                         f"; unknown-callee sites in the unit: {w.get('unknown_sites_in_unit', 0)}" +
                         (f"; own object calls {uc['direct']} / {uc['indirect']} / {uc['generic']}" if uc else ''))
    L.append('')
    L.append('## Things to keep in mind')
    L.append('- The two configurations measure sizes with different models, so sizes are not '
             'comparable across configurations except where the text says "model units" and '
             'they are compared only within a configuration. Object text sizes in bytes and '
             'counts of decisions are comparable.')
    L.append('- A configuration with a lower small-function size speculates on callees the '
             'other one inlines without speculation, which changes the counts for reasons '
             'unrelated to the criterion.')
    L.append('- Build times include everything the build command did; CPU time is the sum over '
             'all processes, wall time depends on parallelism.')
    L.append('- "Speculation work" counts the whole callee even for speculations that the budget '
             'aborted part way, so it overstates the work of a configuration with aborts.')
    L.append('- In the per-bin data and figure 1, aborted and refused speculations count as not '
             'inlined; in figure 4 they are absent because they have no simplified size.')
    L.append('- Decisions from every optimisation level are pooled.')
    L.append('- Call instruction counts come from disassembling the objects: a direct call is `bl` or '
             '`call symbol`, an indirect call is `blr` or `call *reg`, and a generic application is a '
             'relocation to caml_applyN or caml_sendN (the runtime helpers used when the callee or its '
             'arity is unknown). They count call sites in the code, not calls executed.')
    L.append('- Unknown-callee call sites are those the inlining report marks as calls Flambda 2 could '
             'not make direct; they overlap with, but are not the same as, the indirect call instructions.')
    L.append('- The figures are in the `figures/` directory next to this file if you want to look at them.')
    with open(os.path.join(data_dir, 'NARRATIVE_PROMPT.md'), 'w') as fh:
        fh.write('\n'.join(L) + '\n')


# --------------------------------------------------------------------------
# render: the PDF
# --------------------------------------------------------------------------

def parse_narrative(path):
    sections = {}
    if not path or not os.path.exists(path):
        return sections
    cur = None
    with open(path) as fh:
        for line in fh:
            m = re.match(r'^##\s+(\S+)', line)
            if m:
                cur = m.group(1).strip('`')
                sections[cur] = []
            elif cur is not None:
                sections[cur].append(line.rstrip('\n'))
    return {k: '\n'.join(v).strip() for k, v in sections.items()}


def md_inline(text):
    t = html.escape(text)
    t = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', t)
    t = re.sub(r'`(.+?)`', r'<font face="Courier" size="8.5">\1</font>', t)
    return t


def narrative_flowables(text, styles):
    from reportlab.platypus import Paragraph, Spacer
    out = []
    if not text:
        out.append(Paragraph('<i>Commentary to be written from NARRATIVE_PROMPT.md.</i>', styles['note']))
        return out
    para = []
    def flush():
        if para:
            out.append(Paragraph(md_inline(' '.join(para)), styles['body']))
            para.clear()
    for line in text.split('\n'):
        s = line.strip()
        if not s:
            flush()
        elif s.startswith('- ') or s.startswith('* '):
            flush()
            out.append(Paragraph(md_inline(s[2:]), styles['bullet'], bulletText='•'))
        else:
            para.append(s)
    flush()
    return out


def render(data_dir, out_pdf, narrative):
    need('reportlab')
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (Image, KeepTogether, PageBreak, Paragraph,
                                    SimpleDocTemplate, Spacer, Table, TableStyle)
    with open(os.path.join(data_dir, 'stats.json')) as fh:
        out = json.load(fh)
    with open(os.path.join(data_dir, 'config.json')) as fh:
        cfg = json.load(fh)
    nar = parse_narrative(narrative)
    names = out['configs']
    st, metas = out['stats'], out['metas']
    ink, ink2, rule, band = (colors.HexColor('#0b0b0b'), colors.HexColor('#52514e'),
                             colors.HexColor('#c3c2b7'), colors.HexColor('#f3f2ee'))
    base = ParagraphStyle('base', fontName='Helvetica', fontSize=9.5, leading=13, textColor=ink)
    styles = {
        'title': ParagraphStyle('t', parent=base, fontName='Helvetica-Bold', fontSize=18, leading=22, spaceAfter=4),
        'sub': ParagraphStyle('s', parent=base, textColor=ink2, fontSize=9, leading=12, spaceAfter=10),
        'h2': ParagraphStyle('h', parent=base, fontName='Helvetica-Bold', fontSize=12, leading=15, spaceBefore=10, spaceAfter=4, keepWithNext=1),
        'body': ParagraphStyle('b', parent=base, spaceAfter=5),
        'bullet': ParagraphStyle('bl', parent=base, leftIndent=12, bulletIndent=2, spaceAfter=2),
        'caption': ParagraphStyle('c', parent=base, fontSize=8, leading=10.5, textColor=ink2, spaceBefore=2, spaceAfter=8),
        'note': ParagraphStyle('n', parent=base, fontSize=8.5, leading=11, textColor=ink2, spaceAfter=6),
        'th': ParagraphStyle('th', parent=base, fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=ink2),
        'td': ParagraphStyle('td', parent=base, fontSize=8.5, leading=10.5),
    }
    W = A4[0] - 2 * 16 * mm

    def table(data, widths, align_right_from=1, header=True):
        t = Table(data, colWidths=widths, repeatRows=1 if header else 0)
        ts = TableStyle([
            ('FONT', (0, 0), (-1, -1), 'Helvetica', 8.5), ('TEXTCOLOR', (0, 0), (-1, -1), ink),
            ('ALIGN', (align_right_from, 1), (-1, -1), 'RIGHT'), ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LINEBELOW', (0, 0), (-1, 0), 0.8, rule), ('LINEBELOW', (0, 1), (-1, -1), 0.3, colors.HexColor('#e1e0d9')),
            ('TOPPADDING', (0, 0), (-1, -1), 3), ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
            ('LEFTPADDING', (0, 0), (-1, -1), 4), ('RIGHTPADDING', (0, 0), (-1, -1), 4)])
        for i in range(2, len(data), 2):
            ts.add('BACKGROUND', (0, i), (-1, i), band)
        t.setStyle(ts)
        return t

    def figure(name, number, caption):
        path = os.path.join(data_dir, 'figures', name)
        if not os.path.exists(path):
            return []
        from reportlab.lib.utils import ImageReader
        iw, ih = ImageReader(path).getSize()
        img = Image(path, width=W, height=W * ih / iw)
        return [KeepTogether([img, Paragraph(f'<b>Figure {number}.</b> {html.escape(caption)}', styles['caption'])])]

    story = []
    story.append(Paragraph(html.escape(cfg['title']), styles['title']))
    m0 = metas[names[0]]
    story.append(Paragraph(html.escape(
        f"Generated {out['generated'][:10]} on {m0['host']} ({m0['machine']}); tree {m0['tree']} at "
        f"{', '.join(sorted({metas[n]['commit'] for n in names}))}. Sizes quoted in model units are the "
        f"{out['arch']} estimates of each configuration's own code size model and are not comparable "
        f"between configurations; byte counts and decision counts are."), styles['sub']))
    story.append(Paragraph('Summary', styles['h2']))
    story += narrative_flowables(nar.get('summary'), styles)

    # table 1
    two = len(names) == 2
    rows = [[Paragraph('metric', styles['th'])] + [Paragraph(html.escape(n), styles['th']) for n in names]
            + ([Paragraph('change', styles['th'])] if two else [])]
    def trow(label, key, fmt=fmt_int, src=st, comparable=True):
        cells = [fmt(src[n][key]) if src[n].get(key) is not None else 'n/a' for n in names]
        if two:
            a, b = src[names[0]].get(key), src[names[1]].get(key)
            cells.append(f'{100.0 * (b - a) / a:+.1f}%' if comparable and a and b is not None else '')
        rows.append([Paragraph(html.escape(label), styles['td'])] + cells)
    trow('build wall time (s)', 'wall_seconds', lambda x: f'{x:.0f}', metas)
    trow('build CPU time (s)', 'cpu_seconds', lambda x: f'{x:.0f}', metas)
    trow('OCaml object text size (bytes)', 'object_text_total')
    trow('speculative decisions (all outcomes)', 'decisions')
    trow('judged after a full speculation', 'decided')
    trow('aborted by the budget', 'aborted')
    trow('refused before speculating', 'budget_refused')
    rows.append([Paragraph('functor applications: speculated / inlined', styles['td'])] +
                [f"{fmt_int(st[n]['functor_decisions'])} / {fmt_int(st[n]['functor_inlined'])}" for n in names]
                + ([''] if two else []))
    trow('inlined', 'inlined')
    trow('rejected', 'rejected')
    trow('share inlined', 'inlined_share', lambda x: f'{100 * x:.1f}%', comparable=False)
    trow('distinct callees inlined', 'distinct_callees_inlined')
    trow('inlined body size, total (model units)', 'inlined_body_total', comparable=False)
    trow('inlined body size, median (model units)', 'inlined_body_median', lambda x: f'{x:.0f}', comparable=False)
    trow('speculation work (model units)', 'speculation_work', comparable=False)
    trow('direct call instructions', 'direct_calls')
    trow('indirect call instructions', 'indirect_calls')
    trow('generic applications (caml_apply, caml_send)', 'generic_applies')
    trow('unknown-callee call sites (reports)', 'unknown_callee_sites')
    story.append(Spacer(1, 4))
    ncols = len(names) + (1 if two else 0)
    story.append(KeepTogether([table(rows, [W * 0.46] + [W * 0.54 / ncols] * ncols),
                               Paragraph('<b>Table 1.</b> Headline measurements per configuration.', styles['caption'])]))

    story.append(Paragraph('Where inlining happens', styles['h2']))
    story += figure('probability.png', 1, 'Share of speculative decisions that inline, by callee size before inlining, for each configuration. Callees below a configuration\'s small function size are inlined without speculation and do not appear.')
    story += narrative_flowables(nar.get('fig-probability'), styles)
    story += figure('inlined.png', 2, 'Number of inlined decisions by callee size.')
    story += narrative_flowables(nar.get('fig-inlined'), styles)
    story.append(Paragraph('Code growth', styles['h2']))
    story += figure('body.png', 3, 'Total size of the bodies inlined after speculation, by callee size, in each configuration\'s own model units.')
    story += narrative_flowables(nar.get('fig-body'), styles)
    story += figure('shrink.png', 4, 'Ratio of the simplified size to the size before inlining, one point per completed speculation, with the median per size bin; aborted speculations have no simplified size and are absent.')
    story += narrative_flowables(nar.get('fig-shrink'), styles)
    if len(names) >= 2 and os.path.exists(os.path.join(data_dir, 'figures', 'objects.png')):
        story.append(Paragraph('Generated code size', styles['h2']))
        story += figure('objects.png', 5, f'Directories with the largest change in OCaml object text size, {names[-1]} minus {names[0]} (red: larger, blue: smaller).')
        story += narrative_flowables(nar.get('fig-objects'), styles)
        rows = [[Paragraph('directory', styles['th']), Paragraph('change (bytes)', styles['th'])]]
        for d, v in list(out['object_dir_deltas'].items())[:14]:
            rows.append([Paragraph(html.escape(d), styles['td']), f'{v:+,}'])
        story.append(KeepTogether([table(rows, [W * 0.7, W * 0.3]),
                                   Paragraph('<b>Table 3.</b> Object text size change by directory, largest first.', styles['caption'])]))

    story.append(Paragraph('Callees contributing most inlined code', styles['h2']))
    for n in names:
        rows = [[Paragraph(h, styles['th']) for h in ('callee', 'calls', 'size before', 'inlined total', 'median body')]]
        for t in st[n]['top_callees']:
            rows.append([Paragraph(html.escape(t['callee']), styles['td']), str(t['calls']), fmt_int(t['orig']),
                         fmt_int(t['body']), fmt_int(t['median_body'])])
        story.append(KeepTogether([table(rows, [W * 0.52, W * 0.1, W * 0.12, W * 0.14, W * 0.12]),
                                   Paragraph(f'<b>Table 2 ({html.escape(n)}).</b> Callees by total inlined body size ({html.escape(metas[n]["size_units"])}).', styles['caption'])]))
    story += narrative_flowables(nar.get('table-callees'), styles)

    story.append(Paragraph('Functor applications', styles['h2']))
    for n in names:
        rows = [[Paragraph(h, styles['th']) for h in ('functor', 'applications', 'inlined', 'rejected', 'aborted or refused', 'size before')]]
        for t in st[n]['functors']:
            rows.append([Paragraph(html.escape(t['functor']), styles['td']), str(t['applications']), str(t['inlined']),
                         str(t['rejected']), str(t['aborted']), fmt_int(t['size'])])
        if len(rows) > 1:
            story.append(KeepTogether([table(rows, [W * 0.46, W * 0.12, W * 0.09, W * 0.09, W * 0.13, W * 0.11]),
                                       Paragraph(f'<b>Table 4 ({html.escape(n)}).</b> Functor applications by functor, most applied first ({html.escape(metas[n]["size_units"])}).', styles['caption'])]))
    story += narrative_flowables(nar.get('functors'), styles)

    if out.get('call_deltas_top'):
        story.append(Paragraph('Direct and indirect calls', styles['h2']))
        a, b = names[0], names[-1]
        rows = [[Paragraph(h, styles['th']) for h in ('object', a, b, 'change')]]
        for p, va, vb, d in out['call_deltas_top'][:12]:
            rows.append([Paragraph(html.escape(p.split('/')[-1]), styles['td']), str(va), str(vb), f'{d:+}'])
        story.append(KeepTogether([table(rows, [W * 0.55, W * 0.15, W * 0.15, W * 0.15]),
                                   Paragraph('<b>Table 5.</b> Objects with the largest increase in indirect calls plus generic applications.', styles['caption'])]))
        if out.get('unknown_deltas_top'):
            rows = [[Paragraph(h, styles['th']) for h in ('unit', a, b, 'change')]]
            for u, va, vb, d in out['unknown_deltas_top'][:12]:
                rows.append([Paragraph(html.escape(u), styles['td']), str(va), str(vb), f'{d:+}'])
            story.append(KeepTogether([table(rows, [W * 0.55, W * 0.15, W * 0.15, W * 0.15]),
                                       Paragraph('<b>Table 6.</b> Units with the largest increase in call sites whose callee was unknown to Flambda 2.', styles['caption'])]))
        story += narrative_flowables(nar.get('calls'), styles)

    if cfg.get('watch_callees'):
        story.append(Paragraph('Watched callees', styles['h2']))
        for prefix in cfg['watch_callees']:
            rows = [[Paragraph(h, styles['th']) for h in ('outcome and reason',) + tuple(names)]]
            keys = [k for k in REASONS if any(st[n]['watched'].get(prefix, {}).get(k) for n in names)]
            for k in keys:
                rows.append([Paragraph(html.escape(k), styles['td'])] + [str(st[n]['watched'].get(prefix, {}).get(k, 0)) for n in names])
            rows.append([Paragraph('<b>call sites in total</b>', styles['td'])] + [str(st[n]['watched'].get(prefix, {}).get('sites', 0)) for n in names])
            rows.append([Paragraph('unknown-callee sites inside its unit', styles['td'])] + [str(st[n]['watched'].get(prefix, {}).get('unknown_sites_in_unit', 0)) for n in names])
            if any(st[n]['watched'].get(prefix, {}).get('unit_calls') for n in names):
                rows.append([Paragraph('its object: direct / indirect / generic calls', styles['td'])] +
                            [(lambda uc: f"{uc['direct']} / {uc['indirect']} / {uc['generic']}" if uc else 'n/a')(st[n]['watched'].get(prefix, {}).get('unit_calls')) for n in names])
            story.append(KeepTogether([table(rows, [W * 0.5] + [W * 0.5 / len(names)] * len(names)),
                                       Paragraph(f'<b>Table 7.</b> Call sites to {html.escape(prefix)} by outcome.', styles['caption'])]))
        story += narrative_flowables(nar.get('watched'), styles)

    story.append(Paragraph('Conclusions', styles['h2']))
    story += narrative_flowables(nar.get('conclusions'), styles)

    story.append(PageBreak())
    story.append(Paragraph('Method and configurations', styles['h2']))
    for n in names:
        m = metas[n]
        story.append(Paragraph(md_inline(
            f"**{n}**: {m['label']}. " + (f"Clean: `{m['clean']}`. " if m['clean'] else '') +
            f"Build: `{m['command']}` with {', '.join(f'`{k}={v}`' for k, v in m['env'].items()) or 'no extra environment'}. "
            f"Reports: {m['report_summary']['files']} files, {m['report_summary']['decisions']} call-site decisions "
            f"(outcomes {json.dumps(m['report_summary']['outcomes'])}). Objects: {st[n]['object_count']} files."), styles['note']))
    story.append(Paragraph(md_inline(
        'Decisions are read from the `.inlining.org` reports with `tools/inlining_decisions.py`; a callee\'s size '
        'before inlining is the one its call site saw. Object sizes are those of `.o` files that have a `.cmx` '
        f"beside them (measure: {', '.join(sorted({metas[n].get('object_size_measure', 'text section') for n in names}))}). "
        'Decisions from every optimisation level are pooled; in figures 1 to 3 an aborted or refused speculation '
        f'counts as a decision not to inline. Bins with fewer than {MIN_BIN} decisions are omitted from the figures. '
        'Functor applications are counted in the totals but excluded from the inlined counts and the size '
        'figures.'), styles['note']))
    doc = SimpleDocTemplate(out_pdf, pagesize=A4, leftMargin=16 * mm, rightMargin=16 * mm,
                            topMargin=14 * mm, bottomMargin=14 * mm, title=cfg['title'])
    doc.build(story)
    print(f'wrote {out_pdf}')


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)
    p = sub.add_parser('run', help='build each configuration, harvest, analyse')
    p.add_argument('--preset', choices=sorted(PRESETS))
    p.add_argument('--config', help='JSON configuration file (see example-config)')
    p.add_argument('--tree', help='override the tree the commands run in')
    p.add_argument('--data', default='inlining-report-data', help='directory for harvested data and outputs')
    p.add_argument('--skip-build', action='store_true', help='harvest what is already built (keeps recorded build times)')
    p.add_argument('--only', action='append', help='only this configuration (repeatable), e.g. to re-harvest one')
    p = sub.add_parser('analyse', help='recompute statistics, figures, prompt and draft from harvested data')
    p.add_argument('--data', default='inlining-report-data')
    p = sub.add_parser('render', help='assemble the final PDF from the analysis and the narrative')
    p.add_argument('--data', default='inlining-report-data')
    p.add_argument('--narrative', help='narrative Markdown (default: <data>/narrative.md)')
    p.add_argument('out_pdf')
    sub.add_parser('example-config', help='print a configuration file to adapt for another tree')
    args = ap.parse_args()
    if args.cmd == 'run':
        cmd_run(args)
    elif args.cmd == 'analyse':
        analyse(os.path.abspath(args.data))
    elif args.cmd == 'render':
        data = os.path.abspath(args.data)
        nar = args.narrative or os.path.join(data, 'narrative.md')
        render(data, args.out_pdf, nar if os.path.exists(nar) else None)
    elif args.cmd == 'example-config':
        ex = json.loads(json.dumps(PRESETS['oxcaml']))
        ex['tree'] = '/path/to/tree'
        ex['title'] = 'Speculative inlining on <project>'
        ex['report_dirs'] = ex['object_dirs'] = ['_build/default']
        for c in ex['configs']:
            c['clean'] = 'dune clean'
            c['command'] = 'dune build @install'
            c['env'] = {'OCAMLPARAM': c['env']['BUILD_OCAMLPARAM']}
        print(json.dumps(ex, indent=2))


if __name__ == '__main__':
    main()
