/* GENERATED by tools/avx512gen/genmem.py -- do not edit. */
#include <assert.h>

#include <caml/simd.h>
#include <caml/mlvalues.h>
#include <stdint.h>
#include <stdlib.h>
intnat vec_aligned_alloc(intnat align, intnat size) {
    void* p = NULL;
    if (posix_memalign(&p, (size_t)align, (size_t)size)) return 0;
    return (intnat)p;
}
int64_t mem_w(intnat a, intnat i){ int64_t* p=(int64_t*)a; return p[i]; }

#define BUILTIN(name) void name() { assert(0); }
BUILTIN(caml_avx512f_int32x8_load);
BUILTIN(caml_avx512f_int64x4_load);
BUILTIN(caml_avx512bw_int16x16_loadu);
BUILTIN(caml_avx512f_int32x8_loadu);
BUILTIN(caml_avx512f_int64x4_loadu);
BUILTIN(caml_avx512bw_int8x32_loadu);
BUILTIN(caml_avx512f_int32x8_load_mask);
BUILTIN(caml_avx512f_int64x4_load_mask);
BUILTIN(caml_avx512f_float64x4_load_mask);
BUILTIN(caml_avx512f_float32x8_load_mask);
BUILTIN(caml_avx512bw_int16x16_loadu_mask);
BUILTIN(caml_avx512f_int32x8_loadu_mask);
BUILTIN(caml_avx512f_int64x4_loadu_mask);
BUILTIN(caml_avx512bw_int8x32_loadu_mask);
BUILTIN(caml_avx512f_float64x4_loadu_mask);
BUILTIN(caml_avx512f_float32x8_loadu_mask);
BUILTIN(caml_avx512f_int32x8_store_mask);
BUILTIN(caml_avx512f_int64x4_store_mask);
BUILTIN(caml_avx512f_float64x4_store_mask);
BUILTIN(caml_avx512f_float32x8_store_mask);
BUILTIN(caml_avx512bw_int16x16_storeu_mask);
BUILTIN(caml_avx512f_int32x8_storeu_mask);
BUILTIN(caml_avx512f_int64x4_storeu_mask);
BUILTIN(caml_avx512bw_int8x32_storeu_mask);
BUILTIN(caml_avx512f_float64x4_storeu_mask);
BUILTIN(caml_avx512f_float32x8_storeu_mask);
BUILTIN(caml_avx512f_int32x8_load_maskz);
BUILTIN(caml_avx512f_int64x4_load_maskz);
BUILTIN(caml_avx512f_float64x4_load_maskz);
BUILTIN(caml_avx512f_float32x8_load_maskz);
BUILTIN(caml_avx512bw_int16x16_loadu_maskz);
BUILTIN(caml_avx512f_int32x8_loadu_maskz);
BUILTIN(caml_avx512f_int64x4_loadu_maskz);
BUILTIN(caml_avx512bw_int8x32_loadu_maskz);
BUILTIN(caml_avx512f_float64x4_loadu_maskz);
BUILTIN(caml_avx512f_float32x8_loadu_maskz);
BUILTIN(caml_avx512f_int32x8_store);
BUILTIN(caml_avx512f_int64x4_store);
BUILTIN(caml_avx512bw_int16x16_storeu);
BUILTIN(caml_avx512f_int32x8_storeu);
BUILTIN(caml_avx512f_int64x4_storeu);
BUILTIN(caml_avx512bw_int8x32_storeu);
BUILTIN(caml_avx512f_int32x16_load);
BUILTIN(caml_avx512f_int64x8_load);
BUILTIN(caml_avx512f_float64x8_load);
BUILTIN(caml_avx512f_float32x16_load);
BUILTIN(caml_avx512bw_int16x32_loadu);
BUILTIN(caml_avx512f_int32x16_loadu);
BUILTIN(caml_avx512f_int64x8_loadu);
BUILTIN(caml_avx512bw_int8x64_loadu);
BUILTIN(caml_avx512f_float64x8_loadu);
BUILTIN(caml_avx512f_float32x16_loadu);
BUILTIN(caml_avx512f_int32x16_load_mask);
BUILTIN(caml_avx512f_int64x8_load_mask);
BUILTIN(caml_avx512f_float64x8_load_mask);
BUILTIN(caml_avx512f_float32x16_load_mask);
BUILTIN(caml_avx512bw_int16x32_loadu_mask);
BUILTIN(caml_avx512f_int32x16_loadu_mask);
BUILTIN(caml_avx512f_int64x8_loadu_mask);
BUILTIN(caml_avx512bw_int8x64_loadu_mask);
BUILTIN(caml_avx512f_float64x8_loadu_mask);
BUILTIN(caml_avx512f_float32x16_loadu_mask);
BUILTIN(caml_avx512f_int32x16_store_mask);
BUILTIN(caml_avx512f_int64x8_store_mask);
BUILTIN(caml_avx512f_float64x8_store_mask);
BUILTIN(caml_avx512f_float32x16_store_mask);
BUILTIN(caml_avx512bw_int16x32_storeu_mask);
BUILTIN(caml_avx512f_int32x16_storeu_mask);
BUILTIN(caml_avx512f_int64x8_storeu_mask);
BUILTIN(caml_avx512bw_int8x64_storeu_mask);
BUILTIN(caml_avx512f_float64x8_storeu_mask);
BUILTIN(caml_avx512f_float32x16_storeu_mask);
BUILTIN(caml_avx512f_int32x16_load_maskz);
BUILTIN(caml_avx512f_int64x8_load_maskz);
BUILTIN(caml_avx512f_float64x8_load_maskz);
BUILTIN(caml_avx512f_float32x16_load_maskz);
BUILTIN(caml_avx512bw_int16x32_loadu_maskz);
BUILTIN(caml_avx512f_int32x16_loadu_maskz);
BUILTIN(caml_avx512f_int64x8_loadu_maskz);
BUILTIN(caml_avx512bw_int8x64_loadu_maskz);
BUILTIN(caml_avx512f_float64x8_loadu_maskz);
BUILTIN(caml_avx512f_float32x16_loadu_maskz);
BUILTIN(caml_avx512f_int32x16_store);
BUILTIN(caml_avx512f_int64x8_store);
BUILTIN(caml_avx512f_float64x8_store);
BUILTIN(caml_avx512f_float32x16_store);
BUILTIN(caml_avx512bw_int16x32_storeu);
BUILTIN(caml_avx512f_int32x16_storeu);
BUILTIN(caml_avx512f_int64x8_storeu);
BUILTIN(caml_avx512bw_int8x64_storeu);
BUILTIN(caml_avx512f_float64x8_storeu);
BUILTIN(caml_avx512f_float32x16_storeu);
BUILTIN(caml_avx512f_int32x4_load);
BUILTIN(caml_avx512f_int64x2_load);
BUILTIN(caml_avx512bw_int16x8_loadu);
BUILTIN(caml_avx512f_int32x4_loadu);
BUILTIN(caml_avx512f_int64x2_loadu);
BUILTIN(caml_avx512bw_int8x16_loadu);
BUILTIN(caml_avx512f_int32x4_load_mask);
BUILTIN(caml_avx512f_int64x2_load_mask);
BUILTIN(caml_avx512f_float64x2_load_mask);
BUILTIN(caml_avx512f_float32x4_load_mask);
BUILTIN(caml_avx512bw_int16x8_loadu_mask);
BUILTIN(caml_avx512f_int32x4_loadu_mask);
BUILTIN(caml_avx512f_int64x2_loadu_mask);
BUILTIN(caml_avx512bw_int8x16_loadu_mask);
BUILTIN(caml_avx512f_float64x2_loadu_mask);
BUILTIN(caml_avx512f_float32x4_loadu_mask);
BUILTIN(caml_avx512f_int32x4_store_mask);
BUILTIN(caml_avx512f_int64x2_store_mask);
BUILTIN(caml_avx512f_float64x2_store_mask);
BUILTIN(caml_avx512f_float32x4_store_mask);
BUILTIN(caml_avx512bw_int16x8_storeu_mask);
BUILTIN(caml_avx512f_int32x4_storeu_mask);
BUILTIN(caml_avx512f_int64x2_storeu_mask);
BUILTIN(caml_avx512bw_int8x16_storeu_mask);
BUILTIN(caml_avx512f_float64x2_storeu_mask);
BUILTIN(caml_avx512f_float32x4_storeu_mask);
BUILTIN(caml_avx512f_int32x4_load_maskz);
BUILTIN(caml_avx512f_int64x2_load_maskz);
BUILTIN(caml_avx512f_float64x2_load_maskz);
BUILTIN(caml_avx512f_float32x4_load_maskz);
BUILTIN(caml_avx512bw_int16x8_loadu_maskz);
BUILTIN(caml_avx512f_int32x4_loadu_maskz);
BUILTIN(caml_avx512f_int64x2_loadu_maskz);
BUILTIN(caml_avx512bw_int8x16_loadu_maskz);
BUILTIN(caml_avx512f_float64x2_loadu_maskz);
BUILTIN(caml_avx512f_float32x4_loadu_maskz);
BUILTIN(caml_avx512f_int32x4_store);
BUILTIN(caml_avx512f_int64x2_store);
BUILTIN(caml_avx512bw_int16x8_storeu);
BUILTIN(caml_avx512f_int32x4_storeu);
BUILTIN(caml_avx512f_int64x2_storeu);
BUILTIN(caml_avx512bw_int8x16_storeu);
BUILTIN(caml_avx512f_float32x8_broadcast_f32x4);
BUILTIN(caml_avx512f_float32x16_broadcast_f32x4);
BUILTIN(caml_avx512dq_float64x4_broadcast_f64x2);
BUILTIN(caml_avx512f_int32x8_broadcast_i32x4);
BUILTIN(caml_avx512f_int32x16_broadcast_i32x4);
BUILTIN(caml_avx512dq_int64x4_broadcast_i64x2);
BUILTIN(caml_avx512dq_int64x8_broadcast_i64x2);
BUILTIN(caml_avx512dq_int32x16_broadcast_i32x8);
BUILTIN(caml_avx512f_int64x8_broadcast_i64x4);
BUILTIN(caml_avx512f_int32x4_broadcast_d);
BUILTIN(caml_avx512f_int32x8_broadcast_d);
BUILTIN(caml_avx512f_int32x16_broadcast_d);
BUILTIN(caml_avx512f_int64x2_broadcast_q);
BUILTIN(caml_avx512f_int64x4_broadcast_q);
BUILTIN(caml_avx512f_int64x8_broadcast_q);
BUILTIN(caml_avx512f_int32x8_expandloadu_mask);
BUILTIN(caml_avx512f_int64x4_expandloadu_mask);
BUILTIN(caml_avx512f_float64x4_expandloadu_mask);
BUILTIN(caml_avx512f_float32x8_expandloadu_mask);
BUILTIN(caml_avx512f_int32x8_expandloadu_maskz);
BUILTIN(caml_avx512f_int64x4_expandloadu_maskz);
BUILTIN(caml_avx512f_float64x4_expandloadu_maskz);
BUILTIN(caml_avx512f_float32x8_expandloadu_maskz);
BUILTIN(caml_avx512f_int32x16_expandloadu_mask);
BUILTIN(caml_avx512f_int64x8_expandloadu_mask);
BUILTIN(caml_avx512f_float64x8_expandloadu_mask);
BUILTIN(caml_avx512f_float32x16_expandloadu_mask);
BUILTIN(caml_avx512f_int32x16_expandloadu_maskz);
BUILTIN(caml_avx512f_int64x8_expandloadu_maskz);
BUILTIN(caml_avx512f_float64x8_expandloadu_maskz);
BUILTIN(caml_avx512f_float32x16_expandloadu_maskz);
BUILTIN(caml_avx512f_int32x4_expandloadu_mask);
BUILTIN(caml_avx512f_int64x2_expandloadu_mask);
BUILTIN(caml_avx512f_float64x2_expandloadu_mask);
BUILTIN(caml_avx512f_float32x4_expandloadu_mask);
BUILTIN(caml_avx512f_int32x4_expandloadu_maskz);
BUILTIN(caml_avx512f_int64x2_expandloadu_maskz);
BUILTIN(caml_avx512f_float64x2_expandloadu_maskz);
BUILTIN(caml_avx512f_float32x4_expandloadu_maskz);
BUILTIN(caml_avx512f_int32x8_compressstoreu_mask);
BUILTIN(caml_avx512f_int64x4_compressstoreu_mask);
BUILTIN(caml_avx512f_float64x4_compressstoreu_mask);
BUILTIN(caml_avx512f_float32x8_compressstoreu_mask);
BUILTIN(caml_avx512f_int32x16_compressstoreu_mask);
BUILTIN(caml_avx512f_int64x8_compressstoreu_mask);
BUILTIN(caml_avx512f_float64x8_compressstoreu_mask);
BUILTIN(caml_avx512f_float32x16_compressstoreu_mask);
BUILTIN(caml_avx512f_int32x4_compressstoreu_mask);
BUILTIN(caml_avx512f_int64x2_compressstoreu_mask);
BUILTIN(caml_avx512f_float64x2_compressstoreu_mask);
BUILTIN(caml_avx512f_float32x4_compressstoreu_mask);
BUILTIN(caml_avx512bw_cvt_int16x16_int8x16_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x8_int16x8_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x8_int8x8_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int16x4_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int32x4_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int8x4_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x16_int8x16_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x8_int16x8_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x8_int8x8_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int16x4_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int32x4_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int8x4_saturating_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x16_int8x16_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x8_int16x8_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x8_int8x8_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int16x4_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int32x4_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x4_int8x4_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x32_int8x32_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x16_int16x16_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x16_int8x16_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int16x8_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int32x8_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int8x8_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x32_int8x32_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x16_int16x16_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x16_int8x16_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int16x8_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int32x8_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int8x8_saturating_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x32_int8x32_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x16_int16x16_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x16_int8x16_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int16x8_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int32x8_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x8_int8x8_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x8_int8x8_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x4_int16x4_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x4_int8x4_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int16x2_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int32x2_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int8x2_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x8_int8x8_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x4_int16x4_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x4_int8x4_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int16x2_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int32x2_saturating_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int8x2_saturating_storeu_mask);
BUILTIN(caml_avx512bw_cvt_int16x8_int8x8_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x4_int16x4_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int32x4_int8x4_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int16x2_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int32x2_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_cvt_int64x2_int8x2_saturating_unsigned_storeu_mask);
BUILTIN(caml_avx512f_int32x8_i32scatter_mask);
BUILTIN(caml_avx512f_int64x4_i32scatter_mask);
BUILTIN(caml_avx512f_float64x4_i32scatter_mask);
BUILTIN(caml_avx512f_float32x8_i32scatter_mask);
BUILTIN(caml_avx512f_int32x4_i64scatter_mask);
BUILTIN(caml_avx512f_int64x4_i64scatter_mask);
BUILTIN(caml_avx512f_float64x4_i64scatter_mask);
BUILTIN(caml_avx512f_float32x4_i64scatter_mask);
BUILTIN(caml_avx512f_int32x16_i32scatter_mask);
BUILTIN(caml_avx512f_int64x8_i32scatter_mask);
BUILTIN(caml_avx512f_float64x8_i32scatter_mask);
BUILTIN(caml_avx512f_float32x16_i32scatter_mask);
BUILTIN(caml_avx512f_int32x8_i64scatter_mask);
BUILTIN(caml_avx512f_int64x8_i64scatter_mask);
BUILTIN(caml_avx512f_float64x8_i64scatter_mask);
BUILTIN(caml_avx512f_float32x8_i64scatter_mask);
BUILTIN(caml_avx512f_int32x4_i32scatter_mask);
BUILTIN(caml_avx512f_int64x2_i32scatter_mask);
BUILTIN(caml_avx512f_float64x2_i32scatter_mask);
BUILTIN(caml_avx512f_float32x4_i32scatter_mask);
BUILTIN(caml_avx512f_int64x2_i64scatter_mask);
BUILTIN(caml_avx512f_float64x2_i64scatter_mask);
BUILTIN(caml_avx512f_load_mask16);
BUILTIN(caml_avx512bw_load_mask32);
BUILTIN(caml_avx512bw_load_mask64);
BUILTIN(caml_avx512dq_load_mask8);
BUILTIN(caml_avx512f_store_mask16);
BUILTIN(caml_avx512bw_store_mask32);
BUILTIN(caml_avx512bw_store_mask64);
BUILTIN(caml_avx512dq_store_mask8);
#ifdef ARCH_AVX512
#include <immintrin.h>
__m256i c_avx512f_int32x8_load(intnat a)
{
    return _mm256_load_epi32((void const*)a);
}

__m256i c_avx512f_int64x4_load(intnat a)
{
    return _mm256_load_epi64((void const*)a);
}

__m256i c_avx512bw_int16x16_loadu(intnat a)
{
    return _mm256_loadu_epi16((void const*)a);
}

__m256i c_avx512f_int32x8_loadu(intnat a)
{
    return _mm256_loadu_epi32((void const*)a);
}

__m256i c_avx512f_int64x4_loadu(intnat a)
{
    return _mm256_loadu_epi64((void const*)a);
}

__m256i c_avx512bw_int8x32_loadu(intnat a)
{
    return _mm256_loadu_epi8((void const*)a);
}

__m256i c_avx512f_int32x8_load_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_load_epi32(src, (__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int64x4_load_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_load_epi64(src, (__mmask8)k, (void const*)a);
}

__m256d c_avx512f_float64x4_load_mask(__m256d src, intnat a, int64_t k)
{
    return _mm256_mask_load_pd(src, (__mmask8)k, (void const*)a);
}

__m256 c_avx512f_float32x8_load_mask(__m256 src, intnat a, int64_t k)
{
    return _mm256_mask_load_ps(src, (__mmask8)k, (void const*)a);
}

__m256i c_avx512bw_int16x16_loadu_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_loadu_epi16(src, (__mmask16)k, (void const*)a);
}

__m256i c_avx512f_int32x8_loadu_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_loadu_epi32(src, (__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int64x4_loadu_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_loadu_epi64(src, (__mmask8)k, (void const*)a);
}

__m256i c_avx512bw_int8x32_loadu_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_loadu_epi8(src, (__mmask32)k, (void const*)a);
}

__m256d c_avx512f_float64x4_loadu_mask(__m256d src, intnat a, int64_t k)
{
    return _mm256_mask_loadu_pd(src, (__mmask8)k, (void const*)a);
}

__m256 c_avx512f_float32x8_loadu_mask(__m256 src, intnat a, int64_t k)
{
    return _mm256_mask_loadu_ps(src, (__mmask8)k, (void const*)a);
}

intnat c_avx512f_int32x8_store_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_store_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int64x4_store_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_store_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float64x4_store_mask(intnat a, __m256d v, int64_t k)
{
    _mm256_mask_store_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x8_store_mask(intnat a, __m256 v, int64_t k)
{
    _mm256_mask_store_ps((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_int16x16_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_storeu_epi16((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_int32x8_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int64x4_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_storeu_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_int8x32_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_storeu_epi8((void*)a, (__mmask32)k, v); return 0;
}

intnat c_avx512f_float64x4_storeu_mask(intnat a, __m256d v, int64_t k)
{
    _mm256_mask_storeu_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x8_storeu_mask(intnat a, __m256 v, int64_t k)
{
    _mm256_mask_storeu_ps((void*)a, (__mmask8)k, v); return 0;
}

__m256i c_avx512f_int32x8_load_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_load_epi32((__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int64x4_load_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_load_epi64((__mmask8)k, (void const*)a);
}

__m256d c_avx512f_float64x4_load_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_load_pd((__mmask8)k, (void const*)a);
}

__m256 c_avx512f_float32x8_load_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_load_ps((__mmask8)k, (void const*)a);
}

__m256i c_avx512bw_int16x16_loadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_loadu_epi16((__mmask16)k, (void const*)a);
}

__m256i c_avx512f_int32x8_loadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_loadu_epi32((__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int64x4_loadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_loadu_epi64((__mmask8)k, (void const*)a);
}

__m256i c_avx512bw_int8x32_loadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_loadu_epi8((__mmask32)k, (void const*)a);
}

__m256d c_avx512f_float64x4_loadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_loadu_pd((__mmask8)k, (void const*)a);
}

__m256 c_avx512f_float32x8_loadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_loadu_ps((__mmask8)k, (void const*)a);
}

intnat c_avx512f_int32x8_store(intnat a, __m256i v)
{
    _mm256_store_epi32((void*)a, v); return 0;
}

intnat c_avx512f_int64x4_store(intnat a, __m256i v)
{
    _mm256_store_epi64((void*)a, v); return 0;
}

intnat c_avx512bw_int16x16_storeu(intnat a, __m256i v)
{
    _mm256_storeu_epi16((void*)a, v); return 0;
}

intnat c_avx512f_int32x8_storeu(intnat a, __m256i v)
{
    _mm256_storeu_epi32((void*)a, v); return 0;
}

intnat c_avx512f_int64x4_storeu(intnat a, __m256i v)
{
    _mm256_storeu_epi64((void*)a, v); return 0;
}

intnat c_avx512bw_int8x32_storeu(intnat a, __m256i v)
{
    _mm256_storeu_epi8((void*)a, v); return 0;
}

__m512i c_avx512f_int32x16_load(intnat a)
{
    return _mm512_load_epi32((void const*)a);
}

__m512i c_avx512f_int64x8_load(intnat a)
{
    return _mm512_load_epi64((void const*)a);
}

__m512d c_avx512f_float64x8_load(intnat a)
{
    return _mm512_load_pd((void const*)a);
}

__m512 c_avx512f_float32x16_load(intnat a)
{
    return _mm512_load_ps((void const*)a);
}

__m512i c_avx512bw_int16x32_loadu(intnat a)
{
    return _mm512_loadu_epi16((void const*)a);
}

__m512i c_avx512f_int32x16_loadu(intnat a)
{
    return _mm512_loadu_epi32((void const*)a);
}

__m512i c_avx512f_int64x8_loadu(intnat a)
{
    return _mm512_loadu_epi64((void const*)a);
}

__m512i c_avx512bw_int8x64_loadu(intnat a)
{
    return _mm512_loadu_epi8((void const*)a);
}

__m512d c_avx512f_float64x8_loadu(intnat a)
{
    return _mm512_loadu_pd((void const*)a);
}

__m512 c_avx512f_float32x16_loadu(intnat a)
{
    return _mm512_loadu_ps((void const*)a);
}

__m512i c_avx512f_int32x16_load_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_load_epi32(src, (__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int64x8_load_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_load_epi64(src, (__mmask8)k, (void const*)a);
}

__m512d c_avx512f_float64x8_load_mask(__m512d src, intnat a, int64_t k)
{
    return _mm512_mask_load_pd(src, (__mmask8)k, (void const*)a);
}

__m512 c_avx512f_float32x16_load_mask(__m512 src, intnat a, int64_t k)
{
    return _mm512_mask_load_ps(src, (__mmask16)k, (void const*)a);
}

__m512i c_avx512bw_int16x32_loadu_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_loadu_epi16(src, (__mmask32)k, (void const*)a);
}

__m512i c_avx512f_int32x16_loadu_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_loadu_epi32(src, (__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int64x8_loadu_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_loadu_epi64(src, (__mmask8)k, (void const*)a);
}

__m512i c_avx512bw_int8x64_loadu_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_loadu_epi8(src, (__mmask64)k, (void const*)a);
}

__m512d c_avx512f_float64x8_loadu_mask(__m512d src, intnat a, int64_t k)
{
    return _mm512_mask_loadu_pd(src, (__mmask8)k, (void const*)a);
}

__m512 c_avx512f_float32x16_loadu_mask(__m512 src, intnat a, int64_t k)
{
    return _mm512_mask_loadu_ps(src, (__mmask16)k, (void const*)a);
}

intnat c_avx512f_int32x16_store_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_store_epi32((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_int64x8_store_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_store_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float64x8_store_mask(intnat a, __m512d v, int64_t k)
{
    _mm512_mask_store_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x16_store_mask(intnat a, __m512 v, int64_t k)
{
    _mm512_mask_store_ps((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512bw_int16x32_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_storeu_epi16((void*)a, (__mmask32)k, v); return 0;
}

intnat c_avx512f_int32x16_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_storeu_epi32((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_int64x8_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_storeu_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_int8x64_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_storeu_epi8((void*)a, (__mmask64)k, v); return 0;
}

intnat c_avx512f_float64x8_storeu_mask(intnat a, __m512d v, int64_t k)
{
    _mm512_mask_storeu_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x16_storeu_mask(intnat a, __m512 v, int64_t k)
{
    _mm512_mask_storeu_ps((void*)a, (__mmask16)k, v); return 0;
}

__m512i c_avx512f_int32x16_load_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_load_epi32((__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int64x8_load_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_load_epi64((__mmask8)k, (void const*)a);
}

__m512d c_avx512f_float64x8_load_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_load_pd((__mmask8)k, (void const*)a);
}

__m512 c_avx512f_float32x16_load_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_load_ps((__mmask16)k, (void const*)a);
}

__m512i c_avx512bw_int16x32_loadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_loadu_epi16((__mmask32)k, (void const*)a);
}

__m512i c_avx512f_int32x16_loadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_loadu_epi32((__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int64x8_loadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_loadu_epi64((__mmask8)k, (void const*)a);
}

__m512i c_avx512bw_int8x64_loadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_loadu_epi8((__mmask64)k, (void const*)a);
}

__m512d c_avx512f_float64x8_loadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_loadu_pd((__mmask8)k, (void const*)a);
}

__m512 c_avx512f_float32x16_loadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_loadu_ps((__mmask16)k, (void const*)a);
}

intnat c_avx512f_int32x16_store(intnat a, __m512i v)
{
    _mm512_store_epi32((void*)a, v); return 0;
}

intnat c_avx512f_int64x8_store(intnat a, __m512i v)
{
    _mm512_store_epi64((void*)a, v); return 0;
}

intnat c_avx512f_float64x8_store(intnat a, __m512d v)
{
    _mm512_store_pd((void*)a, v); return 0;
}

intnat c_avx512f_float32x16_store(intnat a, __m512 v)
{
    _mm512_store_ps((void*)a, v); return 0;
}

intnat c_avx512bw_int16x32_storeu(intnat a, __m512i v)
{
    _mm512_storeu_epi16((void*)a, v); return 0;
}

intnat c_avx512f_int32x16_storeu(intnat a, __m512i v)
{
    _mm512_storeu_epi32((void*)a, v); return 0;
}

intnat c_avx512f_int64x8_storeu(intnat a, __m512i v)
{
    _mm512_storeu_epi64((void*)a, v); return 0;
}

intnat c_avx512bw_int8x64_storeu(intnat a, __m512i v)
{
    _mm512_storeu_epi8((void*)a, v); return 0;
}

intnat c_avx512f_float64x8_storeu(intnat a, __m512d v)
{
    _mm512_storeu_pd((void*)a, v); return 0;
}

intnat c_avx512f_float32x16_storeu(intnat a, __m512 v)
{
    _mm512_storeu_ps((void*)a, v); return 0;
}

__m128i c_avx512f_int32x4_load(intnat a)
{
    return _mm_load_epi32((void const*)a);
}

__m128i c_avx512f_int64x2_load(intnat a)
{
    return _mm_load_epi64((void const*)a);
}

__m128i c_avx512bw_int16x8_loadu(intnat a)
{
    return _mm_loadu_epi16((void const*)a);
}

__m128i c_avx512f_int32x4_loadu(intnat a)
{
    return _mm_loadu_epi32((void const*)a);
}

__m128i c_avx512f_int64x2_loadu(intnat a)
{
    return _mm_loadu_epi64((void const*)a);
}

__m128i c_avx512bw_int8x16_loadu(intnat a)
{
    return _mm_loadu_epi8((void const*)a);
}

__m128i c_avx512f_int32x4_load_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_load_epi32(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int64x2_load_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_load_epi64(src, (__mmask8)k, (void const*)a);
}

__m128d c_avx512f_float64x2_load_mask(__m128d src, intnat a, int64_t k)
{
    return _mm_mask_load_pd(src, (__mmask8)k, (void const*)a);
}

__m128 c_avx512f_float32x4_load_mask(__m128 src, intnat a, int64_t k)
{
    return _mm_mask_load_ps(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512bw_int16x8_loadu_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_loadu_epi16(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int32x4_loadu_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_loadu_epi32(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int64x2_loadu_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_loadu_epi64(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512bw_int8x16_loadu_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_loadu_epi8(src, (__mmask16)k, (void const*)a);
}

__m128d c_avx512f_float64x2_loadu_mask(__m128d src, intnat a, int64_t k)
{
    return _mm_mask_loadu_pd(src, (__mmask8)k, (void const*)a);
}

__m128 c_avx512f_float32x4_loadu_mask(__m128 src, intnat a, int64_t k)
{
    return _mm_mask_loadu_ps(src, (__mmask8)k, (void const*)a);
}

intnat c_avx512f_int32x4_store_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_store_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int64x2_store_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_store_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float64x2_store_mask(intnat a, __m128d v, int64_t k)
{
    _mm_mask_store_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x4_store_mask(intnat a, __m128 v, int64_t k)
{
    _mm_mask_store_ps((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_int16x8_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int32x4_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int64x2_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_storeu_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_int8x16_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_float64x2_storeu_mask(intnat a, __m128d v, int64_t k)
{
    _mm_mask_storeu_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x4_storeu_mask(intnat a, __m128 v, int64_t k)
{
    _mm_mask_storeu_ps((void*)a, (__mmask8)k, v); return 0;
}

__m128i c_avx512f_int32x4_load_maskz(intnat a, int64_t k)
{
    return _mm_maskz_load_epi32((__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int64x2_load_maskz(intnat a, int64_t k)
{
    return _mm_maskz_load_epi64((__mmask8)k, (void const*)a);
}

__m128d c_avx512f_float64x2_load_maskz(intnat a, int64_t k)
{
    return _mm_maskz_load_pd((__mmask8)k, (void const*)a);
}

__m128 c_avx512f_float32x4_load_maskz(intnat a, int64_t k)
{
    return _mm_maskz_load_ps((__mmask8)k, (void const*)a);
}

__m128i c_avx512bw_int16x8_loadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_loadu_epi16((__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int32x4_loadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_loadu_epi32((__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int64x2_loadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_loadu_epi64((__mmask8)k, (void const*)a);
}

__m128i c_avx512bw_int8x16_loadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_loadu_epi8((__mmask16)k, (void const*)a);
}

__m128d c_avx512f_float64x2_loadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_loadu_pd((__mmask8)k, (void const*)a);
}

__m128 c_avx512f_float32x4_loadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_loadu_ps((__mmask8)k, (void const*)a);
}

intnat c_avx512f_int32x4_store(intnat a, __m128i v)
{
    _mm_store_epi32((void*)a, v); return 0;
}

intnat c_avx512f_int64x2_store(intnat a, __m128i v)
{
    _mm_store_epi64((void*)a, v); return 0;
}

intnat c_avx512bw_int16x8_storeu(intnat a, __m128i v)
{
    _mm_storeu_epi16((void*)a, v); return 0;
}

intnat c_avx512f_int32x4_storeu(intnat a, __m128i v)
{
    _mm_storeu_epi32((void*)a, v); return 0;
}

intnat c_avx512f_int64x2_storeu(intnat a, __m128i v)
{
    _mm_storeu_epi64((void*)a, v); return 0;
}

intnat c_avx512bw_int8x16_storeu(intnat a, __m128i v)
{
    _mm_storeu_epi8((void*)a, v); return 0;
}

__m256 c_avx512f_float32x8_broadcast_f32x4(intnat a)
{
    return _mm256_broadcast_f32x4(_mm_loadu_ps((float const*)a));
}

__m512 c_avx512f_float32x16_broadcast_f32x4(intnat a)
{
    return _mm512_broadcast_f32x4(_mm_loadu_ps((float const*)a));
}

__m256d c_avx512dq_float64x4_broadcast_f64x2(intnat a)
{
    return _mm256_broadcast_f64x2(_mm_loadu_pd((double const*)a));
}

__m256i c_avx512f_int32x8_broadcast_i32x4(intnat a)
{
    return _mm256_broadcast_i32x4(_mm_loadu_si128((void const*)a));
}

__m512i c_avx512f_int32x16_broadcast_i32x4(intnat a)
{
    return _mm512_broadcast_i32x4(_mm_loadu_si128((void const*)a));
}

__m256i c_avx512dq_int64x4_broadcast_i64x2(intnat a)
{
    return _mm256_broadcast_i64x2(_mm_loadu_si128((void const*)a));
}

__m512i c_avx512dq_int64x8_broadcast_i64x2(intnat a)
{
    return _mm512_broadcast_i64x2(_mm_loadu_si128((void const*)a));
}

__m512i c_avx512dq_int32x16_broadcast_i32x8(intnat a)
{
    return _mm512_broadcast_i32x8(_mm256_loadu_si256((void const*)a));
}

__m512i c_avx512f_int64x8_broadcast_i64x4(intnat a)
{
    return _mm512_broadcast_i64x4(_mm256_loadu_si256((void const*)a));
}

__m128i c_avx512f_int32x4_broadcast_d(intnat a)
{
    return _mm_set1_epi32(*(int32_t const*)a);
}

__m256i c_avx512f_int32x8_broadcast_d(intnat a)
{
    return _mm256_set1_epi32(*(int32_t const*)a);
}

__m512i c_avx512f_int32x16_broadcast_d(intnat a)
{
    return _mm512_set1_epi32(*(int32_t const*)a);
}

__m128i c_avx512f_int64x2_broadcast_q(intnat a)
{
    return _mm_set1_epi64x(*(int64_t const*)a);
}

__m256i c_avx512f_int64x4_broadcast_q(intnat a)
{
    return _mm256_set1_epi64x(*(int64_t const*)a);
}

__m512i c_avx512f_int64x8_broadcast_q(intnat a)
{
    return _mm512_set1_epi64(*(int64_t const*)a);
}

__m256i c_avx512f_int32x8_expandloadu_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_expandloadu_epi32(src, (__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int64x4_expandloadu_mask(__m256i src, intnat a, int64_t k)
{
    return _mm256_mask_expandloadu_epi64(src, (__mmask8)k, (void const*)a);
}

__m256d c_avx512f_float64x4_expandloadu_mask(__m256d src, intnat a, int64_t k)
{
    return _mm256_mask_expandloadu_pd(src, (__mmask8)k, (void const*)a);
}

__m256 c_avx512f_float32x8_expandloadu_mask(__m256 src, intnat a, int64_t k)
{
    return _mm256_mask_expandloadu_ps(src, (__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int32x8_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_expandloadu_epi32((__mmask8)k, (void const*)a);
}

__m256i c_avx512f_int64x4_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_expandloadu_epi64((__mmask8)k, (void const*)a);
}

__m256d c_avx512f_float64x4_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_expandloadu_pd((__mmask8)k, (void const*)a);
}

__m256 c_avx512f_float32x8_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm256_maskz_expandloadu_ps((__mmask8)k, (void const*)a);
}

__m512i c_avx512f_int32x16_expandloadu_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_expandloadu_epi32(src, (__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int64x8_expandloadu_mask(__m512i src, intnat a, int64_t k)
{
    return _mm512_mask_expandloadu_epi64(src, (__mmask8)k, (void const*)a);
}

__m512d c_avx512f_float64x8_expandloadu_mask(__m512d src, intnat a, int64_t k)
{
    return _mm512_mask_expandloadu_pd(src, (__mmask8)k, (void const*)a);
}

__m512 c_avx512f_float32x16_expandloadu_mask(__m512 src, intnat a, int64_t k)
{
    return _mm512_mask_expandloadu_ps(src, (__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int32x16_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_expandloadu_epi32((__mmask16)k, (void const*)a);
}

__m512i c_avx512f_int64x8_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_expandloadu_epi64((__mmask8)k, (void const*)a);
}

__m512d c_avx512f_float64x8_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_expandloadu_pd((__mmask8)k, (void const*)a);
}

__m512 c_avx512f_float32x16_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm512_maskz_expandloadu_ps((__mmask16)k, (void const*)a);
}

__m128i c_avx512f_int32x4_expandloadu_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_expandloadu_epi32(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int64x2_expandloadu_mask(__m128i src, intnat a, int64_t k)
{
    return _mm_mask_expandloadu_epi64(src, (__mmask8)k, (void const*)a);
}

__m128d c_avx512f_float64x2_expandloadu_mask(__m128d src, intnat a, int64_t k)
{
    return _mm_mask_expandloadu_pd(src, (__mmask8)k, (void const*)a);
}

__m128 c_avx512f_float32x4_expandloadu_mask(__m128 src, intnat a, int64_t k)
{
    return _mm_mask_expandloadu_ps(src, (__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int32x4_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_expandloadu_epi32((__mmask8)k, (void const*)a);
}

__m128i c_avx512f_int64x2_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_expandloadu_epi64((__mmask8)k, (void const*)a);
}

__m128d c_avx512f_float64x2_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_expandloadu_pd((__mmask8)k, (void const*)a);
}

__m128 c_avx512f_float32x4_expandloadu_maskz(intnat a, int64_t k)
{
    return _mm_maskz_expandloadu_ps((__mmask8)k, (void const*)a);
}

intnat c_avx512f_int32x8_compressstoreu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_compressstoreu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int64x4_compressstoreu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_compressstoreu_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float64x4_compressstoreu_mask(intnat a, __m256d v, int64_t k)
{
    _mm256_mask_compressstoreu_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x8_compressstoreu_mask(intnat a, __m256 v, int64_t k)
{
    _mm256_mask_compressstoreu_ps((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int32x16_compressstoreu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_compressstoreu_epi32((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_int64x8_compressstoreu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_compressstoreu_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float64x8_compressstoreu_mask(intnat a, __m512d v, int64_t k)
{
    _mm512_mask_compressstoreu_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x16_compressstoreu_mask(intnat a, __m512 v, int64_t k)
{
    _mm512_mask_compressstoreu_ps((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_int32x4_compressstoreu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_compressstoreu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int64x2_compressstoreu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_compressstoreu_epi64((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float64x2_compressstoreu_mask(intnat a, __m128d v, int64_t k)
{
    _mm_mask_compressstoreu_pd((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_float32x4_compressstoreu_mask(intnat a, __m128 v, int64_t k)
{
    _mm_mask_compressstoreu_ps((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x16_int8x16_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtepi16_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int32x8_int16x8_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtepi32_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x8_int8x8_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtepi32_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int16x4_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int32x4_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int8x4_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x16_int8x16_saturating_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtsepi16_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int32x8_int16x8_saturating_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtsepi32_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x8_int8x8_saturating_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtsepi32_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int16x4_saturating_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtsepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int32x4_saturating_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtsepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int8x4_saturating_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtsepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x16_int8x16_saturating_unsigned_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtusepi16_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int32x8_int16x8_saturating_unsigned_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtusepi32_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x8_int8x8_saturating_unsigned_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtusepi32_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int16x4_saturating_unsigned_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtusepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int32x4_saturating_unsigned_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtusepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x4_int8x4_saturating_unsigned_storeu_mask(intnat a, __m256i v, int64_t k)
{
    _mm256_mask_cvtusepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x32_int8x32_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtepi16_storeu_epi8((void*)a, (__mmask32)k, v); return 0;
}

intnat c_avx512f_cvt_int32x16_int16x16_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtepi32_storeu_epi16((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int32x16_int8x16_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtepi32_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int16x8_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int32x8_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int8x8_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x32_int8x32_saturating_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtsepi16_storeu_epi8((void*)a, (__mmask32)k, v); return 0;
}

intnat c_avx512f_cvt_int32x16_int16x16_saturating_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtsepi32_storeu_epi16((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int32x16_int8x16_saturating_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtsepi32_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int16x8_saturating_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtsepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int32x8_saturating_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtsepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int8x8_saturating_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtsepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x32_int8x32_saturating_unsigned_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtusepi16_storeu_epi8((void*)a, (__mmask32)k, v); return 0;
}

intnat c_avx512f_cvt_int32x16_int16x16_saturating_unsigned_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtusepi32_storeu_epi16((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int32x16_int8x16_saturating_unsigned_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtusepi32_storeu_epi8((void*)a, (__mmask16)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int16x8_saturating_unsigned_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtusepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int32x8_saturating_unsigned_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtusepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x8_int8x8_saturating_unsigned_storeu_mask(intnat a, __m512i v, int64_t k)
{
    _mm512_mask_cvtusepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x8_int8x8_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtepi16_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x4_int16x4_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtepi32_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x4_int8x4_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtepi32_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int16x2_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int32x2_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int8x2_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x8_int8x8_saturating_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtsepi16_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x4_int16x4_saturating_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtsepi32_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x4_int8x4_saturating_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtsepi32_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int16x2_saturating_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtsepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int32x2_saturating_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtsepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int8x2_saturating_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtsepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512bw_cvt_int16x8_int8x8_saturating_unsigned_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtusepi16_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x4_int16x4_saturating_unsigned_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtusepi32_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int32x4_int8x4_saturating_unsigned_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtusepi32_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int16x2_saturating_unsigned_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtusepi64_storeu_epi16((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int32x2_saturating_unsigned_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtusepi64_storeu_epi32((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_cvt_int64x2_int8x2_saturating_unsigned_storeu_mask(intnat a, __m128i v, int64_t k)
{
    _mm_mask_cvtusepi64_storeu_epi8((void*)a, (__mmask8)k, v); return 0;
}

intnat c_avx512f_int32x8_i32scatter_mask(intnat a, __m256i idx, __m256i v, int64_t k)
{
    _mm256_mask_i32scatter_epi32((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int64x4_i32scatter_mask(intnat a, __m128i idx, __m256i v, int64_t k)
{
    _mm256_mask_i32scatter_epi64((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float64x4_i32scatter_mask(intnat a, __m128i idx, __m256d v, int64_t k)
{
    _mm256_mask_i32scatter_pd((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float32x8_i32scatter_mask(intnat a, __m256i idx, __m256 v, int64_t k)
{
    _mm256_mask_i32scatter_ps((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int32x4_i64scatter_mask(intnat a, __m256i idx, __m128i v, int64_t k)
{
    _mm256_mask_i64scatter_epi32((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int64x4_i64scatter_mask(intnat a, __m256i idx, __m256i v, int64_t k)
{
    _mm256_mask_i64scatter_epi64((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float64x4_i64scatter_mask(intnat a, __m256i idx, __m256d v, int64_t k)
{
    _mm256_mask_i64scatter_pd((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float32x4_i64scatter_mask(intnat a, __m256i idx, __m128 v, int64_t k)
{
    _mm256_mask_i64scatter_ps((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int32x16_i32scatter_mask(intnat a, __m512i idx, __m512i v, int64_t k)
{
    _mm512_mask_i32scatter_epi32((void*)a, (__mmask16)k, idx, v, 4); return 0;
}

intnat c_avx512f_int64x8_i32scatter_mask(intnat a, __m256i idx, __m512i v, int64_t k)
{
    _mm512_mask_i32scatter_epi64((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float64x8_i32scatter_mask(intnat a, __m256i idx, __m512d v, int64_t k)
{
    _mm512_mask_i32scatter_pd((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float32x16_i32scatter_mask(intnat a, __m512i idx, __m512 v, int64_t k)
{
    _mm512_mask_i32scatter_ps((void*)a, (__mmask16)k, idx, v, 4); return 0;
}

intnat c_avx512f_int32x8_i64scatter_mask(intnat a, __m512i idx, __m256i v, int64_t k)
{
    _mm512_mask_i64scatter_epi32((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int64x8_i64scatter_mask(intnat a, __m512i idx, __m512i v, int64_t k)
{
    _mm512_mask_i64scatter_epi64((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float64x8_i64scatter_mask(intnat a, __m512i idx, __m512d v, int64_t k)
{
    _mm512_mask_i64scatter_pd((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float32x8_i64scatter_mask(intnat a, __m512i idx, __m256 v, int64_t k)
{
    _mm512_mask_i64scatter_ps((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int32x4_i32scatter_mask(intnat a, __m128i idx, __m128i v, int64_t k)
{
    _mm_mask_i32scatter_epi32((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int64x2_i32scatter_mask(intnat a, __m128i idx, __m128i v, int64_t k)
{
    _mm_mask_i32scatter_epi64((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float64x2_i32scatter_mask(intnat a, __m128i idx, __m128d v, int64_t k)
{
    _mm_mask_i32scatter_pd((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float32x4_i32scatter_mask(intnat a, __m128i idx, __m128 v, int64_t k)
{
    _mm_mask_i32scatter_ps((void*)a, (__mmask8)k, idx, v, 4); return 0;
}

intnat c_avx512f_int64x2_i64scatter_mask(intnat a, __m128i idx, __m128i v, int64_t k)
{
    _mm_mask_i64scatter_epi64((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

intnat c_avx512f_float64x2_i64scatter_mask(intnat a, __m128i idx, __m128d v, int64_t k)
{
    _mm_mask_i64scatter_pd((void*)a, (__mmask8)k, idx, v, 8); return 0;
}

int64_t c_avx512f_load_mask16(intnat a)
{
    return (int64_t)_load_mask16((void const*)a);
}

int64_t c_avx512bw_load_mask32(intnat a)
{
    return (int64_t)_load_mask32((void const*)a);
}

int64_t c_avx512bw_load_mask64(intnat a)
{
    return (int64_t)_load_mask64((void const*)a);
}

int64_t c_avx512dq_load_mask8(intnat a)
{
    return (int64_t)_load_mask8((void const*)a);
}

intnat c_avx512f_store_mask16(intnat a, int64_t k)
{
    _store_mask16((void*)a, (__mmask16)k); return 0;
}

intnat c_avx512bw_store_mask32(intnat a, int64_t k)
{
    _store_mask32((void*)a, (__mmask32)k); return 0;
}

intnat c_avx512bw_store_mask64(intnat a, int64_t k)
{
    _store_mask64((void*)a, (__mmask64)k); return 0;
}

intnat c_avx512dq_store_mask8(intnat a, int64_t k)
{
    _store_mask8((void*)a, (__mmask8)k); return 0;
}

#endif
