# CYBERSECURITY WARNING: DO NOT give workflows write permission to any source code repo.
# If you want this functionality, ask for help from a subset of:
# @jvanburen @glittershark @mshinwell
name: conflicts
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  merge_group:
jobs:
  check:
    name: Conflicts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - system: x86_64-linux
            os: warp-ubuntu-latest-x64-32x
    steps:
      - name: Checkout the OxCaml repo
        uses: actions/checkout@master

      - name: Check for conflict markers
        run: bash tools/ci/actions/check-conflicts.sh
