# CYBERSECURITY WARNING: Do not expose secrets to runners without consulting with repo owners

name: Nix Flake Actions

on:
  pull_request:
  push:

jobs:
  nix-matrix:
    runs-on: warp-ubuntu-latest-arm64-8x
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeuo pipefail
          matrix="$(nix eval --json '.#githubActions.matrix')"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - run: nix build -L '.#${{ matrix.attr }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
