name: Nix Flake actions

on:
  pull_request:
  push:

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
          nix eval --json '.#githubActions.matrix' |
            jq -c '.include |= map(select(.os | startsWith("macos-") | not))' |
            cat <(echo -n matrix=) - >> "$GITHUB_OUTPUT"

  # jvanburen 2025-10-08: our macOS CI capacity is limited, so i enabled fail-fast and
  # disabled macos runners for now to help hopefully improve queueing time. we should
  # revert these changes once we get more capacity
  nix-build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: nix-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix build -L '.#${{ matrix.attr }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
